Fix #974 Extra infromation on Profile
ONEARMY/community-platform pull request #1031
Opened 2020-09-05 15:39 UTC by alromh87

Shows information on user profile
- [x] Location with link to map pin
- [x] Accepted HowTos
- [x] Accepted Events

User stats are computed via firebase function triggered by database changes

2020-09-05 19:52 UTC, alromh87 commented
This profiles show different validations:

- alromh87
  - Pin
  - Events
  - HowTos
- bentest12
  - Only Pin
- 7pgee0qxlzmdbxmfdtbe4hcdzom2
  - Only HowTos
- 4vd2ejopw1ftcunhj01o8vpbgq62
  - Only Event
- 1qsijzipovtkqrryfavkzc1dzd93
  - No Pins, events or howTos

As requested in #974

2020-09-10 09:41 UTC, BenGamma requested changes
If I understand well the counts for how-to and events will be triggered on creation or on edit right ?
So to have this information available we'll need to modify all the existing howtos and events ? I'm trying to understand how we are going to proceed for migration.
Other than that see my comments for small changes.
Thanks for the work !

2020-09-10 09:41 UTC, BenGamma commented on src/components/ElWithBeforeIcon/index.tsx
> +  mr?: number
In that case it will be better to extend the props from rebass BoxProps directly, but I don't think you need to add it here, and I don't see it used anywhere else anyway ?

2020-09-10 09:41 UTC, BenGamma commented on src/models/user.models.tsx
> +  _stats?: IUserStats
Here can you rename `stats` without underscore ? We keep the underscore variables to distinct the existing variables in a package or a library and the ones we add are without

2020-09-10 12:54 UTC, alromh87 commented on src/components/ElWithBeforeIcon/index.tsx
> +  mr?: number
It was needed to be able to change the margin of the internal box, which had it fixed to 4, now it will default to 4(avoid braking other displays), but can be overwiten when usng component, used to make howto event display in one line

2020-09-10 13:08 UTC, alromh87 commented on src/models/user.models.tsx
> +  _stats?: IUserStats
Done :smile:

2020-09-14 10:40 UTC, BenGamma commented
> Functions are at [functions/src/Integrations/user-stats.ts ](https://github.com/ONEARMY/community-platform/commit/40b7deb8073677b2518906acb444bca19081df44), I gess I'm missing some config since they where not deployed.

As far as I know they will need to be deployed on firebase once merged with master.

> I already have script for the initial calculation and update of user.stats for migration, this would be executed just once, after that updates will be calculated based on individual howto/event data, for faster execution

Ok nice, can I see this script ?

2020-09-14 11:41 UTC, BenGamma commented
I added a commit so I had to create a new branch and new PR, discussion moved to #1040

2020-09-14 11:41 UTC, closed without merging

2020-09-14 12:39 UTC, alromh87 commented
https://github.com/ONEARMY/community-platform/pull/1040#issuecomment-692024726