Feat/user stats migration
ONEARMY/community-platform pull request #1055
Opened 2020-10-12 06:26 UTC by chrismclarke

## Description

Additional scripts and tidying to support user stats migration. 
### Main Changes:

- Refactor userStats to own folder (with consistent naming for exports)
- Add stricter typings
- Code-tidy stat count functions
- Add one-time migration script for initial stats population for all users, accounting for all events and howtos

### Todo before merge
- Identify any additional migration tasks (e.g. current scripts for locations and possibly tidying some of legacy user id issues)
- Decide whether to create new db endpoint (e.g. v4_users) or use existing. Update frontend code accordingly

## Git Issues

_Closes #_

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

2020-10-12 08:15 UTC, alromh87 commented on src/models/user.models.tsx
> +  userCreatedHowtos: number
Frontend would need to update accordingly

2020-10-12 12:08 UTC, alromh87 requested changes
I feel like the dessired rsult would not be achived with the changes as they are now.

2020-10-12 12:08 UTC, alromh87 commented on functions/src/index.ts
> -import * as UserTriggers from './Integrations/user-triggers'
The purpose of this trigger is to update howTo's flag in case a user update his location, so if this behaviour is dessired  the trigger should be enabled.

This trigger could be used as well for handling when user requests username change, bt thats longer story.

2020-10-12 12:17 UTC, alromh87 requested changes
Few more comments

2020-10-12 12:17 UTC, alromh87 commented on functions/src/userStats/migration.ts
> +export const migrateUserStats = functions.https.onCall(
Still unsure here but looks to me, from my testing, that calling the function this way migth lead to reaching firestore maximum execution time without producing any result, so next time is executed start from the begginig would be needed, again failing.

Because getting all events, howtos, users proccessing and updating and not keeping track of already updated  users.

2020-10-12 12:17 UTC, alromh87 commented on functions/src/userStats/migration.ts
> +  howtos.forEach(v => {
Same as https://github.com/ONEARMY/community-platform/pull/1055/files/7928f26fcfdd5a8c0c08d8745e1ea8ba2e87f106#r503244379

2020-10-12 14:46 UTC, chrismclarke commented on functions/src/userStats/migration.ts
> +  events.forEach(v => {
Parallel here is fine as we're not running any async code (it's just taking an array and converting to an object). But yeah, otherwise choices are to use a `for-of` loop which works in series, or create a new array or map to record each op as a promise (e.g. `promises= someLoop.forEach(v=>promises.push(someAsyncFunc(v))` and use `await Promise.all(promises)` to carry out in parallel. The downside to the second approach is the function will fail if any one promise fails, however any individual promise that passed up until that point will still have be updated.

The exception to this is when writing db docs, firebase has an inbuilt method called `batch`, where you can run ops on up to 500 docs in parallel once per second.

2020-10-12 14:49 UTC, chrismclarke commented on functions/src/index.ts
> -import * as UserTriggers from './Integrations/user-triggers'
Ah that makes sense, and yeah could to have a place to record any side-effects for user changes. There's actually another (poorly named function) that listens for user updates also to automatically create a user backup (`FirebaseUserBackup`), so I'll probably merge these into a single function and document a bit better

2020-10-12 14:51 UTC, chrismclarke commented on functions/src/userStats/migration.ts
> +export const migrateUserStats = functions.https.onCall(
Oh, I hadn't actually thought about timeout issues, but yes you are right that could happen. There is actually a way to manually increase timeouts for a specific function: https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation, but nonetheless I'll do some testing and optimise for this.

2020-10-12 14:58 UTC, chrismclarke commented on functions/src/userStats/migration.ts
> +  console.log('allHowTosByUser', allHowTosByUser)
Thanks!

2020-10-13 04:36 UTC, chrismclarke commented
OK, I think it should now be good to go. I've run against dev and seems to be working as expected, and did a test run on live (no db writes, just logging what would be changed) and seems reasonable. Output attached.
Thanks for your work on this @alromh87 .
@BenGamma - let me know when you want to do the next release and I can run against production and update functions.
[userMigrate_Live-1602563518371.log](https://github.com/ONEARMY/community-platform/files/5368948/userMigrate_Live-1602563518371.log)

2020-10-13 12:05 UTC, alromh87 requested changes
LGTM

Just one change needed to update frontend howto list when user updates location.

I don't see the flag batch update though

2020-10-13 12:05 UTC, alromh87 commented on functions/src/userUpdates/index.ts
> +        .update({ creatorCountry: country })
Adding `'_modified': new Date().toISOString()`  will show the new info on the frontend, thanks for the info Chris :wink:

2020-10-13 13:46 UTC, BenGamma approved these changes
Thanks a lot guys, I'm not a specialist in the backend optimisation but what I see looks good to me ! Special mention for updating the documentation as well 👍 
@chrismclarke I'll create a PR for the new release v1.3 to production branch. I'll leave it to you to press merge button and run the migration script once merged in production.

2020-10-13 13:47 UTC, BenGamma commented on functions/src/userUpdates/index.ts
> +        .update({ creatorCountry: country })
thanks @alromh87 👌

2020-10-13 13:48 UTC, merged