[WIP] Useful button
ONEARMY/community-platform pull request #1074
Opened 2020-11-14 21:52 UTC by tudi2d

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

PR Checklist

- [ ] - Latest `master` branch merged
- [ ] - PR title descriptive (can be used in release notes)
- [ ] - Passes Tests

## Description

_What this PR does_

## Git Issues

_Closes #_

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

2020-11-17 11:13 UTC, BenGamma requested changes
Thanks man for the work 💪 
I noticed there are a lot of test failing, probably due to the fact that the new button is not expected. Can you have a look at the tests and fix them ? There is a section in [the wiki](https://github.com/ONEARMY/community-platform/wiki/E2E-Testing) about it

2020-11-17 11:13 UTC, BenGamma commented on src/models/user.models.tsx
> +  usefUlHowTos: string[]
Change capital U here, it should be `usefulHowTos`

2020-11-17 16:42 UTC, tudi2d commented
@BenGamma Thanks! Yes, sure - will fix the failing test as soon as everything is implemented and change the status from draft to PR then! Should find time for this in the next days! :)

2021-01-31 21:09 UTC, chrismclarke reviewed
Thanks again for this @tudi2d and sorry it's taken so long to review.

I really like the new feature overall, especially the separation between users recording on their own profile and just reflecting the total value on the howto. I've taken this one step further and actually moved that second piece of logic to a backend function to be triggered automatically (that way if a user disconnects or multiple users try to update at the same time data won't get lost).

I also realised one fundamental issue with how firestore operates, meaning that we will need to rethink how we display the final total. I've created a new PR with your changes and my edits on top at #1094, alongside more explanation of the changes (specifically c74562496580c95d0a4fe25c5be4a483a2654894)

2021-01-31 21:09 UTC, chrismclarke commented
merging into #1094

2021-01-31 21:09 UTC, closed without merging