Feat/notifications
ONEARMY/community-platform pull request #1367
Opened 2022-01-02 22:15 UTC by patrycjapraczyk

PR Checklist

- [ ] - Latest `master` branch merged
- [ ] - PR title descriptive (can be used in release notes)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

This PR added notifications to user profile. They are triggered when another user votes 'useful' or comments on their how-to. The notifications are shown under the thunderbolt icon in a pop-up. The user can 'clear notifications', which marks them as 'read' and removes them from the pop-up.

## Git Issues

Closes [#1199](https://github.com/ONEARMY/community-platform/issues/1199)

## Screenshots/Videos

No notifications:

Desktop:
![image](https://user-images.githubusercontent.com/35103888/147890202-03d0d6d1-51ac-467f-836d-e71f0c45ef7c.png)

Mobile:
![image](https://user-images.githubusercontent.com/35103888/147890215-fa104ac2-3bde-4442-a8d2-e49e611243f2.png)

There are notifications:

Desktop:
![image](https://user-images.githubusercontent.com/35103888/147890687-71bb221a-fbaf-4b2f-b040-918cd65296af.png)

Mobile:
![image](https://user-images.githubusercontent.com/35103888/147890755-c8c29abf-32b1-4f1b-80b4-4ed028ad8a3d.png)

2022-01-03 09:40 UTC, thisislawatts commented
@patrycjapraczyk this looks great. Thanks for raising the PR. Will you be able to make the monthly call today? I thought it would be fun to demo the things that we are working on.

2022-01-03 15:01 UTC, patrycjapraczyk commented
Thanks Luke! Unfortunately I'll not be able to make it to the call today,
as I'll be en route. But I'd be happy to demo the feature at some other
time, also to speed up the PR review.

On Mon, Jan 3, 2022, 10:40 AM Luke Watts ***@***.***> wrote:

> @patrycjapraczyk <https://github.com/patrycjapraczyk> this looks great.
> Thanks for raising the PR. Will you be able to make the monthly call today?
> I thought it would be fun to demo the things that we are working on.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ONEARMY/community-platform/pull/1367#issuecomment-1003971441>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIL2JEC34KRZPHOCZ7X45Q3UUFVIHANCNFSM5LEEAQXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-03 17:41 UTC, thisislawatts commented
It would be great to look through this together. My calendar is public and you can find my availability here:
https://calendly.com/luke_____watts/

Please book a slot that works for you and we can walk through this. I will add some comments to the PR in the meantime.

2022-01-03 20:56 UTC, thisislawatts commented on src/components/Notifications/NotificationItem.tsx
> +                  by&nbsp;
**question (nitpick):** Do we need these `&nbsp;` characters?
Maybe there's a small CSS change we can make to these unnecessary

2022-01-03 20:56 UTC, thisislawatts commented on src/models/user.models.tsx
> +  triggeredByName: string,
**Suggestion (non-blocking):** Create a structured entity:

Rather than storing two properties here, we could create a structured entity, such as:

```suggestion
  triggeredBy: {
    type: 'user' | 'system' // Imagining a future where notifications can be triggered by other events
    displayName: string, 
    userId?: string,
  }
```

2022-01-03 20:56 UTC, thisislawatts commented on src/models/user.models.tsx
> +  howToId?: string,
**Suggestion:** Simplify the data structure, and remove the need for the render method to know anything about the how to build the click through URL. 

What do you think? 

```suggestion
  callToActionUrl?: string,
```

Rather than containing multiple

2022-01-04 19:19 UTC, patrycjapraczyk commented on package.json
> +
I removed "node-sass" just so that the project runs on my Mac and pushed this by accident. Do we still use this though? It seems to be deprecated [here](https://www.npmjs.com/package/node-sass)

2022-01-04 19:20 UTC, patrycjapraczyk commented on src/components/Notifications/NotificationItem.tsx
> +                  by&nbsp;
I could try to add some padding there to `Link` components. Do you think this would be a better solution?

2022-01-04 19:38 UTC, patrycjapraczyk commented on src/models/user.models.tsx
> +  triggeredByName: string,
Good idea but we could add the type just when it's needed.

2022-01-04 20:02 UTC, thisislawatts commented on src/models/user.models.tsx
> +  triggeredByName: string,
Absolutely! We were talking about this notifications feature during the monthly dev call and got excited about being able to push out notifications which surface new features, etc.

2022-01-04 20:04 UTC, thisislawatts commented on src/components/Notifications/NotificationItem.tsx
> +                  by&nbsp;
I think if these characters are being introduced to address a visual issue we should instead try to use CSS to implement it.

2022-01-04 20:07 UTC, thisislawatts commented on package.json
> +
Oh great spot, I wonder how easy it would be to switch across to dart-sass. I will raise an issue to track this work.

2022-01-04 21:27 UTC, patrycjapraczyk commented on src/models/user.models.tsx
> +  howToId?: string,
I've realised just now that `commentId` is not being used anywhere, so this could definitely be removed. 
Just to make sure I understand this correctly: with `callToActionUrl` in the case of how-tos you'd store a url to a relevant how-to, for example: `/how-to/testing-notifications1` ?

2022-01-05 14:57 UTC, davehakkens commented
Wauw thanks a lot for this PR @patrycjapraczyk, very exciting feature
1. I've tested locally but didn't always receive a notification. Most of the time on a `comment`, never on `useful`. That said i'm not sure if it has to do anything with the `beta-tester` role, local setup or some build errors. So i'll wait with deeper testing until you and @thisislawatts work out the functionality a bit more.👆 (do let me know if you need me help testing somewhere)
2. I have some additional tiny remarks to layout, some padding, sizing, margins etc. To align it a bit more with the [original layout](https://community-platform.webflow.io/u/how-to-with-notification) Would you like me to point them out specifically now or prefer to get the function running first so we can test better and then go in details?

For the rest all good 💪

2022-01-05 17:07 UTC, patrycjapraczyk commented
Hi @davehakkens and thanks for your comments.
I will try to align the styling to the original layout.
For allowing me to test the feature better: do you know how I could change the status of my how-to, so that it's not "Awaiting moderation"?

2022-01-05 17:11 UTC, davehakkens commented
> Hi @davehakkens and thanks for your comments. I will try to align the styling to the original layout. What do you think about the mobile version? To allow me to test the feature better: do you know how I could change the status of my how-to, so that it's not "Awaiting moderation"?

You need to be an `admin` to approve a how-to
If you give me your username I can make you an admin on [dev.onearmy.world](https://dev.onearmy.world)
Would that work?

2022-01-05 17:16 UTC, patrycjapraczyk commented
My username is: `patrycja` and email `praczyk.patrycja@gmail.com` . 
I thought I could set myself as admin via "View as: admin" option on the top dev bar.

2022-01-05 17:23 UTC, davehakkens commented
> My username is: `patrycja` and email `praczyk.patrycja@gmail.com` . I thought I could set myself as admin via "View as: admin" option on the top dev bar but could not find an option to approve the how-to.

Added as an admin on dev.onearmy.world
If you (or anyone) creates a how-to now it should send a notification in our Slack channel #community-notifications-dev This has a url to the how-to to approve.
Alternatively, you should be able to see the how-to in the main how-to overview 
If you go there you can click/approve 
<img width="638" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/148260901-bd31b89b-282c-4c63-896b-945b95a0ffb6.png">

Good point about the "views as admin" not sure if it actually does the same thing. Never used it like that..

2022-01-05 18:06 UTC, patrycjapraczyk commented
Thanks @davehakkens . 

I am still facing some issues: 
- can't see delete or click/approve buttons
![image](https://user-images.githubusercontent.com/35103888/148265361-221c04a8-79f6-4d83-b724-62fe26f9a83d.png)
- I can't see the how-to I created locally that's awaiting moderation on [dev.onearmy.world](https://dev.onearmy.world/academy/intro.html). Is that normal?

Would it be possible to add me to ONE ARMY org on Slack? I was a guest in #platform-dev channel but can't access it anymore, as I've run out of the Slack pro trial.

2022-01-05 19:42 UTC, davehakkens commented
>     can't see delete or click/approve buttons locally

You only see the buttons for not approved how-to's. Once approved all buttons go away

> I can't see the how-to I created locally that's awaiting moderation on dev.onearmy.world. Is that normal?

To be honest i'm not sure 100% sure how synced the local database is with the database from dev.onearmy.world. A bit of a blackhole there for me..

Added you on Slack. Feel free to send me a message there to continue the coversation

2022-01-05 19:48 UTC, thisislawatts commented on src/models/user.models.tsx
> +  howToId?: string,
That's right. I understand the requirement as:
A user is able to click a notification to navigate to the subject matter.

This means that if I get a notification about a Howto receiving a Useful vote I can click through to see the Howto.

2022-01-27 19:43 UTC, thisislawatts requested changes

2022-01-27 19:43 UTC, thisislawatts commented on src/pages/common/Header/Header.tsx
> +    const areThereNotifications = !(user?.notifications?.filter(notification => !notification.read).length === 0);
**issue (blocking):** The existing statement does not resolve to the correct value. As a result I was seeing the notification icon appear with a highlight even though there were no notifications to read.

```suggestion
    const areThereNotifications = Boolean(
      user?.notifications?.length &&
        !(
          user?.notifications?.filter(notification => !notification.read)
            .length === 0
        ),
    )
```


I believe the reason for this is that the original statement would resolve eventually resolve to a falsy value which was then wrapped with `!(...)` reverting it to true. However there can never be notifications unless user.notifications.length

I've spun up a small example in the Typescript Playground to demonstrate the differences in behaviour: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgHIHszBsBcvojIDeAUMhclBHACYBcyARuugDY0gDcpAvqaVCRYiFAAU4ULHDYBVAM7QS5SiEzZc+YIXmMMWHHgIgA2gF0+AhDrDIAroqjIAvCV7I485BKnAZC6B5rEHlbSQgAFQALaAh9DSNtEJdkAEIACgdoAH4AOjUDTWN5PJw2YXSChK1CFwA+NKrDGpBc6joASlyOEABzMCiXZ1cABg7SYPl2CG70XvTicOjY+Obi3nGKCZsPamXqACUaNjYAT1WipK9XACFWDjgQdJVKe0c8psudPJ7+wYAyf4vV5pZ4gkFZKAfdRrK6lYDlaCVGFfIjOBqpT6JQhtGi0TbgkHdCB9AZDUbA14dAA0wPG2xC01m80Wexih2OZwu2JCGy4QA

2022-01-27 19:57 UTC, thisislawatts commented on src/pages/common/Header/Menu/Notifications/NotificationsMobile.tsx
> +                    Nada, no new notification
**suggestion:** The is a "fun" one from the English language, but when talking about zero values we should always pluralize the noun. Found this little thread on it:
https://english.stackexchange.com/questions/38293/why-is-zero-followed-by-a-plural-noun

```suggestion
                    Nada, no new notifications
```

2022-01-27 19:59 UTC, thisislawatts commented on src/stores/User/user.store.ts
> +      console.error(err)
**nitpick (non-blocking):** Instead of `console.error` use `logger.error` which will ensure this message gets aggregated out of an individual browser to a service like logflare.app. This will improve our visibility into issues

2022-01-29 14:05 UTC, patrycjapraczyk commented on src/pages/common/Header/Header.tsx
> +    const areThereNotifications = !(user?.notifications?.filter(notification => !notification.read).length === 0);
Hm, this would work fine when running the project but not when running the tests, that's why I missed it Added this change to make it more foolproof, thank you for the suggestion!

2022-02-02 09:10 UTC, davehakkens commented
uhmm.. So.. I wanted to pull the edits locally and give it a test run. But I think doing so it merged the [old branch](https://github.com/ONEARMY/community-platform/pull/1367/commits/6c773205a18e9ad0ad6d0bd239feec42a17cf577) again?
<img width="900" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/152124256-b8c189ab-c1d0-4e22-a731-e25264939360.png">
I'm not sure why this is happening, i tried to revert but still seems like it changed some files.`  .circleci/config.yml`
`yarn.lock `
Looks like the same that happened a few days ago with the PR from jojudre @thisislawatts 
Very sorry for making a mess here. :(

2022-02-05 20:13 UTC, patrycjapraczyk commented
Hey @davehakkens not sure what you've done lol but this should be me reverting your last 2 commits

> uhmm.. So.. I wanted to pull the edits locally and give it a test run. But I think doing so it merged the [old branch](https://github.com/ONEARMY/community-platform/pull/1367/commits/6c773205a18e9ad0ad6d0bd239feec42a17cf577) again? <img alt="afbeelding" width="900" src="https://user-images.githubusercontent.com/13672737/152124256-b8c189ab-c1d0-4e22-a731-e25264939360.png"> I'm not sure why this is happening, i tried to revert but still seems like it changed some files.` .circleci/config.yml` `yarn.lock ` Looks like the same that happened a few days ago with the PR from jojudre @thisislawatts Very sorry for making a mess here. :(

2022-02-06 09:22 UTC, davehakkens commented
I would love to @patrycjapraczyk but this desktop thing is still scaring me.
Conflicts when pulling code in and it always wants me to push something back in the branch.
I think I need to watch a few more tutorial videos first :|

Would you say its ready for final review?


<img width="1000" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/152674512-fcaacf31-5368-4ebc-ab50-5d2ec487015d.png">

2022-02-06 15:01 UTC, patrycjapraczyk commented
Hey @davehakkens it's ready for the final review. I'm just struggling to correct the commit messages ever since you pushed the changes my branch, not sure what happened there, so the lint tests are not passing.

I'm going to send you a Slack message with what I think would work for testing the changes on my branch

2022-02-08 20:44 UTC, closed without merging