docs: add frontend module docs
ONEARMY/community-platform pull request #1410
Opened 2022-01-26 02:59 UTC by chrismclarke

PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Developer experience (improves developer workflows for contributing to the project)

## Description

Provides documentation to outline steps required to add new modules to the platform.
This follows pr proposed in #1394 to add a new testing module, which in turn was intended to facilitate testing code from #1393

## Git Issues

Closes #1394

## Screenshots/Videos

![localhost_3001_Frontend%20Development_modules](https://user-images.githubusercontent.com/10515065/151096577-049b829a-ad5b-4e9d-8ad8-f2f4369bc066.png)

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

2022-01-29 04:47 UTC, thisislawatts requested changes

2022-01-29 04:47 UTC, thisislawatts commented on packages/documentation/docs/Frontend Development/modules.md
> +The platform consists of multiple _modules_ which provide the building blocks the app features and core functionality. Examples include features such as _howtos_, _events_ and _research_, alongside c
**nitpick (blocking):** Do we really want to frame database as a module? It seems like to much of a shared dependency for it to be considered a module.

I wonder if the same applies for the idea of a User.

2022-01-29 04:47 UTC, thisislawatts commented on packages/documentation/docs/Frontend Development/modules.md
> +## Module Folder
**Suggestion:** given we do not yet have any modules which conform to this structure perhaps we should refer to it as a Proposed Module Folder Structure?

2022-02-01 02:49 UTC, chrismclarke commented on packages/documentation/docs/Frontend Development/modules.md
> +The platform consists of multiple _modules_ which provide the building blocks the app features and core functionality. Examples include features such as _howtos_, _events_ and _research_, alongside c
yeah, the I've never really understood why we have both a profile and settings page for users/workspaces, I find it all a bit confusing. I'll remove the core module reference for now until we decide in the future what is actually core/non

2022-02-01 02:55 UTC, chrismclarke commented on packages/documentation/docs/Frontend Development/modules.md
> +## Module Folder
Yeah, this has definitely been a bit of a minor grievance for me ever since we created the first stores. It's never really made sense to me the level of separation between pages and stores, pretty much guarantees when working on most frontend code still jumping forwards and backwards between multiple directories. I'll add a note

2022-02-01 03:11 UTC, chrismclarke commented
text updated as:

![image](https://user-images.githubusercontent.com/10515065/151907803-4592086d-c2f2-4a1f-89cc-3f08ff2ac843.png)

2022-02-01 05:53 UTC, thisislawatts approved these changes

2022-02-02 06:06 UTC, merged

2022-02-04 20:11 UTC, thisislawatts commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on [GitHub release](https://github.com/ONEARMY/community-platform/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-02-05 09:53 UTC, thisislawatts commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on [GitHub release](https://github.com/ONEARMY/community-platform/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: