Feat/db aggregations alt
ONEARMY/community-platform pull request #1450
Opened 2022-02-03 06:46 UTC by chrismclarke

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Latest `master` branch merged

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

2022-02-03 06:51 UTC, chrismclarke commented on functions/src/aggregations/user.aggregations.ts
> +
This is the current proposed syntax. For any aggregator that simply wants to copy value to top-level aggregation all that is required is `field` and `aggregationField`. For more complex aggregations overrides are exposed for core methods

2022-02-03 06:52 UTC, chrismclarke commented on functions/src/aggregations/user.aggregations.ts
> +/** Watch changes to all user docs and apply aggregations */
A single function will listen for any changes to users and handle all listed aggregations

2022-02-03 06:54 UTC, chrismclarke commented on functions/src/aggregations/common.aggregations.ts
> +export async function handleDBAggregations(
This is the main exposed method that can be called by any observer to handle aggregation changes (e.g. changes to user, howto or event collections). It handles checking for specific field-level changes and triggering aggregation as required

2022-02-03 06:55 UTC, chrismclarke commented on functions/src/aggregations/common.aggregations.ts
> +export class AggregationHandler {
The code that handles the actual aggregation functions is contained in a class (for easier variable sharing and exposing override options).

2022-02-03 06:56 UTC, chrismclarke commented on functions/src/Utils/data.utils.ts
> + */
We could import a package like lodash that has more advanced equality operators, although as we're only dealing with primative data types that come from the DB I'm hoping my own implementation should cover most of our use cases.

2022-02-03 06:57 UTC, chrismclarke commented on functions/src/aggregations/common.aggregations.ts
> +  private async seed() {
the seed function will trigger anytime the target aggregation field does not exist. This provides us with an initial migration the first time a document is populated, and also a means to re-calculate/alter logic by updating function and then just deleting the database doc (or targeting a different field name)

2022-02-03 19:19 UTC, chrismclarke commented on functions/src/aggregations/common.aggregations.ts
> +    console.warn('change missed', before.data(), after.data())
not sure where/how to pipe these logs... possibly could just throw as error as no further processing will be done anyway

2022-02-03 19:41 UTC, chrismclarke commented on src/stores/databaseV2/clients/dexie.tsx
> +const DB_CACHE_NUMBER = 20220202
I don't think it's strictly required to update the dexie cache number as adding a new table for aggregations isn't a breaking change, but also no harm in doing so

2022-02-05 07:08 UTC, thisislawatts commented on functions/src/Utils/data.utils.ts
>   * length provided by @param chunksize
**question (non-blocking):** What is the value of adding the `.utils.ts` suffix to a file nested within the Utils directory?

2022-02-05 07:41 UTC, thisislawatts commented on functions/src/Utils/data.utils.ts
> + */
Any reason **not** to use lodash here? We're in a backend context so importing a 3rd party lib does not introduce any performance penalties?

2022-02-05 07:44 UTC, thisislawatts commented on functions/src/aggregations/user.aggregations.ts
> +
**question:** Given this is the primary entry point for the functionality can we add test coverage at this point?

2022-02-05 07:47 UTC, thisislawatts commented on functions/src/aggregations/user.aggregations.ts
> +    return handleDBAggregations(change, userAggregations)
**praise:** ✨ This is a great, a simple entry point hooking into the onUpdate method from Firestore.

2022-02-05 07:48 UTC, thisislawatts commented on functions/src/aggregations/common.aggregations.ts
> +export async function handleDBAggregations(
**question:** Given this is the primary entry point for the functionality can we add test coverage at this point?

2022-02-05 08:00 UTC, thisislawatts requested changes

2022-02-05 08:00 UTC, thisislawatts commented on functions/src/aggregations/common.aggregations.ts
> +      this.seed = () => aggregation.handleAggregationSeed(this)
**question(blocking):** Why are we overriding private methods?

It seems like the Abstract class could provide a useful pattern for us here:
https://levelup.gitconnected.com/design-patterns-with-typescript-interfaces-vs-abstract-classes-b6aab6e2ad21

I think that rather than introducing default behaviours we should enforce on the `IAggregation` interface that _handleAggregationUpdate_ and _handleAggregation_ are required behaviours.

This would also simplify the interface as we would no longer need field or aggregrationField as that logic would then be internal to the Aggregation.

Or potentially I am missing some benefit of those being present

2022-02-05 08:04 UTC, thisislawatts commented on functions/src/aggregations/common.aggregations.ts
> +    console.warn('change missed', before.data(), after.data())
Would this ever happen? This seems like firestore would be breaking the documented contract of the event: https://firebase.google.com/docs/reference/functions/providers_firestore.documentbuilder.html#onupdate

2022-02-05 08:27 UTC, thisislawatts commented
Thanks for the videos, very cool to see it all in action! 🎬 

So if I understand correctly the schema is:

```
user_badges: {
  [username]: {
    [badgeType]: boolean
  }
}
```

My understanding of the original ask was for [a list of the verified users](https://github.com/ONEARMY/community-platform/pull/1205). So whilst this aggregation does some of that work it will still require some additional computation on the client. We could instead switch to using flat arrays which would make the data easier to parse.

```
// Example schema:
user_badges: {
  [badgeType]: username[]
}

// Example of data structure
user_badges: {
  verified: ['precious-plastic']
}
```

This would then mean the implementation of [fetchAllVerifiedUsers](https://github.com/ONEARMY/community-platform/pull/1205/files#diff-777873ae5fb42cece21e6af1347582045f2955fd0ae23244773becf8673d3a8dR256-R261
) could be simplified.

Looking through the PR atm we are repeatedly [performing this kind of evaluation](https://github.com/ONEARMY/community-platform/pull/1205/files#diff-5a9f32ae0ff4d8d701d7f20f8a5e42fa0bd99bcb06e79e190b5fc606942d3525R192-R194) like:

```
// Current implementation in PR
verifiedUsers.some(
  user => user.userName === data._createdBy,
)

// Using proposed data structure
verifiedUsers.includes(data._createdBy);
```

2022-02-08 17:53 UTC, chrismclarke commented on functions/src/Utils/data.utils.ts
>   * length provided by @param chunksize
Personal preference - a name like `data.ts` is pretty generic and really easy to confuse when importing or if multiple code tabs open. 

Would probably make sense at some point to decide on naming conventions, e.g. [backstage adr003](https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr003-avoid-default-exports.md)

2022-02-08 18:03 UTC, chrismclarke commented on functions/src/Utils/data.utils.ts
> + */
I'm typically reluctant on using 3rd party libs when all you need is a dozen or so lines of code - there's the ongoing overhead of ensuring the package is pinned at a compatible version, small performance hit whilst running (many of the methods introduce large number of additional checks and polyfills for methods that are now supported in node), as well as a bit of bloat depending on whether you've configured it well for tree-shaking or not. You're right that in the backend this is not so significant, I expect once containerised any of our function code pales in comparison to what is thrown in by firebase

I would say if we have any other use cases for it, it's not a bad library to have (pretty good chance one of our deps will have it installed anyways). I don't have any myself, but happy to add it pre-emptively if you think that's better to do.

2022-02-08 18:14 UTC, chrismclarke commented on functions/src/aggregations/common.aggregations.ts
> +export async function handleDBAggregations(
Do you mean integration to check that the emulators correctly trigger the function on change, or via mock data?

2022-02-08 18:16 UTC, chrismclarke commented on functions/src/aggregations/common.aggregations.ts
> +    console.warn('change missed', before.data(), after.data())
It purely depends on whether the code I've written to detect diffs functions the same as the code firebase has to detect diffs. Deep-diving how firebase works is a horrible experience (done before, pledged never again) so I think makes sense to keep as a means to catch issues.

2022-02-08 18:34 UTC, thisislawatts commented on functions/src/aggregations/common.aggregations.ts
> +export async function handleDBAggregations(
I think invoking this function with mock data probably gives us enough confidence.

Ideally we would treat the entire thing as a black box and update the document and then observe the changes being aggregated. However I think the dependency on the emulator would this too brittle and more expensive.

2022-02-08 18:38 UTC, chrismclarke commented on functions/src/aggregations/common.aggregations.ts
> +      this.seed = () => aggregation.handleAggregationSeed(this)
The methods should be public (at least that's how I understand typescript - things are assumed public unless private specified) - I don't think it is possible to overwrite a private method

The reason for the default is that I anticipate many of our aggregation cases being the same - take a collection, pick a field, summarise for all docs in the collection. I originally wanted to create a couple different types of aggregator (e.g. one that summarises a field, possibly one for multiple fields, one that returns a count of values etc.), but as the scope of this was already getting huge and exact use-cases hard to pin down I decided to leave things fairly basic with room to override.

The howto useful count provides such a unique case because the data is stored in user profiles, not in the howto itself (and unpicking that pattern again goes far beyond the scope of this PR). So we essentially need to aggregate across users, but then refactor the results to collate by howto id instead of the default user id. I didn't want to turn this into a generic method as I'm not sure it's a pattern we really want to be encouraging, so for now it's just a custom implementation on top of core aggregation methods.

As for abstract classes more generally, I really don't like them. For every article you read saying to use them, you will find another saying not to. My main reason for trying to avoid, is that for a new developer coming from javascript/typescript background, the odds of them having used before and understanding are pretty low - and so it adds an extra layer of terminology to get accustomed to. We do use them for the frontend db code as a fairly specific use-case for providing consistent db adaptors across sdks, but even that I'm not super convinced on.

2022-02-08 18:42 UTC, thisislawatts commented on functions/src/aggregations/common.aggregations.ts
> +    console.warn('change missed', before.data(), after.data())
Sorry, let me clarify. If I am following the code flow correctly this method is only invoked via:

```
exports.default = functions.firestore
  .document(`${DB_ENDPOINTS.users}/{id}`)
  .onUpdate(change => {
    return handleDBAggregations(change, userAggregations)   
  });
```

The [documentation](https://firebase.google.com/docs/functions/firestore-events#trigger_a_function_when_a_document_is_updated) around `onUpdate` suggests that a document has changed. So why are also checking that a document change has occurred?

2022-02-08 18:55 UTC, chrismclarke commented on functions/src/aggregations/common.aggregations.ts
> +    console.warn('change missed', before.data(), after.data())
Oh, because the aggregations aren't interested to a document change, but instead a specific field within the document. So whilst onchange will be triggered to any user profile change (e.g. their name), we only want to trigger the voting aggregation when the relevant user doc field changes. Firestore doesn't provide any means of listening to field changes, only doc changes.

Although, all this talk about change has made me realise that really I don't want the onUpdate listener anyway because that doesn't get triggered on create/delete events, so may have to go for onChange instead

https://firebase.google.com/docs/functions/firestore-events

2022-02-08 19:39 UTC, thisislawatts commented on functions/src/aggregations/common.aggregations.ts
> +      this.seed = () => aggregation.handleAggregationSeed(this)
My preference is to avoid early abstractions. At the moment we have two aggregations in place yet we have decided that one of them represents the what should be the  _default_ behaviour, I am not sure that we have enough data to come to that conclusion at the moment.

2022-02-08 19:52 UTC, chrismclarke commented
> So whilst this aggregation does some of that work it will still require some additional computation on the client. We could instead switch to using flat arrays which would make the data easier to parse.
> 
> ```
> // Example schema:
> user_badges: {
>   [badgeType]: username[]
> }
> 
> // Example of data structure
> user_badges: {
>   verified: ['precious-plastic']
> }
> ```

Right now we have 3 open issues related to verified users: #1163, #1197, #1198, all which require some means of checking if one or more users is verified, and various issues related to aggregation in other ways including #1174, #1154. So whilst the flat arrays does definitely make a lot of sense for a list of all users with the verified badge, there are already some others (and likely many more in the future) that will still require some level of processing. So I'm inclined that we start with a system that replicates data in as standard a way as possible (i.e.. `users.user_id.badges` has the same data as `aggregations.user_badges.user_id`) and build out more methods from there (like the custom aggregator used for voted howtos).

2022-02-08 21:09 UTC, thisislawatts commented
I'm not sure I see the advantage of replicating data structures across multiple locations. As any schema change would then need to be made in the following places:

1. The User model
2. The Aggregations
3. Consumers of the Aggregations

My original suggestion around a flat array, was based on an assumption that each aggregation is being used to answer a single question, almost the equivalent of a key value store rather than creating a subset of User data elsewhere. This excerpt around MongoDB's aggregations has better words than me:

> When working with a database management system, any time you want to retrieve data from the database you must execute an operation known as a query. However, queries only return the data that already exists in the database. In order to analyze your data to find patterns or other information about the data — rather than the data itself — you’ll often need to perform another kind of operation known as an aggregation.
> https://www.digitalocean.com/community/tutorials/how-to-use-aggregations-in-mongodb#understanding-aggregation-pipelines

However I don't want to be blocking so many Issues 😅

2022-02-08 21:10 UTC, thisislawatts approved these changes

2022-02-09 21:29 UTC, closed without merging