Feat/admin pending
ONEARMY/community-platform pull request #1533
Opened 2022-03-10 05:54 UTC by chrismclarke

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Latest `master` branch merged

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

2022-03-13 06:29 UTC, thisislawatts commented on src/modules/admin/pages/admin-approvals.tsx
>  import { observer } from 'mobx-react'
**question:** Why are the files in this directory using a different naming convetion?

Elsewhere in the application we use [`PascalCase`](https://www.theserverside.com/definition/Pascal-case) but in this module we are using [`kebab-case`](https://www.theserverside.com/definition/Kebab-case)

I think it would be worth standardising, I also found [a eslint rule](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/filename-case.md) we could introduce to automate checking for this.

What do you think?

2022-03-13 06:51 UTC, thisislawatts requested changes

2022-03-13 06:51 UTC, thisislawatts commented on src/modules/admin/pages/admin-approvals.tsx
> +  }, [])
**question:** Do we need `useCallback` here or could we inline the getApproval method inside of useEffect?

Otherwise, if we do want to keep the code extracted, based on what I read in [this post](https://devtrium.com/posts/async-functions-useeffect#what-if-you-need-to-extract-the-function-outside-useeffect), we should add `[getApprovals]` as a dependency of the useEffect method.

I have no strong opinions here, looking to improve my understanding of best practices around React hooks.

2022-03-14 23:30 UTC, chrismclarke commented on src/modules/admin/pages/admin-approvals.tsx
>  import { observer } from 'mobx-react'
nice catch, likely fallout from whatever other projects I was working on that day...

I expect any lint rule will fail initially and involve a small amount of refactoring (we've never actively decided on one convention or another, just by coincidence/copy-paste-kismet that most files tend to have similar conventions), but no harm running a quick check to see how much work would be involved

2022-03-14 23:40 UTC, chrismclarke commented on src/modules/admin/pages/admin-approvals.tsx
> +  }, [])
could be inlined, although initial dev the function was a lot messier so nicer to have outside. I think it's a reasonable contender for future refactoring so probably makes sense to keep workable.

I struggled myself to get to grips with how to use async functions with hooks, by default I always write class components but felt like worth trying to figure out other ways seeing as it's what seems to be promoted a bit more. 

From what I understand about the dependencies object, the list is mostly used to decide when to potentially trigger/retrigger evaluation. I never want to trigger the re-evaluation (just hook into the mount lifecycle) so they've been purposefully omitted. I think at one point during dev I found the query being duplicated and removing fixed.

The react FAQs discusses this a little bit more here: https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies

Which might make more sense with the context of: https://dmitripavlutin.com/react-useeffect-explanation/

2022-04-25 11:29 UTC, chrismclarke commented on src/modules/admin/pages/admin-approvals.tsx
>  import { observer } from 'mobx-react'
tidied locally and added #1616 generally

2022-09-05 20:07 UTC, thisislawatts approved these changes

2022-09-25 17:46 UTC, merged