feat: add country flag to research username
ONEARMY/community-platform pull request #1572
Opened 2022-03-27 20:21 UTC by jojudre

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Latest `master` branch merged

PR Type

- [ ] New feature (non-breaking change which adds functionality)

## Description

add country flag to research username

## Git Issues

Closes #1406

## Screenshots/Videos

<img width="1435" alt="Снимок экрана 2022-03-27 в 23 20 57" src="https://user-images.githubusercontent.com/42969746/160299344-8fc08324-3f92-43af-b598-2640f8073841.png">

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

2022-03-27 20:23 UTC, jojudre commented
Hi! 
my account don't have a location/country, can't check case when user upload new research, to understand if flag is visible

2022-03-27 20:27 UTC, davehakkens commented
nicee! If you add yourself to the map you get a flag! 
<img width="222" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/160299510-5b8e1caa-d428-4e08-b654-b33b79dd616c.png">

2022-03-27 20:59 UTC, jojudre commented
@davehakkens can't save pin (
<img width="1440" alt="Снимок экрана 2022-03-27 в 23 59 10" src="https://user-images.githubusercontent.com/42969746/160300786-e21e1c5b-c2d1-46b4-a4d5-74ed654b8bc3.png">

2022-03-27 21:27 UTC, davehakkens commented
Did you fill in all fields (including contact details) if not you cant save

On Sun, Mar 27, 2022 at 22:00 Daria Iziukova ***@***.***>
wrote:

> @davehakkens <https://github.com/davehakkens> can't save pin (
> [image: Снимок экрана 2022-03-27 в 23 59 10]
> <https://user-images.githubusercontent.com/42969746/160300786-e21e1c5b-c2d1-46b4-a4d5-74ed654b8bc3.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ONEARMY/community-platform/pull/1572#issuecomment-1080018072>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADIKCILS4AVNXSUEXC2DNNDVCDD5VANCNFSM5RZIKRQA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-27 22:11 UTC, jojudre commented
@davehakkens everything works correctly )

2022-03-28 17:12 UTC, thisislawatts requested changes

2022-03-28 17:12 UTC, thisislawatts commented on src/pages/Research/Content/ResearchItemDetail.tsx
> +    (async () => {
**praise:** Nice spot, thanks for tidying up! ✨

2022-03-28 17:12 UTC, thisislawatts commented on src/stores/Research/research.store.tsx
> +            : '',
**issue(blocking):** There are quite a few different logical flows here somewhat hidden by the shorthand ternary style.

Have you considered extracting this logic out to a help method which could then be put under test? At the moment writing tests for the stores is non trivial due to their dependencies. But if you introduced a new standalone file it should be straight forward enough to test the various scenarios handled by this code.

2022-03-28 18:38 UTC, jojudre commented on src/stores/Research/research.store.tsx
> +            : '',
i took this logic from howTo store

2022-03-28 18:44 UTC, jojudre commented on src/stores/Research/research.store.tsx
> +            : '',
i have a question, what will happen when user adds map pin? every howtos, comment and research which was created by him should be update, do we have this implementation?

2022-03-28 19:10 UTC, thisislawatts commented on src/stores/Research/research.store.tsx
> +            : '',
It looks like there are some mechanisms in place to ensure data is updated, using serverless functions to make updates after the User object has been changed:
https://github.com/ONEARMY/community-platform/blob/master/functions/src/userUpdates/index.ts#L20

2022-03-28 19:11 UTC, thisislawatts commented on src/stores/Research/research.store.tsx
> +            : '',
At the moment it is only making updates to Howto Articles and Howto Comments

2022-03-28 19:14 UTC, thisislawatts commented on src/stores/Research/research.store.tsx
> +            : '',
> i took this logic from howTo store

This sounds like a very good reason to extract it out to a shared function and place it under test. Let me know if I can provide any guidance on adding a new test file. I think this is a helpful example of a lightweight unit test:
https://github.com/ONEARMY/community-platform/blob/master/src/utils/formatters.test.ts

2022-03-30 20:29 UTC, jojudre commented on src/stores/Research/research.store.tsx
> +            : '',
@thisislawatts thanks for helping! ^.^  i will try to make updates for research like in example for howto

2022-04-05 10:05 UTC, closed without merging