1617-add-download-count-howto (early draft)
ONEARMY/community-platform pull request #1687
Opened 2022-05-23 17:12 UTC by AlfonsoGhislieri

PR Checklist

- [ x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ x] - Latest `master` branch merged

PR Type
- [ x] New feature (non-breaking change which adds functionality)

## Description

I have added a total downloads counter feature. When the download file button is clicked this increments the total_downloads property of the howto model and also updates state inside of the FileInfo component in order to re-render the newly incremented value. 

TODO: still need to implement the logic to not allow users to repeatedly click the button and inflate the downloads counter. I am thinking of using local storage with expiry (maybe 12/24 hours as a cooldown). Happy to take suggestions for this.

2022-05-23 19:31 UTC, davehakkens commented
nice one! Local storage with cooldown sounds good to me, but not an expert in the technical side.

>  I was thinking we would update all howto's to have the total_download property if they have an attached file?
That sounds good, we want it retroactive. Looking forward to test.

2022-05-24 12:15 UTC, AlfonsoGhislieri commented
Just pushed the newest commit which has the cooldown implemented, should all be good to go.

2022-05-24 15:28 UTC, AlfonsoGhislieri commented
Will sort out the styling! And sure happy to work on that after this is all finished up 💯

2022-05-28 06:44 UTC, thisislawatts commented on src/components/FileInfo/FileInfo.tsx
> +  // not sure where to store these functions, if here is ok?
✨ A good question. I would prefer to see this behaviour lift out of FileInfo and instead be implemented within the `HowtoDescription` component.

The FileInfo component should be generic and available for reuse in multiple places across the system. Introducing the `howToID` into the props is a signal that it knows to much about the outside world. 

Instead I think we should extend the `FileInfo` component so that it supports an `onClick` function provided via a prop and then we can lift all of our Howto specific logic out to HowtoDescription. What do you think?

2022-05-28 08:33 UTC, thisislawatts requested changes

2022-05-28 08:33 UTC, thisislawatts commented on src/components/FileInfo/FileInfo.tsx
> +  const checkForExpiry = () => {
**suggestion:** Consider refactoring this method so that it does one thing only or renaming it to better communicate the behaviour. At the moment it is checking whether the method is expired **and** then removing expired items. 

There are three possible flows through this function but there is only instance where we explicitly return a value.

2022-05-30 09:56 UTC, AlfonsoGhislieri commented on src/components/FileInfo/FileInfo.tsx
> +  const checkForExpiry = () => {
Will definitely refactor, going to move everything onto `howToDescription`  and refactor in there!

2022-06-02 08:45 UTC, AlfonsoGhislieri commented on src/components/FileInfo/FileInfo.tsx
> +  const checkForExpiry = () => {
@thisislawatts Ok well what started as a minor refactor has turned out into me redoing most of the logic to make sure everything would work as intended and is future proof. Local storage now has an array that stores objects with a download cooldown for specific download cooldowns. 

I pushed everything up like we discussed and out of `fileInfo.` I also created a `utils` file for `howToDescription` to avoid bloating the actual original file too much since I had to create a lot of extra functions for the new implementation.

Let me know what you think!

2022-06-10 11:59 UTC, thisislawatts requested changes

2022-06-10 11:59 UTC, thisislawatts commented on src/stores/Howto/howto.store.tsx
> +        total_downloads: processedFiles ? 0 : undefined,
**question:** Why would we want `total_downloads` to be undefined? We only show this indicator if there are files available to download.

2022-06-10 12:01 UTC, thisislawatts commented
Thanks for the work @AlfonsoGhislieri looking really good! I have added a few comments/suggestions but otherwise I think we're almost there. I have noticed that some of this GitHub actions have been failing without reason recently, will need to dig a little further into those.

2022-06-10 23:07 UTC, AlfonsoGhislieri commented on src/stores/Howto/howto.store.tsx
> +        total_downloads: processedFiles ? 0 : undefined,
Well the anwser to this is pretty simple and silly, when I started working on the issue I was still rather new to using typescript and I think that was just the easiest way to get it to work from the get go. I never revisted it after... 

First solution I could think is to just add to the total_downloads property to the howto model only if a file exists in the model.

https://github.com/ONEARMY/community-platform/pull/1687/commits/fb12a0712b44b23b408bfda5fd19c1a13ded0978#diff-a2437a58b8d602deb7c8d0b921e348a6c2c561c7af93bcaeb0a13833b0e9541eR365

2022-06-10 23:12 UTC, AlfonsoGhislieri commented
@thisislawatts thanks for all the suggestions! Should all be implemented and now the old howto's are fully functional too! 👍

2022-06-11 13:43 UTC, thisislawatts requested changes

2022-06-11 13:43 UTC, thisislawatts commented on src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
> +                  handleClick={this.handleClick}
**issue:** Note that there are another flow here which need to be included when the download is an external resource:

```
{howto.fileLink ? <DownloadExternal link={howto.fileLink} /> : ''}
```

Apologies for missing this in the previous review

2022-06-11 13:43 UTC, thisislawatts commented on src/components/FileInfo/FileInfo.tsx
> +      {allowDownload && meta.downloadUrl && handleClick ? (
**Issue:** This conditional check has become stricter, however `FileInfo` is a generic and reusable component so there are instances which will not pass handleClick. This represents a breaking change for those usecases.

Instead we should consider removing the conditional check change and making the onClick binding stricter, like `onClick={() => handleClick && handleClick()}`, this will only execute an onClick method if one is passed through as a property.

2022-06-11 19:50 UTC, AlfonsoGhislieri commented on src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
> +                  handleClick={this.handleClick}
No worries, will add that in straight away! Didn't realize it had been added already!

2022-06-11 19:53 UTC, AlfonsoGhislieri commented on src/components/FileInfo/FileInfo.tsx
> +      {allowDownload && meta.downloadUrl && handleClick ? (
Makes sense! Often forget to keep components reusable my bad..

2022-06-12 20:42 UTC, thisislawatts approved these changes

2022-06-14 12:12 UTC, merged