Feat/seo clientside tags
ONEARMY/community-platform pull request #1740
Opened 2022-06-08 05:16 UTC by chrismclarke

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

- Add methods to populate SEO tags dynamically from client-side code
- Integrate howto SEO tags (using howto title, description and feature image)
- Integrate top-level route SEO (names of main pages, e.g. map, how-to, research)

TODO
- I'm not sure if we want to use the existing page `name` property to 

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

2022-06-08 05:26 UTC, chrismclarke commented on src/pages/Howto/Content/Howto/Howto.tsx
> +    seoTagsUpdate({
dynamic content (e.g. howtos) can also be updated using data retrieved from the db. Similar code could be used for other modules

2022-06-08 05:27 UTC, chrismclarke commented on src/pages/Howto/Content/Howto/Howto.tsx
> +    seoTagsUpdate({})
I've added this just to ensure any howto metadata is removed when navigating away (although it should actually be overwritten anyways by the general router implementation), so possibly overkill

2022-06-08 05:28 UTC, chrismclarke commented on src/pages/index.tsx
> +                        <SeoTagsUpdateComponent title={page.title} />
The router component handles updating seo for top-level routes (e.g. map, how-to, research, academy)

2022-06-08 06:30 UTC, thisislawatts commented
@chrismclarke you should be able to test out how this would be interpreted by prerender.io using the following curl command

```sh
curl -H "X-Prerender-Token: <YOUR\_PRERENDER\_TOKEN>" https://service.prerender.io/https://www.example.com/
```

2022-06-08 18:40 UTC, chrismclarke commented
More details can also be seen from the pre-render console
https://dashboard.prerender.io/

![image](https://user-images.githubusercontent.com/10515065/172692017-ba380521-e684-4c3b-9445-7ebb1ee0b8c6.png)

2022-06-08 19:46 UTC, davehakkens approved these changes
Looks good to me. Nice work! 🔥🔥🔥

2022-06-08 19:54 UTC, thisislawatts requested changes

2022-06-08 19:54 UTC, thisislawatts commented on src/pages/Howto/Content/Howto/Howto.tsx
> +    seoTagsUpdate({
@chrismclarke can we add a Cypress test to validate the these tags have been populated?

2022-06-08 20:42 UTC, chrismclarke commented
@thisislawatts 
Just added an seo spec for howtos to check metadata populated. I haven't added a general one for the rest of the pages as I don't think the code currently works how we want it to (default hardcoded SEO values are for precious plastic site only, but likely we will want to improve to have different values depending on site/theme). 

We can either decide whether to try include here before merge (alongside any additional seo for things like research, map, etc.), or leave for follow-up. My preference would be to get merged as I think the current improvements help unblock work integrating prerender

2022-06-10 05:11 UTC, thisislawatts approved these changes

2022-06-15 20:48 UTC, merged