feat: improve appearance when shared sociallly and when viewed in search engine result pages
ONEARMY/community-platform pull request #1805
Opened 2022-06-25 10:53 UTC by thisislawatts

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

2022-06-25 19:28 UTC, chrismclarke commented on functions/src/seo-render/index.ts
> +    if (!xPrerender && containsOneOfThem(BOT_AGENTS, requestUserAgent)) {
nit(non-blocking) - this might be tidier if moved to a separate function such as `isBotRequest` or `shouldUsePrerender` or similar

2022-06-25 19:29 UTC, chrismclarke commented on functions/src/seo-render/index.ts
> +        console.log(`Error fetching response from prerender:`, { error })
nin(non-blocking) - might be better to use firebase `logger.error` function so that it gets flagged in the firebase console dashboard and could be actionable in the future

2022-06-25 19:31 UTC, chrismclarke commented on functions/src/seo-render/index.ts
> +        console.log(`Unable to load index.html`, { error })
I'm not sure what could lead to this case, but I'm guessing we should just send some sort of error back instead of a success with undefined content. E.g. `return res.status(404).send()`

2022-06-25 19:32 UTC, chrismclarke commented on functions/src/seo-render/index.ts
> +        console.log(`Error fetching response from prerender:`, { error })
nit(non-blocking) - same as comment below, probably better not to leave undefined response to filter through to the end, I'd suggest either sending an 404 response or possibly trying a redirect to the home page

2022-06-25 19:35 UTC, chrismclarke commented on functions/package.json
> +    "node-fetch": "2",
nit(non-blocking) - We already have axios in the project, is there a good use case for having two libs that do similar things?

2022-06-25 19:46 UTC, chrismclarke commented on functions/package.json
> +    "build": "webpack && cp ../build/index.html ./dist/",
nit(non-blocking) - this makes me feel slightly anxious as it means that deploying functions depends on the latest frontend to be built, but no real checks in place to ensure this has happened. I've used this approach previously myself and come unstuck when manually doing a quick `firebase deploy --only functions` to try and hotfix, or similar scenarios

A better alternative might be to use an additional HTTP request to fetch the live index.html file instead of relying on having the file copied as described in: https://stackoverflow.com/questions/53904044/accessing-firebase-hosting-files-from-firebase-function-triggers. I expect the request to have pretty negligible time as a) the index file is super small and b) likely will be located in the same region/data-centre.

2022-06-25 19:48 UTC, chrismclarke commented on functions/src/seo-render/index.ts
> +const BOT_AGENTS = [
nit(non-blocking) - do we want to maintain our own list? An alternative would be to use an npm package that does it, e.g. https://www.npmjs.com/package/isbot

2022-06-25 19:53 UTC, chrismclarke commented on firebase.json
> +        "source": "/how-to/**",
I had originally thought we would proxy all endpoints via the seoRender, however I can see the benefit of having it specifically for those that we are setup to handle

2022-06-25 20:00 UTC, chrismclarke commented on functions/src/seo-render/index.ts
> +              'X-Prerender-Token': CONFIG.prerender.api_key,
issue(blocking) - If we reach this point but don't have a prerender api key defined I'm guessing this will throw an error trying to access `api_key` on what would be `undefined`. So I think we will need to have a check earlier for `CONFIG.prerender?.api_key`.

2022-06-25 20:05 UTC, chrismclarke requested changes
Thanks Luke, I definitely think this is a really nice addition to have. 

I've added a few non-blocking comments, mostly around how much we want to let errors pass by unnoticed (e.g. catch and continue) vs structuring error response codes. There's also a few implementation details I want to try and sense-check with you (as I have used similar code in my own projects before but am starting to think whether there might be better options available)

I've also flagged one issue I expect may throw errors in production, will be keen to have your feedback. 

As for testing, #1787 contains code that will allow populating things like the prerender API key into the runtime config for use in emulator testing, so once that is merged we should be able to add tests for this if useful

2022-06-25 20:21 UTC, thisislawatts commented on functions/package.json
> +    "build": "webpack && cp ../build/index.html ./dist/",
@chrismclarke, I did take the HTTP approach initially but I think it's preferable to load from the file system. I was referencing the same SO article. It was the final point around performance that persuaded me to avoid the overhead and uncertainties of a network request. 

> If you just want some static files available in Cloud Function without having to make an external request, simply copy those files in to your functions folder and deploy them all along with your code. You will be able to read them locally, you won't need to enable billing to try it, and you won't incur egress and ingress charges. _**It'll also be faster.**_

I share your concerns around the fragility this introduces into the build process. I wonder what options we have to protect ourselves here, whether that's process, automated checks or documentation. WDYT? Is it worth the overhead of a HTTP request affecting each and every user request in normal operations compared to increased risk during non standard scenarios.

2022-06-25 22:00 UTC, chrismclarke commented on functions/package.json
> +    "build": "webpack && cp ../build/index.html ./dist/",
Yeah, it's hard to comment on these things when we don't really know what _faster_ actually means in this context - like I understand why theoretically it will be, but are the amounts of time we're talking about perceptible? I'm guessing answering that would take more effort than is really worth at this point.

I can't really think of any sensible means to prevent updating of functions without updated code, so personally would probably take the potential performance hit over introducing fragility - however I really don't have a strong opinion so happy to leave as is and address if it comes up as an issue in the future. By that time we may even have SSR working properly, in which case it all becomes a non-issue.

2022-06-26 20:53 UTC, thisislawatts commented on functions/package.json
> +    "node-fetch": "2",
not at all, will switch to axios

2022-06-26 20:57 UTC, thisislawatts commented on functions/src/seo-render/index.ts
> +        console.log(`Error fetching response from prerender:`, { error })
Good catch :) Will introduce some logic to catch these edge cases.

2022-06-26 20:57 UTC, thisislawatts commented on functions/src/seo-render/index.ts
> +              'X-Prerender-Token': CONFIG.prerender.api_key,
Good catch! Will introduce a fix for this

2022-06-28 03:51 UTC, chrismclarke approved these changes
Thanks for making the updates, definitely looks cleaner to me and nice to have some tests also. Will be excited to see it in action!

2022-06-28 04:18 UTC, chrismclarke commented on functions/package.json
> +    "build": "webpack && cp ../build/index.html ./dist/",
One other minor issue I just picked up on is that cp doesn't work on windows... not hugely significant unless trying to build and run docker emulators locally on a windows machine

2022-06-28 04:24 UTC, chrismclarke commented
There's a few conflicts from the work I did on SEO sitemaps, I'll go ahead and give a quick tidy to put them both under the same folder structures

2022-07-04 17:32 UTC, merged