fix: how-to list
ONEARMY/community-platform pull request #1959
Opened 2022-09-30 13:57 UTC by asheerrizvi

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2022-09-30 14:00 UTC, asheerrizvi commented on src/pages/Howto/Content/HowtoList/HowtoList.tsx
> +
@thisislawatts @davehakkens this is what I can think of in terms of major changes.

2022-09-30 14:03 UTC, asheerrizvi commented on src/pages/Howto/Content/HowtoList/HowtoList.tsx
> +    // 5. Show buttons below the grid to navigate between pages.
@thisislawatts this is the approach which I can think of.

2022-10-01 10:23 UTC, thisislawatts commented on src/pages/Howto/Content/HowtoList/HowtoList.tsx
> +    // 5. Show buttons below the grid to navigate between pages.
That seems like a good approach @asheerrizvi, thanks for taking the time to write out and share your ideas!

2022-10-01 10:27 UTC, thisislawatts commented on src/pages/Howto/Howto.tsx
> -            path="/how-to"
**issue(blocking):** We should aim to preserve backwards compatibility so that any existing links through to the how-to page continue to work. For example both of the following URLs should display the same content, the first page of the howto listings: 
http://community.platform/how-to
http://community.platform/how-to/1

Does that make sense?

2022-10-01 14:48 UTC, asheerrizvi commented on src/pages/Howto/Howto.tsx
> -            path="/how-to"
yea I aim to do that by checking for `page` inside HowToList if `page` is not present I will redirect to the first page. Does this sound good to you?

2022-10-01 17:36 UTC, thisislawatts commented on src/pages/Howto/Howto.tsx
> -            path="/how-to"
We want to keep serving content from `http://community.platform/how-to` without introducing a redirect.

I would expect the following:
1. http://community.platform/how-to contains the first 36 items and links to page 2 of the listings. 
2. http://community.platform/how-to/2 contains the second 36 items ands link page 3 of the listings.

36 is a magic number here. I don't know how many items we want to have on a page. This is something we may want to experiment with over time so worth making this easy to reconfigure.

2022-10-02 07:24 UTC, asheerrizvi commented on src/pages/Howto/Howto.tsx
> -            path="/how-to"
Got you!

2022-10-30 18:31 UTC, davehakkens commented
How is this one going @asheerrizvi?

2022-11-01 18:41 UTC, asheerrizvi commented
@davehakkens almost done. Wasn't able to pick this one up since a couple weeks. Was able to have a look today, most likely I'll push the code tomorrow.

2022-11-02 06:37 UTC, asheerrizvi commented
@thisislawatts @davehakkens guys can you have a look and see if I have missed something? Thanks :D

2022-11-09 00:54 UTC, chrismclarke requested changes
Thanks for the updates @asheerrizvi!

I can see you've actually taken 2 attempts at this issue, both options interesting in different ways.
I just want to quickly check in with @davehakkens to see which approach they think is better, and then will sort a proper review

2022-11-09 08:02 UTC, asheerrizvi commented
The previous solution was mostly changes to styling. This one removes virutalization altogether. I see some tests are failing and will try fixing them soon.

2022-11-11 06:20 UTC, asheerrizvi commented
Have pushed a fix for the issues up above. This can be reviewed and tested now.

@davehakkens @chrismclarke

2022-11-20 19:41 UTC, davehakkens commented
Nice work on the alignment!
We had a discussion about this PR here internally. But actually not ready yet to change the scroll for pagination. 
It would make the user expereince less good and there would bring a few new bugs to sort out. 
Is it possible to remove the work on the pagination in this PR? (Perhaps release in a seprate PR for later)

Sorry for the changes on this one..

2022-11-21 04:31 UTC, asheerrizvi commented
@davehakkens got it. What about this [commit](https://github.com/ONEARMY/community-platform/pull/1947/commits/f2cfeed0e62d2cc9633fb0ddf434605734ecfac9) where the changes were mostly cosmetic. It fixed the uneven spacing issue while keeping the virtualized grid. Can we do this instead?

2022-11-21 09:53 UTC, davehakkens commented
> @davehakkens got it. What about this [commit](https://github.com/ONEARMY/community-platform/pull/1947/commits/f2cfeed0e62d2cc9633fb0ddf434605734ecfac9) where the changes were mostly cosmetic. It fixed the uneven spacing issue while keeping the virtualized grid. Can we do this instead?

That looks good to merge in!

2022-11-24 22:23 UTC, davehakkens commented
can you actually make a new PR for that @asheerrizvi?

2022-11-25 06:47 UTC, asheerrizvi commented
@davehakkens here you go: https://github.com/ONEARMY/community-platform/pull/2005

2022-11-25 06:47 UTC, closed without merging

2022-11-25 13:41 UTC, thisislawatts commented
@asheerrizvi, my apologies about the time you've spent working on the pagination implementation. I believe that pagination is the right approach but sadly I wasn't able to make the case for it with the other maintainers. Hope you learnt something in the work. I should have got general agreement for the pagination before making my suggestion on your PR.

Thank you again for the time and effort on this ✨