WIP: Add categories to research module
ONEARMY/community-platform pull request #2016
Opened 2022-11-30 07:09 UTC by asheerrizvi

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2022-12-03 15:33 UTC, asheerrizvi commented
Hey @davehakkens @chrismclarke, have a look at this.

Found another issue with I was working on this. The inputs for adding a tag and adding a category are kind of broken. These inputs re-render on each keystroke and thereby makes the input go out of focus on each such action. If I move this input outside the `Modal` component it seems to work properly. I am not sure at the moment what's causing this re-rendering.

Here's a video:

https://user-images.githubusercontent.com/17976252/205448895-a5e3d790-359d-44f2-b127-365ea8402cc9.mov

Can we open a new bug for this?

2022-12-03 18:10 UTC, davehakkens commented
> Can we open a new bug for this?
Well spotted @asheerrizvi, yes feel free to make an issue for that. Thanks :)

And categories works/looks good here. Nice work! 
Only remark I could have is that the categories go away on mobile, ideally they stay.
But I guess this happens because the entire subheader is hidden?
If there is an easy fix for it it would be nice, if not we will make another issue for it in the future.

2022-12-04 10:36 UTC, asheerrizvi commented
@davehakkens have done these changes.

2022-12-04 12:09 UTC, davehakkens commented
perfect!

2022-12-09 16:05 UTC, asheerrizvi commented
@davehakkens anything left on this one? Or can we merge this?

2022-12-09 17:33 UTC, chrismclarke commented
Thanks @asheerrizvi  - Just taking a look now...

2022-12-09 17:55 UTC, chrismclarke requested changes
Many thanks @asheerrizvi , overall looks really good to me!

I've added a few minor comments inline, most just minor nits but a couple I've marked as `blocking` so would be great to get those resolved before merge.

You'll also see some comments about changing dexie table names and the error it will throw running locally (dexie by default blocks db version number downgrade). This can be quickly resolved by clearing site data

![image](https://user-images.githubusercontent.com/10515065/206763457-7a499621-e112-487c-9fdc-b476cea7fd66.png)

2022-12-09 17:55 UTC, chrismclarke commented on src/stores/databaseV2/clients/dexie.tsx
> +const DB_CACHE_NUMBER = 202205020
Thanks for considering to change this

nit(blocking)
Would you be able to change this to keep consistent with yyyy-mm-dd format? E.g. 20220912

As this number is lower than the number you provided you will find when next running locally dexie will throw a version error. To fix you will need to clear your cache (message me if any issues doing this)

2022-12-09 17:55 UTC, chrismclarke commented on src/models/researchCategories.model.ts
> +export interface ISelectedResearchCategories {
nit(non-blocking)
In case of interest an alternative syntax would be 
```
export type ISelectedResearchCategories = Record<string,boolean>
```
You won't see this as much in the platform because dev started before typescript included and habits persist, but fine either way

https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type

2022-12-09 17:55 UTC, chrismclarke commented on src/pages/Howto/Category/CategoriesSelect.tsx
> +    let categories
nit(blocking)   
Could you please specify the type for categories?
Is it an `ICategory[]`?

2022-12-09 17:55 UTC, chrismclarke commented on src/pages/Howto/Content/Common/Howto.form.tsx
> +                              <Flex sx={{ flexDirection: 'column' }} mb={3}>
nice catch! I forget what we leave as beta-tester only features vs generally available. Could be worth a quick audit at some point in the future, but definitely beyond scope of this PR

2022-12-09 17:55 UTC, chrismclarke commented on src/pages/Howto/Content/HowtoList/HowtoList.tsx
> +              type="how-to-categories"
nit(non-blocking)   
Probably we can drop `-categories` from the type name as implied by the component name `CategoriesSelect`

Then just for consistency probably better to use `howto` instead of `how-to` (although not sure how consistent we are on this through the platform)

2022-12-09 17:55 UTC, chrismclarke commented on src/pages/Research/Content/ResearchList.tsx
> +const updateQueryParams = (
I tested the functionality and works well for me!

2022-12-09 17:55 UTC, chrismclarke commented on shared/models/db.ts
> +  researchCategories: `${DB_PREFIX}v3_research_categories`,
nit(blocking)   
I think we're slowly trying to move away from the `v3_` syntax (as the v3 part doesn't really tell us much and makes the db more messy if wanting to just move one table to v4)

Instead could you change it to `research_categories_rev20221209`?

As mentioned in another comment, this will throw a dexie error running locally for the first time (as schema changed without migration), but fixed by clearing site data in developer tools -> application -> storage

2022-12-24 07:52 UTC, asheerrizvi commented
@chrismclarke thanks for the review 🙌 . Have done these changes.

2022-12-28 03:52 UTC, chrismclarke approved these changes
Thanks for making all the changes @asheerrizvi!
Looks great to me, nice feature to add in for sure

2022-12-28 03:58 UTC, merged