feat(settings): add email frequency setting
ONEARMY/community-platform pull request #2039
Opened 2022-12-16 19:10 UTC by evakill

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

This PR adds a new section, Email notifications, to the user settings page. This section has a dropdown with options `never`, `daily`, `weekly`, `monthly` that sets the `user.notification_settings.emailFrequency` field.

## Git Issues

Closes #2028 

## Screenshots/Videos
demo:
- dropdown selection with four selectable options
- setting persists on save
- dropdown defaults to saved setting on load
- setting does not persist if not saved

https://user-images.githubusercontent.com/37253846/208171087-86239db9-c76e-49ab-aec4-92610b0baef1.mov

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2022-12-16 21:52 UTC, chrismclarke commented on src/models/user.models.tsx
> +  NEVER = 'never',
nit(blocking)
Could we change `Never` to an empty string? That way it can be picked up in the same way as users who have never set a preference when checking in the backend whether we need to compile a list of notifications for the user

2022-12-16 21:56 UTC, chrismclarke commented on src/pages/Settings/content/formSections/EmailNotifications.section.tsx
> +                        this.props.notificationSettings?.emailFrequency ??
thanks for adding the check for users without any settings (still don't have an nice way to migrate all user profiles when we add new fields). 

nit(blocking)
I like the idea that this will get users without notifications enabled to automatically opt in next time they save their profile, although I think probably to keep things a bit clearer it would be better to make the default value never and we can organise a migration in the future to set another default value to all users if required.

2022-12-16 21:58 UTC, chrismclarke requested changes
Looks pretty good to me! A few minor nit-picks to resolve but then I'd say good to go

2022-12-16 22:14 UTC, davehakkens commented
looks nice @evakill!

2022-12-16 22:14 UTC, davehakkens approved these changes

2022-12-17 05:52 UTC, evakill commented
thanks for the reviews! applied your comments @chrismclarke

2022-12-19 20:08 UTC, chrismclarke commented
Thanks @evakill , all looks great to me

One last quick thought @davehakkens  - do we want this to be viewable by everyone or just beta-testers/admins to begin with? The dropdown doesn't do anything on its own at the moment and will probably be some time next month we get the email send integration in

2022-12-19 20:08 UTC, chrismclarke approved these changes

2022-12-20 11:44 UTC, davehakkens commented
Good point @chrismclarke, might be better to start with only visable for with _beta-testers_ and _admins_ if we think it will take a bit more time. Than we can just merge it in now. You know how to add this auth wrapper @evakill?

2022-12-20 15:13 UTC, evakill commented
@davehakkens i can give it a go later this week!

2022-12-21 04:32 UTC, chrismclarke commented
Just a one-liner so I've added in c6d77b3 . 
I don't think there's actually a way to limit anything to multiple roles (e.g. both beta-testers and admins), so have just set to beta-testers for now and any admins that want to test can assign themselves the role (users can have multiple).

Nice to get this one in, will be away from tomorrow so likely will have to wait until the new year to handle the backend work for sending the emails

2022-12-21 04:45 UTC, merged