fix: adds accessibile labels to moderation buttons
ONEARMY/community-platform pull request #2065
Opened 2023-01-08 13:18 UTC by thisislawatts

Use new `showIconOnly` property and use margin-left
for consistent layout.

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-01-13 05:09 UTC, chrismclarke approved these changes
One minor comment from me but otherwise happy with the code. I'll leave it to @davehakkens if there's any related design issues

2023-01-13 05:09 UTC, chrismclarke commented on .circleci/config.yml
> +            npm ls
nit(non-blocking)
Do we still need this line?

2023-01-13 20:45 UTC, davehakkens approved these changes

2023-01-21 03:12 UTC, chrismclarke requested changes
@thisislawatts 
I tried to manually remove the additional `npm-ls` call however when running locally it seems like the commitlint config is not working
```
PS C:\apps\oneArmy\community-platform> git commit -m "chore: remove ci npm ls"
⧗   input: chore: remove ci npm ls
✖   Please add rules to your `commitlint.config.js`
    - Getting started guide: https://git.io/fhHij
    - Example config: https://git.io/fhHip [empty-rules]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

Would you be able to either try fixing (I'm guessing something to do with the version installed or difference with commitlint vs @commitlint/cli), or moving the config changes into a separate PR so that we can still merge the labels update?

2023-01-21 03:45 UTC, chrismclarke commented
On second thoughts I could probably try be a bit more useful (!)
I've moved the commitlint changes to #2070 and will merge the button changes here once tests pass

2023-01-21 04:11 UTC, closed without merging