chore: update node 16 to node 18
ONEARMY/community-platform pull request #2067
Opened 2023-01-13 20:53 UTC by chrismclarke

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## TODO

- [x] Update documentation
- [x] Fix frontend build/run
- [ ] Fix functions build
- [ ] Test emulators build
- [ ] Test CI

## Git Issues

Closes #2057

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-01-17 12:24 UTC, davehakkens approved these changes
Thanks for all the work on this Chris.
Updated Node to 18, did a `yarn start` and it all works.
Very smooth, seems good here!

2023-01-17 23:24 UTC, evakill requested changes
wasn't getting the print statements on `yarn start` - found a console.log that needed to be pulled out of the if/else in the `envCheck`

otherwise, LGTM and runs smoothly when using  node 18 🎉

2023-01-17 23:24 UTC, evakill commented on scripts/envCheck.js
> +  }
```suggestion
  for (const test of tests) {
    let icon = '✅'
    let message = test.message
    const passed = test.exec()
    if (!passed) {
      if (test.severity === 'failure') {
        icon = '❌'
        failures = failures + 1
      } else {
        icon = '⚠️'
        message = '(Recommended) ' + message
      }
    }
    console.log(icon, '', message)
  }
```

2023-01-21 02:30 UTC, chrismclarke commented on scripts/envCheck.js
> +  }
Thanks @evakill - whoops, yeah I think I tried to change it because it felt tedious always seeing the pass messages, but then I'm missing the failure ones so thanks for catching that

2023-01-21 02:34 UTC, chrismclarke commented
Think this one is (finally) good to go.

@davehakkens I'll give a double-check to the deployed dev sites post-merge, but if you could give me a heads up when you are planning to make the next release and I wouldn't mind also quickly checking the production sites at the same time (around most this weekend or Monday on my usual timezone).

2023-01-21 02:51 UTC, merged

2023-01-21 08:51 UTC, davehakkens commented
they al seems to work well @chrismclarke.

Feel free the push the release at your convience, so you can double check.
I dont have any specific time for it that it needs to go out. 
Now/this weekend seems like a good moment.

2023-01-29 14:58 UTC, thisislawatts commented
@chrismclarke are the deployed instances all upgraded to Node 18 now as well? If so can we remove the node 16 build job from the CircleCI workflow?

2023-01-29 19:36 UTC, chrismclarke commented
They should all be, I had kept in when planning to keep the node 18 usage optional but now its enforce fine to get rid. 
I'm guessing we might also want to pin to a specific version of node 18 instead of just `current` (?)