feat: improvements to mark as useful button
ONEARMY/community-platform pull request #2087
Opened 2023-02-03 07:42 UTC by asheerrizvi

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Improvements to mark as useful button

## Git Issues

Closes #2080 

## Screenshots/Videos

<img width="190" alt="image" src="https://user-images.githubusercontent.com/17976252/216541000-622d8812-3b0e-4c9c-bbcb-0ce7080ced66.png">

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-02-03 20:34 UTC, davehakkens commented
Niceee, works smooth.
Any specific reason to not use the syling as mentioned in the original issue?

2023-02-04 05:07 UTC, asheerrizvi commented
@davehakkens I wasn't able to inspect them using the Figma link for some reason. I will try again.

2023-02-04 06:51 UTC, asheerrizvi commented
@davehakkens styling should be better now.

2023-02-04 11:06 UTC, asheerrizvi commented
@davehakkens done.

2023-02-10 20:08 UTC, davehakkens commented
Would you be interested to review this one @evakill?

2023-02-22 20:19 UTC, evakill requested changes

2023-02-22 20:19 UTC, evakill commented on packages/components/src/Button/Button.tsx
> -            top: 0,
changing this Button component has a lot of downstream effects. it's used a ton of places in the app. from clicking around a bit, i noticed places where the styling is now different:
<img width="874" alt="Screen Shot 2023-02-22 at 2 15 01 PM" src="https://user-images.githubusercontent.com/37253846/220749146-50151e4a-cdb6-44ba-9ea2-05fc73ff17e7.png">
<img width="889" alt="Screen Shot 2023-02-22 at 2 14 56 PM" src="https://user-images.githubusercontent.com/37253846/220749150-43dd9d85-d4db-44de-9a74-03f58dadbf32.png">
<img width="926" alt="Screen Shot 2023-02-22 at 2 14 47 PM" src="https://user-images.githubusercontent.com/37253846/220749154-df294e6c-f9d4-4ea2-ace4-26283e7537ea.png">
<img width="828" alt="Screen Shot 2023-02-22 at 2 14 37 PM" src="https://user-images.githubusercontent.com/37253846/220749157-40cee5ee-e08d-4e77-8899-54408e2d2568.png">
<img width="382" alt="Screen Shot 2023-02-22 at 2 08 00 PM" src="https://user-images.githubusercontent.com/37253846/220749163-f41db088-b6da-4587-9553-86facd55c184.png">
<img width="424" alt="Screen Shot 2023-02-22 at 2 07 57 PM" src="https://user-images.githubusercontent.com/37253846/220749165-1e555395-c0c6-4de5-b6d6-1086fa475ae6.png">

i think we should avoid changing this file unless we are wanting to modify the component globally. do you think you can refactor the styling changes to happen in `UsefulStatsButton` instead?

2023-02-26 14:32 UTC, asheerrizvi commented on packages/components/src/Button/Button.tsx
> -            top: 0,
Sure, have reverted changes to the Button component. Although, I believe we can do better in terms of CSS, it would be cool if we can revisit it later and make the necessary improvements.

2023-02-26 15:32 UTC, davehakkens commented
@evakill changes are added, looks good here.
Let me know if you have any other remarks. Otherwise we can merge :)

2023-02-27 23:50 UTC, evakill approved these changes
ok this looks fine, not sure why some tests are now failing. @chrismclarke any ideas?

2023-02-28 10:28 UTC, davehakkens commented
The chrome tests can be a bit buggy. I re-run the check and now they passed.
PR Preview not sure what is going on. But I guess we dont need that to merge

2023-02-28 10:28 UTC, merged