feat: follow research articles for updates #1438
ONEARMY/community-platform pull request #2145
Opened 2023-03-07 17:27 UTC by thisislawatts

- feat(components): add support for research_update notification
- feat: follow research article

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-03-11 18:05 UTC, davehakkens commented
> Sanity check, a user probably doesn't want to subscribe to **any** updates to an article. What constitutes a meaningful change?

I would say:
Subscribe to: any new update (step) posted.
Not subscribe to: any new comment made

2023-03-26 17:37 UTC, davehakkens commented
Nice one. Seems promosing!
But I dont see any follow button?
<img width="1276" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/227793746-fe59f768-6cfe-49f8-a191-1bac842f9292.png">

2023-03-26 19:46 UTC, thisislawatts commented
Ah weird, I am seeing it locally but not in the preview 🤔 let me take a look…

2023-03-28 07:01 UTC, davehakkens commented
Did some local testing.
1. Button to toggle works, but when following I dont receive a notification if an update is posted.
2. Can we make the icon `orange` (like notifications) when its active. To make the different state is more visable

2023-03-28 16:21 UTC, thisislawatts commented
> 1. Button to toggle works, but when following I dont receive a notification if an update is posted.
Will take another look into this 👀 
> 2. Can we make the icon `orange` (like notifications) when its active. To make the different state is more visable
Sure thing!

2023-03-29 16:29 UTC, thisislawatts commented
After some further investigation @davehakkens can we focus on merging the changes which introduce the core functionality and iterate on the Following Button in a separate PR? 

This Following Button will only be available for `beta-tester` users. 

I am wondering whether we should align with the Useful button and show how many people are Following a Research project.

2023-03-29 21:41 UTC, davehakkens commented
Works now. Nice. Yeh i'd buy up for releasing and iterating as we go.

2023-03-30 17:34 UTC, thisislawatts commented
Okay great, thanks @davehakkens. With the button being worked on separately, @ONEARMY/maintainers can I get a review for the functional changes here?

2023-03-31 09:46 UTC, AlfonsoGhislieri commented
I'll get this reviewed today!

2023-04-01 12:23 UTC, AlfonsoGhislieri requested changes

2023-04-01 12:23 UTC, AlfonsoGhislieri commented on src/stores/Research/research.store.test.ts
> +
**Nitpick** Could you add `// Assert `for better readability

2023-04-01 12:23 UTC, AlfonsoGhislieri commented on src/stores/Research/research.store.test.ts
> +
Same as above

2023-04-01 12:23 UTC, AlfonsoGhislieri commented on src/stores/Research/research.store.test.ts
> +
Also same as above

2023-04-01 12:23 UTC, AlfonsoGhislieri commented on src/stores/Research/research.store.tsx
> +      })
**Question - curious** Is this line to update the `activeReseachItem` that is observable to other components?

2023-04-01 12:23 UTC, AlfonsoGhislieri commented on src/stores/Research/research.store.tsx
> +    })
**Question** Was this kept in for future potential debugging?

2023-04-01 12:27 UTC, AlfonsoGhislieri commented
All done @thisislawatts! Just a few questions and small nitpicky changes, but the main issue that I found was not handling a user that is not logged in, this is obviously not an issue right now since this is only available to `beta-testers` who have to be logged in. So not sure if this should be addressed at this time!

2023-04-01 12:30 UTC, thisislawatts commented on src/models/research.models.tsx
> +type UserIdList = string[]
You're right that we don't get much additional value from this type. The intention here is to clearly communicate the type of strings which will be contained within this list. Happy to remove if you think this additional type does not make the code easier to understand.

2023-04-01 12:34 UTC, thisislawatts commented on packages/components/src/NotificationItem/NotificationItem.tsx
> +    ? 'thunderbolt'
Added here https://github.com/ONEARMY/community-platform/pull/2145/commits/e88cbbb9df474b4514c5ec4ca59c71c90bce7e07

2023-04-01 12:35 UTC, thisislawatts commented on src/pages/Research/Content/ResearchDescription.tsx
> +            </Button>
Agreed, I think this entire chunk needs to be refactored, at the moment it is wrapped in `AuthWrapper` which requires a logged in user. 

I suggest that this work should be done as part of #2191

2023-04-01 12:41 UTC, thisislawatts commented on src/stores/Research/research.store.tsx
> +      })
Thats the intention here, I copied this pattern from elsewhere in the store. However thinking about it I think each of these should be replaced with a call to `setActiveResearchItem` so reduce duplicated mechanisms for update the activeResearchItem. 🤔 

Maybe a good item for a follow up refactoring PR

2023-04-01 12:47 UTC, thisislawatts commented on src/stores/Research/research.store.tsx
> +    })
That was the intention.

2023-04-01 12:48 UTC, AlfonsoGhislieri commented on src/pages/Research/Content/ResearchDescription.tsx
> +            </Button>
Ah yeah that's definitely getting quite cluttered, thanks for raising the issue :-)

2023-04-01 12:51 UTC, AlfonsoGhislieri commented on src/stores/Research/research.store.tsx
> +      })
Yeah I kept seeing across the store, could be worth looking into like you said for some refactoring!

2023-04-01 12:51 UTC, thisislawatts commented
My preference @AlfonsoGhislieri would be to see the Follow/Folllowing button handled separately for a few reasons:
* This PR is already quite old and touches a bunch of files other people may be working on, the sooner these changes are available on the default branch the less likely we are to encounter merge conflicts. 
* The opt in/out button is not coupled to the backend logic so does not need to go out in the same PR. The use of `beta-tester` here helps protect users from seeing work in progress.
* There needs to be some design iterations to the Follow/Following button which should not block the functional change we are making here.

2023-04-01 12:55 UTC, AlfonsoGhislieri commented
Yeah that makes complete sense to me @thisislawatts! Didn't see that you had raised that PR already. Great work! 👍🏻

2023-04-01 12:55 UTC, AlfonsoGhislieri approved these changes

2023-04-01 14:04 UTC, davehakkens approved these changes

2023-04-01 14:04 UTC, merged