feat: introduce pkg for themes
ONEARMY/community-platform pull request #2155
Opened 2023-03-22 20:58 UTC by thisislawatts

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-03-24 16:21 UTC, davehakkens commented
> Next up 🦉 Dark Mode(TM) that no one is asking for. 
😅

2023-03-25 20:45 UTC, chrismclarke requested changes
See a couple of comments in-line.

Also as this has potential for accidentally breaking theme/style imports I'll suggest @davehakkens  takes a visual check just to make sure colours, logos etc. appear as expected

2023-03-25 20:45 UTC, chrismclarke commented on packages/themes/dist/common/button.d.ts
question(blocking)
Do we want to be including the dist folder? 

I assume the answer is probably no, and in which case we need to add to the scripting to ensure it's both recompiled when developing locally and compiled as part of build processes

2023-03-25 20:45 UTC, chrismclarke commented on packages/themes/tsconfig.json
nit(non-blocking)
I'm not sure if we really need the full boilerplate - most editors have intellisense for the properties anyway.

2023-03-26 14:06 UTC, thisislawatts commented on packages/themes/dist/common/button.d.ts
Good catch @chrismclarke, I've updated to ignore `dist` and reworked each of the workflows to build themes.

2023-03-26 15:01 UTC, davehakkens approved these changes
Looks good to me! (only tried PP thought, will test again when deployed to dev sites)

2023-03-26 20:02 UTC, thisislawatts commented
@chrismclarke do you think this should be marked as a breaking change, aka a v2? Originally I was only thinking about this as refactoring but maybe its more meaningful than that.

2023-03-27 11:12 UTC, chrismclarke commented on package.json
> +    "start": "concurrently --kill-others --names themes,components,platform --prefix-colors cyan,blue,magenta \"yarn start:themes\" \"yarn start:components\" \"yarn start:platform\"",
Thanks for updating all of these, appreciate it's a bit of a pain maintaining the long list (on my deep backlog to revisit nx/other options)

2023-03-27 11:48 UTC, chrismclarke approved these changes
Thanks for the updates @thisislawatts , confirm running locally behaves as expected (can make changes to theme and see live reloaded). 

I can see there's a few additional minor tweaks to CI scripts so I'd say good to go once passing

2023-03-27 11:49 UTC, chrismclarke approved these changes

2023-03-27 11:49 UTC, merged