chore: refactor no-useless-catch
ONEARMY/community-platform pull request #2161
Opened 2023-03-25 14:41 UTC by thisislawatts

> A catch clause that only rethrows the original error is redundant, and has no effect on the runtime behavior of the program. These redundant clauses can be a source of confusion and code bloat, so it’s better to disallow these unnecessary catch clauses.
https://eslint.org/docs/latest/rules/no-useless-catch

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-03-25 21:10 UTC, chrismclarke requested changes
One minor question but otherwise looks good to me

2023-03-25 21:10 UTC, chrismclarke commented on src/stores/User/user.store.ts
> +import { logger } from '../../logger'
question(blocking)
I've seen on most PRs you've been changing some src imports to relative (but not all).
I'm wondering if this is something your editor is doing or an active choice, and if so why make the logger reative but not the models or utils below? Right now this feels a little inconsistent (it was before, but the added changes don't resolve)... might just be a lack of understanding on my part

2023-03-25 21:15 UTC, chrismclarke approved these changes

2023-03-25 21:15 UTC, chrismclarke commented on src/stores/User/user.store.ts
> +import { logger } from '../../logger'
Otherwise happy with the change, so actually I think this can be non-blocking but would be good to know for future ref

2023-03-25 21:16 UTC, merged

2023-03-26 15:01 UTC, thisislawatts commented on src/stores/User/user.store.ts
> +import { logger } from '../../logger'
A good question, I am intermittently seeing failures owing to `/src/paths` not being resolveable during the build process. It suspect it happening when the require chain is changed due to order of imports across the project. You're right though that it is really inconsistent across the project.
* 609 instances of `from 'src'`
* 359 instances of `from '..?/` (although that pattern is a little greedy)

It would be great to standardise here, ideally with some tooling to help out.

2023-03-27 11:22 UTC, chrismclarke commented on src/stores/User/user.store.ts
> +import { logger } from '../../logger'
Yeah path resolution is a total pain, particularly as you have somewhat competing systems trying to manage - cra/webpack has it's own support where it basically just replaces the references at build time via it's own config, and then typescript which uses tsconfig files to resolve as it compiles.

I think my personal preference would be to get all workspaces working with absolute paths. The thing I don't like about relative paths is when they get too nested and you need to make folder structure changes (I've seen vscode make really janky replacements, turning local `../folder/file` to `../../../root/project/folder/file`. You also can get issues if people try to import files from outside the workspace (which may/may not fail depending on compiler), although I think that one is more easily solved with lint rules (think there's some module boundary one that we may already have(?)). 

Thanks for the stats though, nice to know that we are consistently inconsistent enough that probably not worth dealing with for now 😅