feat: add consistent alert modal #2154
ONEARMY/community-platform pull request #2178
Opened 2023-03-28 00:47 UTC by iSCJT

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

1. Adds common confirm modal component
2. Replaces comment deletion window.confirm in how to and research pages with new confirm modal
3. Replaces contact link delete confirmation on settings page with new confirm modal
4. Adds / updates cypress tests for pages (tests are to the same level of the pre-existing ones but need improving, added a todo for myself)

## Git Issues

Closes #2154 

## Screenshots/Videos

![image](https://user-images.githubusercontent.com/80723794/228098018-abb8173f-4d53-4686-8cf6-8a805fce3cec.png)

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-03-28 10:04 UTC, AlfonsoGhislieri requested changes

2023-03-28 10:04 UTC, AlfonsoGhislieri commented on packages/cypress/src/integration/howto/comments.spec.ts
> +})
**praise**: Good idea to get the comments into a separate spec file

2023-03-28 10:04 UTC, AlfonsoGhislieri commented on packages/cypress/src/integration/howto/read.spec.ts
> +    // })
You delete these lines, I agree with your changes to move the comment tests to a separate spec file. It's in line with how the research comment testing is handled.

2023-03-28 10:10 UTC, AlfonsoGhislieri commented
Thanks a lot @iSCJT, looks really good to me, great addition to have a new component! 🤩

2023-03-28 10:16 UTC, iSCJT commented on packages/components/src/ConfirmModal/ConfirmModal.tsx
> +export const ConfirmModal: React.FC<{
I'll refactor, I wouldn't normally use but I checked how another component was implemented and went for consistency.  I'll add myself a chore to refactor the others as well.

2023-03-28 10:17 UTC, iSCJT commented on packages/cypress/src/integration/howto/comments.spec.ts
> +        // TODO: check db to make sure comment deleted
Link doesn't work but i'll find it in the codebase.  Thanks for highlighting!  I'll clear the TODO's

2023-03-28 10:57 UTC, AlfonsoGhislieri commented on packages/components/src/ConfirmModal/ConfirmModal.tsx
> +export const ConfirmModal: React.FC<{
Yeah I do think there is a little inconsistency from back when it still was reccomended

2023-03-28 10:57 UTC, AlfonsoGhislieri commented on packages/cypress/src/integration/howto/comments.spec.ts
> +        // TODO: check db to make sure comment deleted
Sorry, this is the one [here](https://github.com/ONEARMY/community-platform/blob/6947c477525c6b4d7ea3c222e144134ecc4d99f7/src/stores/Howto/howto.store.test.ts)

2023-03-28 16:33 UTC, thisislawatts commented on packages/components/src/ConfirmModal/ConfirmModal.tsx
> +export const ConfirmModal: React.FC<{
>  I'll add myself a chore to refactor the others as well.
Perhaps useful to raise this is as a GitHub Issue, open it up for anyone looking to make contributions to the project?

2023-03-28 20:04 UTC, iSCJT commented on packages/cypress/src/integration/howto/comments.spec.ts
> +        // TODO: check db to make sure comment deleted
thanks @AlfonsoGhislieri

2023-03-28 20:40 UTC, iSCJT commented on packages/components/src/ConfirmModal/ConfirmModal.tsx
> +export const ConfirmModal: React.FC<{
@thisislawatts good idea, I've added #2182

2023-03-28 21:17 UTC, AlfonsoGhislieri approved these changes

2023-03-30 19:17 UTC, davehakkens commented
The branch seems to have some conflicts? Can't merge yet :|
```
 src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
src/pages/Research/Content/ResearchComments/ResearchComments.tsx 
```

2023-03-30 21:01 UTC, davehakkens approved these changes

2023-03-30 21:01 UTC, merged