feat(Howto.form): added current character count indicator
ONEARMY/community-platform pull request #2184
Opened 2023-03-29 08:59 UTC by cerkiewny

In order to easier see what the limit of characters in the howto creation for the title is, show current and maximum number of characters next to the text area widget.

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Introduced the better character length indicator on the title input ui for event

## Git Issues

Closes #2015 

## Screenshots/Videos

https://user-images.githubusercontent.com/4504330/228482191-3b00edd0-66c8-4c90-9dd0-09c8d91cee0a.mp4

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-03-29 11:57 UTC, davehakkens commented
Looks nice, cool color detail.
Might be good to align/intergrate this with other areas in the platform
We already have a similair function in the comments input.
<img width="993" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/228527803-36a81974-fba9-43ca-a713-9f448323c15b.png">

And could use it also in the research module
<img width="848" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/228527921-00bf7bb0-a02b-4980-b732-9f9c4e2f8497.png">

2023-03-29 15:53 UTC, thisislawatts commented
Thanks for taking a look at this @cerkiewny, I think it would be worth adding this counter into: https://github.com/ONEARMY/community-platform/blob/master/packages/components/src/FieldInput/FieldInput.tsx

Consider:
* Making this counter conditional so it is only included if there is a `maxLength` attribute passed through. 
* Using [standard fontsizes](https://github.com/ONEARMY/community-platform/blob/0b3a0119f5ada4dc55c29679e85ef3319a7d51fb/packages/themes/src/project-kamp/styles.ts#L4) from the theme declaration rather the hardcoding pixel values.

2023-03-29 15:59 UTC, cerkiewny commented
On related note do you have the theme or some design system from which I could use the colors (like instead of green orange red success/warning/danger colors)? I will change it later today. And can move it to FieldInput as you suggested.

2023-03-29 16:09 UTC, iSCJT commented
> 

There's a bit about the theming [here](https://onearmy.github.io/community-platform/Frontend%20Development/overview)

Although I think it needs an update and the themes directory was moved to [here](https://github.com/ONEARMY/community-platform/tree/b2c823a37210dd741acadd9b6c9c557e7990138a/packages/themes) a few days ago.

2023-04-06 12:08 UTC, AlfonsoGhislieri commented on src/pages/Howto/Content/Common/Howto.form.tsx
> +}
Like suggested by @thisislawatts try and use theme for both color and fontsizes. Eg: `theme.fontSizes[2]` or `theme.color.red`

2023-04-07 12:10 UTC, davehakkens commented on src/pages/Howto/Content/Common/Howto.form.tsx
> +  let color = 'black'
Yes would be great to apply to other areas as well!

2023-04-08 10:33 UTC, AlfonsoGhislieri commented on src/pages/Howto/Content/Common/Howto.form.tsx
> +  let color = 'black'
Then we should definitely look into extracting this functionality from just this component and making it reusable @cerkiewny

2023-04-14 14:12 UTC, AlfonsoGhislieri requested changes
Thanks @cerkiewny for making some of the suggested changes, sorry for the confusion around the use of themeing earlier. Would be great if we can make the component theme aware.

Some other things which would be great if you could change as suggested by @davehakkens earlier in the conversation:
- The counter currently is on the bottom left of the field, would be better to have it on the bottom right for consistency.
- Could you also add it to the research form?

Let me know if you have any questions or need any help!

2023-04-14 14:12 UTC, AlfonsoGhislieri commented on packages/components/src/FieldInput/FieldInput.tsx
> +  }
**Issue**: Same here, once again my bad if I didn't make it clear and confused you leading you use theme rather than making the component theme aware.

But here we should pass `color` as a prop for `sx` so that it has access to the themeing. So we can stop using theme, eg: `theme.colors.red` --> `'red'`. This could also be refactored so we don't need to use all these if statements, you can define an object that maps percentage thresholds and check the `percMax` against the keys:

```
const colorMap = {
  0.6: 'yellow.base',
  0.75: 'red2',
  0.99: 'red',
}
```

2023-04-14 14:12 UTC, AlfonsoGhislieri commented on src/pages/Howto/Content/Common/Howto.form.tsx
>                                </Flex>
**Potential issue**: Don't we need `showCharacterCount` to pass a boolean here? Is it not just passing a Falsey value right now?

2023-04-14 14:12 UTC, AlfonsoGhislieri commented on packages/components/src/FieldInput/FieldInput.tsx
>    customOnBlur?: (event: any) => void
**Question**: Is it really necessary to also create this `showCharacterCount` prop? Is passing `maxLength` not enough to decide when the counter should be conditionally rendered?

2023-04-14 15:18 UTC, cerkiewny commented on packages/components/src/FieldInput/FieldInput.tsx
>  type FieldProps = FieldRenderProps<any, any> & { children?: React.ReactNode }
Ok, will adjust this.

2023-04-14 15:18 UTC, cerkiewny commented on packages/components/src/FieldInput/FieldInput.tsx
> +      {curSize} / {maxSize}
Sure, my bad missed it :)

2023-04-14 15:19 UTC, cerkiewny commented on packages/components/src/FieldInput/FieldInput.tsx
> +  }
No problem at all. I will change it.

2023-04-14 15:19 UTC, cerkiewny commented on src/pages/Howto/Content/Common/Howto.form.tsx
>                                </Flex>
I was thinking about it but decided that adding extra property will make it backwards compatible. If you think it is enough I can also base it on maxLength being provided.

2023-04-14 15:20 UTC, cerkiewny commented on packages/components/src/FieldInput/FieldInput.tsx
>    customOnBlur?: (event: any) => void
I was thinking about it but decided that adding extra property will make it backwards compatible. If you think it is enough I can also base it on maxLength being provided.

2023-04-14 15:37 UTC, AlfonsoGhislieri commented on src/pages/Howto/Content/Common/Howto.form.tsx
>                                </Flex>
For some reason I was convinced that with the shorthand it would default to undefined since it's an optional parameter!

2023-04-14 15:44 UTC, AlfonsoGhislieri commented on packages/components/src/FieldInput/FieldInput.tsx
>    customOnBlur?: (event: any) => void
That makes sense, I'd say keep it just to be safe. Also probably a good extra guard to avoid this rendering where we don't explicitly want it!

2023-04-14 19:11 UTC, cerkiewny commented
https://user-images.githubusercontent.com/4504330/232135441-28fee4d0-6407-44e5-8876-6c828de8042a.mp4

2023-04-16 10:09 UTC, AlfonsoGhislieri requested changes
Thanks for all the changes @cerkiewny looks like we are nearly there! Could you also add this to the [Research.form](https://github.com/ONEARMY/community-platform/blob/master/src/pages/Research/Content/Common/Research.form.tsx) please?

We also need to figure out how come the unit test is failing 🤔... You can run this locally with `yarn test:unit`

2023-04-16 11:09 UTC, AlfonsoGhislieri requested changes

2023-04-16 11:09 UTC, AlfonsoGhislieri commented on packages/components/src/FieldInput/FieldInput.tsx
>      <>
**Issue**:  I think this line here is breaking the tests because  if `input.value` is `undefined` it cannot access `length`. We should make sure to include some kind of check or conditional before. Eg: `showCharacterCount && maxLength`, this would also need to be included in or before the `onChange` (before is probably better to avoid uncessary processing).

But besides the tests it's best to make sure we don't perform these actions to avoid unecessary state updates, potential bugs and errors.

2023-04-20 16:17 UTC, AlfonsoGhislieri requested changes

2023-04-20 16:17 UTC, AlfonsoGhislieri commented on packages/components/src/FieldInput/FieldInput.tsx
> +        }}
**Issue**: This action should not be taking place unless we actually want to display the character counter like I mentioned in my earlier review comment.

2023-04-20 16:17 UTC, AlfonsoGhislieri commented on packages/components/src/FieldInput/FieldInput.tsx
>      <>
**Issue**: There are many cases where the fieldInput is used but we don't actually want to set or use this functionality, we don't want to burden the component with unecessary state management. An if statement to conditonally set the state would be preferred.

2023-04-20 16:17 UTC, AlfonsoGhislieri commented on packages/components/src/CreateComment/CreateComment.tsx
> -              >
@cerkiewny Can you get back to me on this?

2023-04-20 16:59 UTC, cerkiewny commented on packages/components/src/FieldInput/FieldInput.tsx
>      <>
Hooks can't be conditional AFAIK...

2023-04-20 18:57 UTC, AlfonsoGhislieri commented on packages/components/src/FieldInput/FieldInput.tsx
>      <>
My bad if this wasn't clear, I was referring to setting the state conditonally, not calling it conditionally. But, now I realize I must have quickly glanced over this and didn't realize you used nullish coalecing to take care of conditionally setting it. I was defaulting to something that was more explicit in my head eg:

```
const [curLength, setLength] = useState<number>(
  showCharacterCount && maxLength ? input.value.length : 0
);
```

2023-04-20 19:18 UTC, AlfonsoGhislieri commented on packages/components/src/FieldInput/FieldInput.tsx
>      <>
Also just came to mind but another interesting option could be to use Yup to create a schema and validate it, like was introduced in #2218, you can see an example in code [here](https://github.com/ONEARMY/community-platform/blob/3129cc8e7050e82162f047dd3735f68269c4f51b/packages/components/src/ResearchEditorOverview/ResearchEditorOverview.tsx#L23)

2023-04-20 20:12 UTC, cerkiewny commented on packages/components/src/FieldInput/FieldInput.tsx
> +        }}
You mean setLength should be conditional? input.onChange has to run, otherwise it breaks inputField

2023-04-20 20:15 UTC, AlfonsoGhislieri commented on packages/components/src/FieldInput/FieldInput.tsx
> +        }}
Yes exactly, I don't think we should be updating the state unless we are using the characterCounter right?

2023-04-20 20:19 UTC, cerkiewny commented on packages/components/src/FieldInput/FieldInput.tsx
> +        }}
No opinion here, sure, can change that.

2023-04-20 20:24 UTC, AlfonsoGhislieri commented on packages/components/src/FieldInput/FieldInput.tsx
>      <>
Just in general if you were interested in adding some schema validation since it's something we recently incorporated in the code base. Not at all necesssary.

2023-04-20 20:26 UTC, AlfonsoGhislieri approved these changes
Looks good @cerkiewny, thanks a bunch for the addition 🤩 and sorry for being a pain in the ass!

2023-04-20 20:34 UTC, merged