fix: map page missing flags
ONEARMY/community-platform pull request #2189
Opened 2023-03-30 14:32 UTC by thisislawatts

- chore: refactor to simplify typing
- chore: remove mock pin generation code
- chore: remove unused code
- fix: pass flag through from User object
- chore: refactor to common method

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-04-02 10:55 UTC, AlfonsoGhislieri requested changes
Looks good @thisislawatts really nice to see a lot of refactoring here! Just a left over rogue comment to remove 🎉

2023-04-02 10:55 UTC, AlfonsoGhislieri commented on src/pages/Maps/Content/View/index.tsx
>    // so that pins can be displayed as required
**Nitpick** this comment is a bit confusing now that the `handleMove` function has been removed

2023-04-04 07:12 UTC, AlfonsoGhislieri submitted a review, later dismissed

2023-04-04 17:15 UTC, thisislawatts commented
@AlfonsoGhislieri all the tests are passing now, guessing it could have been a flake?

2023-04-04 17:17 UTC, davehakkens approved these changes

2023-04-04 17:17 UTC, merged