fix: fail back to unknown flag for invalid country code
ONEARMY/community-platform pull request #2192
Opened 2023-03-30 18:53 UTC by thisislawatts

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-04-01 12:45 UTC, AlfonsoGhislieri requested changes

2023-04-01 12:45 UTC, AlfonsoGhislieri commented on packages/components/src/Username/Username.tsx
> +  'AG',
**Issue**: Could we maybe have a file inside `Username` with these codes, this makes the readability of the whole component not great.

We can even just make this more accessible by placing it in some helper folder for other components if we need to reuse it down the line?

2023-04-01 15:24 UTC, thisislawatts commented on packages/components/src/Username/Username.tsx
> +  'AG',
Update made in: https://github.com/ONEARMY/community-platform/pull/2192/commits/3a2901d1f24ee4d2a5ff28f6ae673180a904c5be

2023-04-02 11:02 UTC, AlfonsoGhislieri approved these changes

2023-04-02 11:02 UTC, merged