feat(platform): add color toggle to follow button on research page
ONEARMY/community-platform pull request #2205
Opened 2023-04-05 15:39 UTC by NoHara42

PR Checklist

- [ x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Adds the same color as the active notification icon to the thunderbolt inside any research item.

## Git Issues

Closes #2200

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_
<img width="569" alt="image" src="https://user-images.githubusercontent.com/43496778/230131525-e1a970c4-1552-449d-a0dc-59ca604be1f0.png">
<img width="553" alt="image" src="https://user-images.githubusercontent.com/43496778/230131599-5fea81a1-f988-4176-9dab-2b3f03db2d00.png">

2023-04-05 15:40 UTC, NoHara42 commented
What is the testing philosophy here, do we test extensively?

2023-04-05 17:46 UTC, thisislawatts commented
Thanks for raising the PR so quickly @NoHara42, we've some documentation on the testing approach here: https://onearmy.github.io/community-platform/Testing/overview, although it looks a little out of date. Recently I have been introducing tests at a lower level using jest and react testing library, primarily to speed up the feedback cycle whilst working.

You could look at extending the existing ResearchArticle test coverage to cover this scenario:
https://github.com/ONEARMY/community-platform/blob/master/src/pages/Research/Content/ResearchArticle.test.tsx

2023-04-12 10:43 UTC, davehakkens commented
Are you able to finish this @NoHara42 or need help?

2023-04-12 13:38 UTC, NoHara42 commented
@davehakkens hey Dave, I still intend to finish this up. Sorry the last few days were busier than I thought. 
I'll need another couple days before I can have another go at completing the tests I wrote.

2023-04-23 17:29 UTC, davehakkens commented
let me know if tou are able to do this @NoHara42. If not no worries we will take over. 
Want to merge it in so we can use it for season 3 :)

2023-04-24 15:48 UTC, NoHara42 commented
@davehakkens hey Dave, I will take another look right now and will comment again if I'm not able to complete it this session.

Currently working on a farm in the south of Spain so my time is a bit limited. 🐵

2023-04-24 21:13 UTC, NoHara42 commented
Had some issues setting up the Dev environment on my system today, some WSL drama...

I would like to take another crack at it tomorrow, as I have a test written. 

@davehakkens do you (or another contributor) have some time in the evenings to reassure me that the tests I'm writing are valid and my Dev environment is setup correctly?

I am getting a bunch of errors when I run all the projects unit tests.

2023-04-25 13:04 UTC, AlfonsoGhislieri commented
Hi @NoHara42 what tests are you running? The `yarn test:unit `should be for unit tests which is what I assume you have been writing? If its a component test then should be with `yarn test:components` 

I don't think these should be failing.. Let me know

2023-04-25 21:19 UTC, AlfonsoGhislieri requested changes

2023-04-25 21:19 UTC, AlfonsoGhislieri commented on src/pages/Research/Content/ResearchDescription.tsx
> +                )
**praise**: nice idea to include a fallback values to make this less prone to errors.

2023-04-25 21:19 UTC, AlfonsoGhislieri commented on src/pages/Research/Content/ResearchDescription.tsx
> +              }
**Issue**: Would be a lot cleaner to not have these colors hardcoded, would be nicer to add them to the theme/use the theme instead. You can find the theme files in [packages/themes/src](https://github.com/ONEARMY/community-platform/tree/master/packages/themes/src). Let me know if you have any questions or need any help for this.

2023-04-25 21:19 UTC, AlfonsoGhislieri commented on packages/components/src/Button/Button.tsx
>        )}
**Suggestion following issue above**: here you should use sx to so that you can access the theme colors directly. Eg:  `<Icon glyph={props.icon} sx={{ color: props.iconColor }} />`

2023-04-26 17:56 UTC, NoHara42 commented on packages/components/src/Button/Button.tsx
>        )}
I had to add `sx` to the `IconWrapper` Component directly, as it uses styled components, which didn't seem to work well with the theming I had defined.

2023-04-26 17:57 UTC, NoHara42 commented on src/pages/Research/Content/ResearchDescription.tsx
> +              }
Done

2023-04-26 18:03 UTC, NoHara42 commented
@AlfonsoGhislieri Should be done with your suggestions, also refactored some repeated theme colors while I was at it.

Sorry about the force pushes, I'm not the subtlest of git history cleaners. 🥲

2023-04-26 21:07 UTC, AlfonsoGhislieri commented
Thanks for this @NoHara42! Really appreciate the extra work refactoring the themeing! I just raised #2251 to fix the unit tests that were failing and made some minor changes. Your commits are still there in the history 🙃

2023-04-27 07:21 UTC, closed without merging