feat: adds draft status
ONEARMY/community-platform pull request #2206
Opened 2023-04-05 20:26 UTC by thisislawatts

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-04-12 10:42 UTC, davehakkens commented
Seems like its missing the part to go back and continue on the draft?
After saving as a draft I don't how to find it back, edit an publish?
Or am I not seeing it @thisislawatts?

2023-04-16 11:58 UTC, AlfonsoGhislieri commented on src/pages/Research/Content/ResearchArticle.test.tsx
>  })
**Suggestion**: Should we maybe include an assertion to check that 'Research Update #1' is showing just to be a little more thorough

2023-04-16 11:58 UTC, AlfonsoGhislieri commented on src/pages/Research/Content/Common/ResearchUpdate.form.tsx
> +                    type="submit"
**Question**: Why is `evt.preventDefault()` needed now compared to before?

2023-04-20 16:27 UTC, thisislawatts commented on src/pages/Research/Content/Common/ResearchUpdate.form.tsx
> +                    type="submit"
Good catch, thanks! Removed.

2023-04-20 16:27 UTC, thisislawatts commented on src/pages/Research/Content/ResearchArticle.test.tsx
>  })
Added ✨

2023-04-22 15:51 UTC, AlfonsoGhislieri approved these changes

2023-04-22 15:51 UTC, AlfonsoGhislieri commented on packages/components/src/ResearchEditorOverview/ResearchEditorOverview.stories.tsx
>      {
**Suggestion**: Could be good to have a story that shows some updates with the draft status

2023-04-22 15:51 UTC, AlfonsoGhislieri commented on src/pages/Research/Content/Common/ResearchUpdate.form.tsx
> +
**Praise**: nice refactoring here, good to see this added use of a type and pulling all this logic out of the main component return!

2023-04-22 19:53 UTC, AlfonsoGhislieri requested changes

2023-04-22 19:53 UTC, AlfonsoGhislieri commented on src/pages/Research/Content/Common/ResearchUpdate.form.tsx
> +                        props.formValues._id,
**Issue**: Should we not be checking or guarding `store.activeResearchItem.updates ` being undefined here, could it not cause an error if we try and map over it after?

2023-04-25 19:33 UTC, thisislawatts commented on src/pages/Research/Content/Common/ResearchUpdate.form.tsx
> +                        props.formValues._id,
Added https://github.com/ONEARMY/community-platform/pull/2206/commits/87137b47cd97e309749c1acf2202173ce6a43a63

2023-04-25 21:38 UTC, AlfonsoGhislieri approved these changes
Looks good to me @thisislawatts thanks for adding the fallback, just a conflict to resolve!

2023-04-26 05:53 UTC, merged