feat: adds quick navigation for Research
ONEARMY/community-platform pull request #2218
Opened 2023-04-10 18:42 UTC by thisislawatts

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-04-10 18:52 UTC, thisislawatts commented
Ps. The [failing cloud function test](https://app.circleci.com/pipelines/github/ONEARMY/community-platform/4338/workflows/ee59aa12-861c-4b84-8a6c-09bb5435f576/jobs/30298) seems unrelated. Likely an issue in the Cypress world.
![Screenshot 2023-04-10 at 20 51 24](https://user-images.githubusercontent.com/472589/230972326-35148b82-4eee-429f-b0dd-b8df30c68dd4.jpg)

```
The Cypress App could not be downloaded.
```

Although it begs the question, **why** are the serverless functions test installing Cypress 🤯

2023-04-12 11:00 UTC, davehakkens commented
Interesting feature @thisislawatts! 
Could eventually see this going to the frontend of the research to have an overview of all the steps in a (long) research.
Anyway for now i have this feedback:

- Images dont load well (they either dont show at all or they don't change when toggeling)
- When you "create update" from the quick menu it's a bit confusing to realise you just created a new step. Ideally a new number is added in the quick menu (perhaps as a draft?)
- How would this work with drafts?
- What exact problem are we trying to fix with this? I like adding features and improving the reseach module but also scared of the maintaince of them. Just trying to understand if the added complexcity is worth it.

2023-04-12 11:12 UTC, thisislawatts commented
@davehakkens the intention here is to solve the issue you raised in the draft status PR. Where you are unable to access a draft post because it is no longer visible in the front end.

Forcing a full page load would fix most of the bugs you've raised here.

2023-04-12 18:21 UTC, davehakkens commented
ah indeed that fixes the image bug. Is there a way to make this more user friendly?

2023-04-13 14:24 UTC, thisislawatts commented
@davehakkens aside from the confusing experience when creating a new update would you be able to help me understand what you find user unfriendly about this component?

I thought the Updates list could also show a badge to indicate when the Update has a `draft` status.

2023-04-13 18:33 UTC, davehakkens commented
> Its not implemented yet, but here's a sketch of how this listing could handle Draft items

That looks neat!  

> aside from the confusing experience when creating a new update would you be able to help me understand what you find user unfriendly about this component?

- I was mainly refering to the behaviour of the images. That you need a refresh to see the ones that belong to the step. This is not very user friendly/ intuitive. Not sure if it can have an auto refresh or something?

-Perhaps instead of calling the "updates" I would call it something like "research overview"

+ One (minor) thing that is a bit confusing is that they all use numbers, but they are not necesserly the same numbers on frontend. (since drafts don't have a number, step 3 is not step 3) But not sure how to fix this. Just throwing it there maybe you have brilliant ideas. If not no problem

2023-04-13 19:08 UTC, thisislawatts commented
The buggy image behaviour should be fixed by this commit: https://github.com/ONEARMY/community-platform/pull/2218/commits/ac3ec635533e944a5d9f49b1fbc057e40b2893ec, that is a long standing bug we've caught as part of this work :)

2023-04-13 19:19 UTC, thisislawatts commented
@davehakkens updated the heading and switched to an unordered list which removes the numbers.

![Screenshot 2023-04-13 at 21 17 56](https://user-images.githubusercontent.com/472589/231861354-23ca07ee-e930-4646-a7c4-f9e87b1f4368.jpg)

2023-04-13 20:38 UTC, davehakkens commented
nice. yeh now it works smooth! Nice to fix that bug along  the way.

One additional thought on this. (sorry I didnt have this clear yet, bit of a freestyle :))
The drafts seems to mess up a bit the logic of the steps.
And realistically I dont really see a case that a users wants to write an update, save as draft, create another new update and then get back to an unpublished draft from 3 steps ago and squeeze it in there again between other steps.

I think a draft is only needed for the latest step. A step that is still under development...

What about:
- Only the latest update can be saved as a draft
- We keep the numbers (not bullet points) to keep it clear and aligned.

2023-04-13 21:48 UTC, thisislawatts commented
At the moment these changes are separate from the Draft status PR. How do you feel about reviewing this change in isolation and then iterating on how this interacts with the Draft status work? 

One potential future for this quick nav component would be to support reordering Updates through drag and drop.

2023-04-14 16:30 UTC, AlfonsoGhislieri commented on src/common/Form/ImageInput/ImageInput.tsx
> +  }
**Suggestion**: While the risk is low in this case since the change is being caused by a prop, it could be good to have a stricter check and avoid any unecessary re-rendering. Could use `shouldComponentUpdate` before eg:

```
shouldComponentUpdate(nextProps, nextState) {
    return JSON.stringify(this.props.value) !== JSON.stringify(nextProps.value)
  }
```

This `componentDidUpdate` does also highlight how much simpler and flexible it would be to instead use `useEffect` if we were using functional components (I think it's also more performant).

2023-04-14 19:24 UTC, thisislawatts commented on src/common/Form/ImageInput/ImageInput.tsx
> +  }
Thanks for the pointer her @AlfonsoGhislieri, I didn't know about this optimisation. I took a [look at the documentation](https://react.dev/reference/react/Component#shouldcomponentupdate-caveats), and they specifically mention the following.
>  * This method only exists as a performance optimization. If your component breaks without it, fix that first.
> * We do not recommend doing deep equality checks or using JSON.stringify in shouldComponentUpdate. It makes performance unpredictable and dependent on the data structure of every prop and state. In the best case, you risk introducing multi-second stalls to your application, and in the worst case you risk crashing it.

My preference here would be to refactor the ImageInput component to be a functional component, however I don't want to bloat this PR too much and would rather defer that change for a separate PR. What do you think?

2023-04-14 19:26 UTC, thisislawatts commented on src/common/Form/ImageInput/ImageInput.tsx
> -}
This is unused at the moment, the FileInformation component had its own local implementation. I think that when FileInformation was extracted to be a in components package this duplication was introduced.

2023-04-14 19:28 UTC, thisislawatts commented on src/pages/Research/Content/Common/Update.form.tsx
> +                  ) : null}
Great idea! I wasn't sure about making it a component until people seemed interested in the approach. 
Here's the work to extract it to the component: f49c5e47b0813a232d58956f331a4a605324bc9a

2023-04-14 20:08 UTC, davehakkens commented
> At the moment these changes are separate from the Draft status PR. How do you feel about reviewing this change in isolation and then iterating on how this interacts with the Draft status work?

Sounds good to me!

2023-04-16 09:07 UTC, AlfonsoGhislieri commented on src/common/Form/ImageInput/ImageInput.tsx
> -}
Ah makes sense!

2023-04-16 09:24 UTC, AlfonsoGhislieri commented on src/common/Form/ImageInput/ImageInput.tsx
> +  }
Yeah that does seem like `shouldComponentUpdate` definitely isn't the correct solution then. Using `key` to reset the state could be maybe be best way then if that works? https://react.dev/reference/react/useState#resetting-state-with-a-key

But otherwise yes I agree, refactoring should definitely be a separate PR.

2023-04-16 09:43 UTC, AlfonsoGhislieri requested changes
Thanks @thisislawatts new component looks great, just a few small bits to maybe tweak I think.

2023-04-16 09:43 UTC, AlfonsoGhislieri commented on src/pages/Research/Content/Common/Update.form.tsx
> +                      sx={{ mt: 4 }}
**Nitpick**: Using conditional `&& `could be cleaner and more concise than ternary (I know you love those ternary operators 😉)

2023-04-16 09:43 UTC, AlfonsoGhislieri commented on src/pages/Research/Content/Common/Research.form.tsx
> +                    sx={{ mt: 4 }}
Same Nitpick as above

2023-04-16 09:43 UTC, AlfonsoGhislieri commented on packages/components/src/ResearchEditorOverview/ResearchEditorOverview.tsx
> +            <Text variant={'quiet'}>
**Issue**: Can we add the optional chaining operator `?` after updates `updates?.map ...`. Just to add a extra protection for any runtime errors.

2023-04-16 18:06 UTC, thisislawatts commented on src/pages/Research/Content/Common/Update.form.tsx
> +                      sx={{ mt: 4 }}
I found [this blog post](https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx) from a few years ago that persuaded me away from the `&&` pattern. I totally agree that it is a little more verbose but in this it is more explicit about the intended behaviour.

2023-04-16 19:38 UTC, thisislawatts commented on packages/components/src/ResearchEditorOverview/ResearchEditorOverview.tsx
> +            <Text variant={'quiet'}>
Thanks for catching that @AlfonsoGhislieri, I've added some tests that verify this behaviour **and** introduced yup for object validation. https://github.com/ONEARMY/community-platform/pull/2218/commits/fcabb6919b964e678344104c224b2f01c41220f4

Let me know if this is overkill, but I think its about time we adopted an schema validation language.

2023-04-18 16:55 UTC, AlfonsoGhislieri commented on src/pages/Research/Content/Common/Update.form.tsx
> +                      sx={{ mt: 4 }}
Wow, super interesting, didn't realize it would render 0! Thanks for the link :-)

2023-04-18 17:07 UTC, AlfonsoGhislieri approved these changes
Looks good @thisislawatts, really cool to see object validation being introduced! Nice to get another layer of validation, will be interesting to see if we get widespread use out of it.

2023-04-18 19:02 UTC, merged