feat: add research url redirect for title changes
ONEARMY/community-platform pull request #2279
Opened 2023-05-01 16:01 UTC by iSCJT

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Adds feature parity with how to's so that if the title of a research item is changed the old url slug will still work.

## Git Issues

Closes #2183

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-05-01 20:15 UTC, thisislawatts requested changes
**issue(blocking):** Can we add some tests here which validate this behaviour? Perhaps either to the e2e or `research.routes.test.tsx` suites.

2023-05-01 20:17 UTC, thisislawatts commented on src/stores/Research/research.store.test.ts
> +  await store.setActiveResearchItemBySlug('fish')
**praise:** Appreciate this renaming ✨

2023-05-03 22:08 UTC, iSCJT commented
> **issue(blocking):** Can we add some tests here which validate this behaviour? Perhaps either to the e2e or `research.routes.test.tsx` suites. 

Have added those now @thisislawatts

2023-05-05 12:00 UTC, thisislawatts approved these changes

2023-05-05 12:00 UTC, merged