feat: add countryflag to research collaborators
ONEARMY/community-platform pull request #2281
Opened 2023-05-01 23:06 UTC by AlfonsoGhislieri

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Adds contributors flags to bottom of reseach article and to updates

## Git Issues

Closes #2278

## Screenshots/Videos

![image](https://user-images.githubusercontent.com/652368/235546588-0d7eacf5-5459-45eb-aa6e-f77898e46068.png)
---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-05-02 11:03 UTC, AlfonsoGhislieri commented on src/pages/Research/Content/ResearchArticle.tsx
> +                    isVerified: false,
This feels very hacky to me, but the issue is that the unit tests fail because useEffect is not run when the components are rendered in jest. This causes the state to be empty and them to fail. This was the easy solution I could think of, but results in dulication of this block:

```
    const collaborators = Array.isArray(item.collaborators)
      ? item.collaborators
      : ((item.collaborators as string) || '').split(',').filter(Boolean)
```

And in general doesn't feel very clean

2023-05-02 17:42 UTC, thisislawatts commented on src/common/contributorData.ts
> +}
**question:** Given this fn has been mocked out in each component that uses it, what do we have in place to verify that this logic is correct?

2023-05-02 19:27 UTC, AlfonsoGhislieri commented on src/common/contributorData.ts
> +}
Currently nothing besides some eye tests and my word ;)

Jokes aside you're right this is definitely a section of code that needs coverage, will add it!

2023-05-05 11:49 UTC, thisislawatts commented on src/pages/Research/Content/ResearchUpdate.test.tsx
> +          getUserByUsername: jest.fn().mockResolvedValue({ country: '' }),
**nitpick (non-blocking):** Maybe we could use the FactoryUser() here so its a full User Object and not a partial.

2023-05-05 11:51 UTC, thisislawatts commented on src/common/contributorData.ts
> +              countryCode: user.location?.countryCode || user.country,
**suggestion:** Reuse the existing [`getUserCountry` helper](https://github.com/ONEARMY/community-platform/blob/master/src/utils/getUserCountry.ts#LL3C18-L3C18)

2023-05-05 11:58 UTC, thisislawatts requested changes

2023-05-05 11:58 UTC, thisislawatts commented on src/common/contributorData.ts
> +import { useEffect, useState } from 'react'
**question(blocking):** Should we namespace/nest these common hooks under `src/common/hooks` directory? I think it would be useful grouping mechanism. 

**issue:** The exported method is contributor**S**Data but the filename is _contributorData_. I think the filename should be _contributorsData_.

2023-05-05 12:33 UTC, AlfonsoGhislieri commented on src/common/contributorData.ts
> +import { useEffect, useState } from 'react'
Good idea, added the folder and modified the filename [870b400](https://github.com/ONEARMY/community-platform/pull/2281/commits/870b400bd8df1be34a52b5efc1fffdfb807c041b)

2023-05-05 12:33 UTC, AlfonsoGhislieri commented on src/common/contributorData.ts
> +              countryCode: user.location?.countryCode || user.country,
Added in [2285d8d](https://github.com/ONEARMY/community-platform/pull/2281/commits/2285d8d08bb4a0fa64564bd25ce90cfa8409a7b7)

2023-05-05 14:40 UTC, thisislawatts approved these changes

2023-05-05 14:40 UTC, merged