feat: release research follow / subscribe feature
ONEARMY/community-platform pull request #2331
Opened 2023-05-06 17:41 UTC by iSCJT

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Removes authwrapper from follow / subscribe feature of research and adds event tracking for feature use.

## Git Issues

Closes #2274 

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-05-06 20:16 UTC, thisislawatts requested changes

2023-05-06 20:16 UTC, thisislawatts commented on src/pages/Research/Content/ResearchDescription.tsx
> +          {props.loggedInUser && (
**issue(blocking):** The test suite "_displays "Follow" button text and color if not subscribed_" is failing. The arrange block needs to be adjusted to provide an activeUser otherwise this is a logged out view. Apologies this is non obvious :( 

```ts
;(useResearchStore as jest.Mock).mockReturnValue({
  ...mockResearchStore,
  activeUser,
})
```

2023-05-08 09:02 UTC, iSCJT commented on src/pages/Research/Content/ResearchDescription.tsx
> +          {props.loggedInUser && (
Thanks Luke, I hadn't seen that the test had failed till this morning.

2023-05-08 11:14 UTC, thisislawatts approved these changes

2023-05-08 11:16 UTC, merged