feat: shown follow button for non-logged in users
ONEARMY/community-platform pull request #2349
Opened 2023-05-11 10:30 UTC by soumya-b019

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description
Shown follow button for non-logged-in users
To achieve this I didn't allow it to render conditionally so that it can be visible to both logged-in as well as non-logged-in users. 
Also, I have added the tooltip that says "login to follow".

## Git Issues
#2337

## Screenshots/Videos

NA

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-05-11 11:18 UTC, iSCJT requested changes
If you could fix the brackets that would be appreciated and as an optional if you're up for it maybe add an e2e cypress test into: [packages/cypress/src/integration/research](https://github.com/ONEARMY/community-platform/tree/master/packages/cypress/src/integration/research)?  Thanks @soumya-b019!

2023-05-11 11:18 UTC, iSCJT commented on src/pages/Research/Content/ResearchDescription.tsx
> +          {(
Thanks for contributing @soumya-b019 🥇  The linting test has failed because we don't need to encapsulate the <Button> with brackets () now that there isn't any conditional logic.

You could fix this by running `yarn format` from a terminal in the route directory but the easiest would just be to delete rows 106 & 133 from your code completely 😃

2023-05-11 12:47 UTC, soumya-b019 commented on src/pages/Research/Content/ResearchDescription.tsx
> +          {(
Thank you for the suggestion. Sure I'll make the changes by removing the brackets ().
However, I'm unable to accommodate the E2E Cypress test at this time.

2023-05-14 10:52 UTC, iSCJT commented on src/pages/Research/Content/ResearchDescription.tsx
> +          {(
Thanks @soumya-b019

2023-05-14 10:52 UTC, iSCJT approved these changes

2023-05-14 13:29 UTC, merged