fix: how-to most useful sort
ONEARMY/community-platform pull request #2453
Opened 2023-06-21 08:52 UTC by iSCJT

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

- Fixes how-to most useful sort
- Fixes display of useful count on how-to list for cards with long title

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-06-21 09:43 UTC, AlfonsoGhislieri approved these changes

2023-06-21 09:43 UTC, AlfonsoGhislieri commented on src/pages/Howto/Content/HowtoList/SortSelect.tsx
**Question**: do we need to keep the `IProps` interface if it does not have any properties? Or is this being kept here in case we did want to use it in the future?

2023-06-21 20:30 UTC, thisislawatts requested changes
**issue (blocking):** As this is a fix can we introduce a failing test which documents the bug and passes due to the change being made here?

2023-06-22 10:38 UTC, iSCJT commented on src/pages/Howto/Content/HowtoList/SortSelect.tsx
to be honest I originally removed it completely but then couldn't get the injected store to work correctly so left the empty interface.  Any ideas?

2023-06-22 11:16 UTC, AlfonsoGhislieri commented on src/pages/Howto/Content/HowtoList/SortSelect.tsx
Looking into other examples in the codebase I see that the empty Props iterface seems to be used frequently, so clearly this is an issue that has appeared. The only way I can think of which could work is:

```
@inject('howtoStore')
@observer
class SortSelect extends Component<**any**, IState> {
  constructor(props: any) {
    super(props)
    this.state = { value: null }
  }

  get injected() {
    return this.props as InjectedProps
  }
```

But then we would just be bypassing any type checking, which is something I just saw done in the [header](https://github.com/ONEARMY/community-platform/blob/master/src/pages/common/Header/Header.tsx) and [eventListings](https://github.com/ONEARMY/community-platform/blob/master/src/pages/Events/Content/EventsListings/EventsListings.tsx). But, I think it's best to leave it like this with the empty interface as is seen in other files.

2023-06-23 11:21 UTC, thisislawatts approved these changes

2023-06-23 11:21 UTC, merged