Feature/merge to v2 drop legacy
ONEARMY/community-platform pull request #2466
Opened 2023-06-24 11:21 UTC by CDeighton

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Drops the old `/admin` code now that all of the features are in `admin_v2`

## Git Issues

Closes #2321

2023-06-27 05:02 UTC, CDeighton commented on src/modules/index.ts
> +      'howto,map,events,research,academy,user,admin',
Drops legacy admin and shifts `admin_v2` routes to `admin`

2023-06-27 12:22 UTC, iSCJT requested changes
@CDeighton one additional consideration with this is that the beta testers admin functionality isn't yet replicated in the new users page so that will also need to be replicated somewhere before fully deprecating v1 admin.

2023-06-27 17:50 UTC, AlfonsoGhislieri commented
Going to assign this over to you @iSCJT!

2023-06-28 11:35 UTC, CDeighton commented
> @CDeighton one additional consideration with this is that the beta testers admin functionality isn't yet replicated in the new users page so that will also need to be replicated somewhere before fully deprecating v1 admin.

@iSCJT oh yikes sorry 🤦 good catch! I thought the new `/admin_v2/users` route covered it but it looks like there is no way to add roles to users on that page.

If it is just the roles, how do you feel about having them on the `u/${username}/edit` screen (mockup below) - 

<img width="1436" alt="Screenshot 2023-06-28 at 11 29 37 PM" src="https://github.com/ONEARMY/community-platform/assets/13475443/7f0698fd-f916-482d-86b3-244d527eb430">

I'd hide the `super-admin` checkbox if a non-super-admin was looking at the screen of course. This way feels a little better to me because it consolidates the user management into a single place. Though it is very possible that I've missed another detail somewhere 😅 

I'm happy to just lift the existing screens as they are if you prefer though, I think it's roughly the same amount of work either way

2023-06-28 19:16 UTC, iSCJT commented
@CDeighton No problem at all, it's not the most obvious and intuitively you'd expect it to be in the new users screen.  At the moment we're trying to centralise the admin functionality into one place rather than have functionality spread across different pages so just lift the existing page into the v2 admin please.  Thank you 🌟

2023-07-03 08:14 UTC, CDeighton commented
@iSCJT should be good now 🤞 I'd recommend reviewing it commit by commit. Theres one for each of the admin and beta tester screens, then one to drop the old admin screen

2023-07-05 08:47 UTC, merged