fix(2305): forget to remove unused thing
ONEARMY/community-platform pull request #2470
Opened 2023-06-26 11:55 UTC by bagiyal

PR Checklist

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Removes direct usage of the theme object, instead accessing it within the sx property.

2023-06-26 13:06 UTC, AlfonsoGhislieri requested changes
Thanks for the PR @bagiyal, just a few things still missing:
- Please make sure you are using prettier for the formatting, this is required to make sure we have uniformity across the codebase. The linting tests are not pasing ( https://prettier.io/ )
- Please try to give clearer commits/PR titles in future work. 'forget to remove unused thing', is quite vague and not very informative. Something like 'refactor: make eventscreate theme aware' would go a long way.

Thanks for the work and let me know if you have any questions!

2023-06-26 14:44 UTC, AlfonsoGhislieri commented
> Sorry man !! Next time I will surely remember these things 🙂

No worries, appreciate the work! Let me know if you need any help with this.

2023-06-26 17:17 UTC, bagiyal commented
Yeah i wanna contribute more in precious plastic Give me more chances 😊

2023-06-26 19:43 UTC, bagiyal commented on src/pages/Events/Content/EventsCreate/EventsCreate.tsx
> +
yeah sure

2023-06-26 19:53 UTC, bagiyal reviewed
Done changes that you said

2023-06-27 09:25 UTC, AlfonsoGhislieri commented
Still have some failing tests here @bagiyal, these are linked to your commit messages. You want to follow convential commit messages, more here: https://www.conventionalcommits.org/en/v1.0.0/

Also conflict needs to be resolved before we can merge this in!

2023-06-29 09:45 UTC, AlfonsoGhislieri commented
The tests here are failing still @bagiyal, commit [a4f2765](https://github.com/ONEARMY/community-platform/pull/2470/commits/a4f27651e20446eae52a7d798dbc2d8a4a7480bb) does not adhere to the linting standards. 

This is also getting quite messy with lots of commits. I can suggest two options:
- Use rebase to `squash  `the commits and also rename the old `commit`: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message
- Open a new PR if you just find that easier

2023-06-29 09:51 UTC, bagiyal commented
@AlfonsoGhislieri i have done changes. Can you check again

2023-06-29 10:20 UTC, AlfonsoGhislieri requested changes

2023-06-29 10:20 UTC, AlfonsoGhislieri commented on src/pages/Events/Content/EventsCreate/EventsCreate.tsx
> -    }
**Issue(blocking)**: why was this styling removed and similarly from all the sx property of all labels?

2023-06-29 10:22 UTC, AlfonsoGhislieri commented
@bagiyal as I said earlier the issue is:
![image](https://github.com/ONEARMY/community-platform/assets/652368/6a5e62aa-5f30-4c24-b63d-7ca2384730db)

There are too many commits for this issue and you still have not fixed the commit message [a4f2765](https://github.com/ONEARMY/community-platform/pull/2470/commits/a4f27651e20446eae52a7d798dbc2d8a4a7480bb).

Please read my message from before on how to solve these issues.

2023-06-29 10:49 UTC, AlfonsoGhislieri commented
Closing this PR, I cleaned it up in #2305, you will still have credit for the work @bagiyal

2023-06-29 10:49 UTC, closed without merging