[refactor] consolidate common style variables
ONEARMY/community-platform pull request #2477
Opened 2023-06-26 17:17 UTC by BaltacMihai

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Developer experience (improves developer workflows for contributing to the project)

## Description

Consolidation of variables that are the same across all the different platforms into common files. This makes it easier to make changes, maintain and keep uniformity across the platform.

## Git Issues

Closes #2474

2023-06-27 07:30 UTC, AlfonsoGhislieri commented
Thanks for having already raised this so quickly @BaltacMihai, wasn’t expecting this so fast! Unfortunately the amount of overlap here really does highlight like @thisislawatts mentioned in #2474 that the better approach should be to use a base theme instead. 

Sorry about this and really do appreciate the work you’ve put into this already!

2023-06-27 07:34 UTC, BaltacMihai commented
Yes, I will try to make a common theme, I think it's a good step that I managed to remove all the repeating elements, so it's easier for me to create this common theme. Instead, I have to think about how I could modify it, so that it would be easy to overwrite certain elements, add something, etc.

2023-06-27 22:40 UTC, AlfonsoGhislieri requested changes
Thanks @BaltacMihai good work! I also am wondering

2023-06-27 22:40 UTC, AlfonsoGhislieri commented on packages/themes/src/common/index.ts
> +  static _commonInputStyle = {
**Question**: why are we using a class here? If we are just using it to store static variables and no methods we can just use an object instead right?

2023-06-27 22:40 UTC, AlfonsoGhislieri commented on packages/themes/src/common/index.ts
> +  colors: AuxiliaryStyle._colors,
**Thought**: Should we maybe separate the `baseTheme` and `AuxiliaryStyle` into two separate files? I know these two are closely related but it might make things more readable and easier to maintain down the line.

2023-06-27 22:40 UTC, AlfonsoGhislieri commented on packages/themes/src/common/index.ts
> +    white: 'white',
**Issue**: the use of underscores here also goes against convention for private variables. Underscores are used as to indicate private variables or function that are not meant to be accessed directly from outside the class/object. Since these are intended for use outside the class, it would be better to remove the underscores.

2023-06-27 22:40 UTC, AlfonsoGhislieri commented on packages/themes/src/common/index.ts
> +  static _commonInputStyle = {
**Nitpick(not blocking)**: these all seem to be common style variables, we should change the name of the class/objec to reflect this more accurately (eg: commonStyles)?

2023-06-28 05:28 UTC, BaltacMihai commented on packages/themes/src/common/index.ts
> +  static _commonInputStyle = {
Yes, my first thought was that I want a class that does not have the possibility to change the variables, that's why I put static, so we encourage the subsequent modification only on these components to have linearity. But yes, it is possible to return to an object, since currently there is no direct modification on common styles.

2023-06-28 05:29 UTC, BaltacMihai commented on packages/themes/src/common/index.ts
> +  colors: AuxiliaryStyle._colors,
Yes, that's a good idea.

2023-06-28 05:31 UTC, BaltacMihai commented on packages/themes/src/common/index.ts
> +    white: 'white',
Here is my mistake, I put "_" in the initial version where I had separate variables and I didn't take it into account when I refactored.

2023-06-28 05:32 UTC, BaltacMihai commented on packages/themes/src/common/index.ts
> +  static _commonInputStyle = {
Yes, that seems like a more accurate name for what we have.

2023-06-28 07:51 UTC, AlfonsoGhislieri approved these changes
Thanks @BaltacMihai looks good to go now! Great work

2023-06-28 07:51 UTC, merged