chore: remove deprecated useful items
ONEARMY/community-platform pull request #2478
Opened 2023-06-26 18:40 UTC by iSCJT

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Removes old useful items no longer used as part of new process.

## Git Issues

Closes #2407 

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-06-27 03:03 UTC, thisislawatts requested changes

2023-06-27 03:03 UTC, thisislawatts commented on functions/src/aggregations/migrations.ts
>  /**
**issue (blocking):** If this code is not being actively used please lets remove it and leverage git history should we need it again. 

* **Maintainability and Cleanliness**: Deprecated code can clutter the codebase and decrease readability. Code should be as clean and simple as possible. Any piece of code that is not recommended for use acts as noise and distracts developers.

* **Reducing Technical Debt**: By removing deprecated code, you are actively reducing the technical debt of the codebase, which will make future updates or changes to the system easier to manage.

* **Forced Updates**: Over time, deprecated code might become unsupported and could stop functioning correctly with new updates of the language or libraries. It's better to update this code before this becomes an issue.

* **Potential Errors and Security Risks**: Deprecated code can also present potential errors and security risks. Deprecated features are often not maintained or updated for security, so they may contain vulnerabilities that are not present in updated code. If the code is not actively being used there are no guarantees that it would be functional.

2023-06-27 10:34 UTC, iSCJT commented on functions/src/aggregations/migrations.ts
>  /**
Fair, I'll remove.

2023-07-01 13:19 UTC, thisislawatts approved these changes

2023-07-01 13:19 UTC, merged