fix: switch user _id to username
ONEARMY/community-platform pull request #2483
Opened 2023-06-26 23:20 UTC by iSCJT

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Further updates to switch the use of user _id's to usernames in the code base with the aim of preventing duplicate users being created.

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-06-27 02:50 UTC, thisislawatts requested changes

2023-06-27 02:50 UTC, thisislawatts commented on src/stores/User/user.store.ts
> -          .doc(updatedUser._id)
**question (blocking):** This seems to be the only part of the code in this PR which may affect whether a new User is being created. 

Could you explain a bit more about the change you are looking to make here? My understanding was that updatedUser._id should be equal to updatedUser.userName.

2023-06-27 10:22 UTC, iSCJT commented on src/stores/User/user.store.ts
> -          .doc(updatedUser._id)
Duplicate users are getting reintroduced into the system again and the 'wrong' users are in some cases the only ones getting updated.  Trying to clear all uses of the _id so that if duplicates are created that it's definitely the user record that has an _id that matches the username that gets updated.

2023-07-01 13:28 UTC, thisislawatts commented
Closing to keep the concept of `_id` and `userName` as separate entities.

2023-07-01 13:28 UTC, closed without merging