feat: add validation skip to research description
ONEARMY/community-platform pull request #2555
Opened 2023-07-04 15:07 UTC by benfurber

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

This adds a skip to the descripton field on the research form when saving a draft.

A couple of decisions I made as part of this - very happy to work further if others disagree.

1. I've only applied the validation skip to the description even though I believe the issue considered applying it to the title too. I'm guessing that if a title is left blank it'll cause issues deciding on a slug, etc.? And will be easier for users to navigate drafts if they don't have a load of 'untitled' research or similar?
2. The validation check is essentially off by default and then turned on to publish. That way users won't be annoyed by the error message until it's important. Totally lots of valid arguments to do it the other way around though.

Like I said, very happy to keep working on this if others disagree with my thinking. :)
 

## Git Issues

Closes #2541

2023-07-04 18:12 UTC, evakill reviewed
hey @benfurber! thanks for picking this one up

i pulled down your branch to test and the save as draft is working well without requiring the description, but it appears that i can also click publish with an empty description, which we don't want. i wonder if final form and react state aren't interacting well together? an idea i had was to make the moderation state a field value on the form - then the validation function can access the moderation state through the second param in the validate function (see docs https://final-form.org/docs/react-final-form/types/FieldProps#validate) let me know if that makes sense to you.

another issue i spotted was that once a draft is published it can be moved to "accepted" using this green check box. 
<img width="1341" alt="Screen Shot 2023-07-04 at 7 03 43 PM" src="https://github.com/ONEARMY/community-platform/assets/37253846/77f5ee0c-22a0-42dd-b889-f4fa0ccbaf2b">
this doesn't have any safeguards for validity, so incomplete research can be published from the draft state. we'd need to add additional checks here. ideally, they'd be shared through some sort of config between the form and this button. this also makes working with final-form a bit tricky... let me know if you want to chat more on potential solutions!

2023-07-04 18:29 UTC, benfurber commented
@evakill Oh wow, apologies for not testing this properly!

I'd love to talk about this more. Are you free/available now-ish through discord?

2023-07-04 19:55 UTC, benfurber commented
As we need to workout what to do with the accepted button element too, I'm thinking that the validation needs to be moved to the form level so that the rules can be easily shared. First attempt using [this as guide](https://codesandbox.io/s/github/final-form/react-final-form/tree/master/examples/record-level-validation?file=/index.js) didn't go very well as the whole form went into a loading state every time the title did a validation check(!)

I'm thinking of giving [this pattern](https://codesandbox.io/s/kl9n295n5?file=/index.js:1606-1633) a go tomorrow.

2023-07-05 07:17 UTC, iSCJT commented
@benfurber @evakill I've added a separate issue for the fact that moderators can approve a draft item: https://github.com/ONEARMY/community-platform/issues/2571

Will leave Eva to circle back on approaches as she had her head into the problem yesterday.

2023-07-05 13:19 UTC, benfurber commented on packages/cypress/src/integration/research/write.spec.ts
> +      cy.wait(2000)
I think this deals with a flaky test...

2023-07-05 13:20 UTC, benfurber commented on packages/cypress/src/integration/research/write.spec.ts
> -
Flow covered above, I don't think it's needed a second time and thus worth speeding the tests up.

2023-07-05 14:07 UTC, benfurber commented
What do you think about this approach @evakill?

2023-07-06 10:53 UTC, evakill requested changes
this looks great @benfurber! also good call @iSCJT to pull out the moderation into a separate issue. left some suggestions on the new approach.

also sorry i missed your invitation to chat, I'll be online most of today if you want to shoot me a message on discord :)

2023-07-06 10:53 UTC, evakill commented on packages/cypress/src/integration/research/write.spec.ts
> +  describe('[Create draft article]', () => {
these are great, thanks for taking time to improve tests 🙌

2023-07-06 10:53 UTC, evakill commented on src/pages/Research/Content/Common/Research.form.tsx
> +                            <Flex
i think that we can remove this hidden element. my understanding is that the final form `formValues` state does not _need_ to correspond to fields. `isDraft` will be undefined until we set it with the mutators on the button click. if we want to set `isDraft` more explicitly, we could add it to `src/pages/Research/Content/CreateResearch/Template.tsx` as an initial prop to the form. I'll leave that decision up to you! 

tested without the hidden checkbox to confirm: behavior works as expected, also did a little console.log test of `formValues`  - first log is on load, second on click of "Save as draft" and third is on click of "Publish"
<img width="1792" alt="Screen Shot 2023-07-06 at 11 41 04 AM" src="https://github.com/ONEARMY/community-platform/assets/37253846/ca098bee-f9c1-459c-8c54-4eb8ddb5cd83">

2023-07-06 10:53 UTC, evakill commented on src/pages/Research/Content/Common/Research.form.tsx
> +    const isDraft =
`allValues.isDraft` will be `boolean | undefined` so this can be simplified to 
```
const validateDescription = (value, allValues) => allValues.isDraft ? undefined : required(value)
```

2023-07-06 11:42 UTC, benfurber commented on packages/cypress/src/integration/research/write.spec.ts
> +      cy.wait(2000)
Update! ...It didn't...

2023-07-06 11:45 UTC, benfurber commented on src/pages/Research/Content/Common/Research.form.tsx
> +                            <Flex
Huh, thanks @evakill. I thought I tested (with exactly the same steps) removing the hidden field and it didn't work, but you're definitely right and it's fine.

2023-07-06 11:52 UTC, benfurber commented on src/pages/Research/Content/Common/Research.form.tsx
> +    const isDraft =
Ugh, thanks for noticing - this is from when I was playing with the visable field and missed this in my tidy up.

2023-07-06 12:11 UTC, benfurber commented
@evakill I think that's everything now. I'm also online for the next few hours, so I'd also certainly be up for working on something together.

2023-07-06 14:08 UTC, evakill approved these changes
LGTM!

2023-07-06 14:36 UTC, merged