feature request/delete how tos and research articles
ONEARMY/community-platform pull request #2594
Opened 2023-07-07 09:28 UTC by thisislawatts

- feat(platform): add delete button to allow user to delete their How-Tos
- parent 77a491b1682af09280a494eae059fe709545c404 author KungRaseri <countjoshington@gmail.com> 1687233276 -0700 committer KungRaseri <countjoshington@gmail.com> 1688677484 -0700
- feat(platform): add delete button to How-Tos and Research Articles

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-07-07 12:28 UTC, iSCJT requested changes
Thanks for doing the work on this, will be really good functionality that people have been asking for.  Found a couple of bits that will need tidying up and have made some code suggestions.

I also think that we should disable or hide the useful, edit and follow buttons for records marked for deletion.

2023-07-07 12:28 UTC, iSCJT commented on src/stores/Research/research.store.tsx
> +      }
Think this can be simplified.

```suggestion
      const user = this.activeUser

      if (id && user) {
        await dbRef.update({_id: id, _deleted: true})
        }

        if (this.activeResearchItem !== undefined) {
          this.allResearchItems = this.allResearchItems.filter(
            (researchItem) => {
              return researchItem._id !== id
            },
          )
        }
      }
```

2023-07-07 12:28 UTC, iSCJT commented on src/stores/Research/research.store.tsx
> +  public filterResearchesByCategory = (
This function has been reintroduced.  Should be handled by the new FilterSorterDecorator.

2023-07-07 12:28 UTC, iSCJT commented on src/stores/Research/research.store.tsx
> +        .sort((a, b) => (a._modified < b._modified ? 1 : -1))
We need to use the contentModifiedTimestamp now so that things like comments and useful votes don't change the listing position.

```suggestion
        .sort((a, b) => (a._contentModifiedTimestamp < b._contentModifiedTimestamp ? 1 : -1))
```

2023-07-08 01:07 UTC, lzizn commented on src/utils/helpers.ts
> +    user.userRoles && Array.isArray(user.userRoles) ? user.userRoles : []
`Array.isArray` accepts falsy, truthy, objects, NaN... you can call it directly

```suggestion
  const roles =
    Array.isArray(user.userRoles) ? user.userRoles : []
```

2023-07-08 01:08 UTC, lzizn commented on src/utils/helpers.ts
> +  ) {
```suggestion

  const userIsAdminOrDocOwner =
  roles.includes('admin') ||
  roles.includes('super-admin') ||
  (doc._createdBy && doc._createdBy === user.userName)
    
      if (userIsAdminOrDocOwner) {
```

2023-07-10 17:32 UTC, closed without merging