fix: update current imgIndex when clicking through images
ONEARMY/community-platform pull request #2600
Opened 2023-07-10 10:41 UTC by iSCJT

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

It was noticed that when viewing the photos from a gallery and then clicking the main image to open it full screen it would always open the first image rather than the selected one.

This pr updates the imgIndex when clicking through the thumbnails in the ImageGallery component so that the correct image is opened fullscreen.

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-07-10 15:19 UTC, thisislawatts submitted a review, later dismissed

2023-07-10 15:19 UTC, thisislawatts commented on packages/components/src/ImageGallery/ImageGallery.tsx
> +                onClick={() => setActive(image, index)}
**issue:** Can we introduce a test to `ImageGallery.test.tsx` which captures the desired behaviour and to guard against regression?

2023-07-11 09:19 UTC, evakill requested changes

2023-07-11 09:19 UTC, evakill commented on packages/components/src/ImageGallery/ImageGallery.tsx
> +      imgIndex: imgIndex,
with this change i think it makes sense for `activeImage` to become a derived state from `images` and `imgIndex` (maybe rename to `activeImageIndex`) rather than tracking both in the component state.

2023-07-19 22:20 UTC, iSCJT commented on packages/components/src/ImageGallery/ImageGallery.tsx
> +      imgIndex: imgIndex,
@evakill Yep agree that makes sense, should have looked at the code properly rather than just rushing a fix for Ale so I could get on with general help stuff.  I've refactored.

2023-07-19 22:21 UTC, iSCJT commented on packages/components/src/ImageGallery/ImageGallery.tsx
> +                onClick={() => setActive(image, index)}
@thisislawatts I'll cycle back to the tests as a separate issue as I've not mocked image data before so will need to look into how it's done and would prefer to get this pr cleared.  I'll add another issue for it in a minute.

2023-07-20 12:57 UTC, evakill approved these changes
lgtm!

2023-07-22 19:57 UTC, merged