feat: allow draft how-to save without form validation
ONEARMY/community-platform pull request #2609
Opened 2023-07-13 08:17 UTC by benfurber

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

This allows users to save a draft how-to with (at a minimum) a title provided. The smallest UI change has been done to enable this. But a lot of store changes were required for this to happen smoothly.

## Git Issues

Closes #2540 

## Screenshots/Videos

<img width="485" alt="Screenshot 2023-07-13 at 09 11 42" src="https://github.com/ONEARMY/community-platform/assets/16688508/7844b007-d101-4a14-8509-4efb4bc6c484">

2023-07-13 08:19 UTC, benfurber commented on packages/cypress/src/integration/howto/write.spec.ts
> +      // Then submit and check again
I will be finishing this off as part of this PR but I won't have a chance until the weekend so I thought I'd submit this all now for comments, etc.

2023-07-13 08:21 UTC, benfurber commented
I'm confused why this PR is pulling in a commit from Luke. `git pull upstream master` is telling me nothing is wrong...

2023-07-13 16:59 UTC, evakill reviewed
thanks for tackling this @benfurber! i gave some feedback from my first read-through. it's a big diff and touches a lot of types so i'd be curious if other @ONEARMY/maintainers have thoughts on this one.

2023-07-13 16:59 UTC, evakill commented on src/models/howto.models.tsx
> +export interface IHowtoFormInput extends IModerable, ISharedFeatures {
why extend `ISharedFeatures` here? i don't think the form input needs any of these fields

2023-07-13 16:59 UTC, evakill commented on src/pages/Howto/Content/Common/HowtoStep.form.tsx
> +  ) => void
i think it would be better to move this `validationWrapper` fn inside the validators file and import it to the component files. this would keep the components cleaner and allows the wrapper to be more easily discoverable for other form components.

2023-07-13 16:59 UTC, evakill commented on src/stores/common/mentions/index.ts
> +  text: string | undefined,
i think best to keep this fn as is and check for undefined before calling it (which you do in `src/stores/Howto/howto.store.tsx` in all cases i could find)

2023-07-13 16:59 UTC, evakill commented on src/stores/Howto/howto.store.tsx
> +    { cover_image }: IHowtoFormInput | IHowto,
nit: i think it's neater to pass in `cover_image` rather than `{ cover_image }`

2023-07-13 16:59 UTC, evakill commented on src/stores/Howto/howto.store.tsx
> +      const steps = await this.processSteps(stepValues, id)
nit: can simplify to one line 
```
const steps = values.steps ? await this.processSteps(stepValues, id) : []
```

2023-07-13 17:07 UTC, AlfonsoGhislieri commented on src/models/howto.models.tsx
> +  // note, tags will remain optional as if populated {} will be stripped by db (firestore)
**Question**: is there a reason `steps` here is not an optional parameter?

2023-07-13 17:15 UTC, AlfonsoGhislieri commented on src/pages/Howto/Content/Common/Howto.form.tsx
> +  }
**Thought**: if the other validation wrapper is pulled out to a separate file then this one should be as well

2023-07-13 17:25 UTC, AlfonsoGhislieri commented
Also definitely would be good to see some more e2e tests for this new change :-)

2023-07-21 09:17 UTC, benfurber commented on src/models/howto.models.tsx
> +  // note, tags will remain optional as if populated {} will be stripped by db (firestore)
Just a practical one, it is currently impossible to submit the form without at least one step present (even if all the fields in the step are empty. So thinking about it, it could be `steps: IHowToStepFormInput[]`

2023-07-21 12:10 UTC, benfurber commented
@evakill @AlfonsoGhislieri Finally ready for another review (sorry for the delay). I've tweaked some additional bits so probably worth a full read through if you don't mind.

2023-07-21 21:16 UTC, evakill requested changes
thanks for continuing to work on this @benfurber! i think it's close just needs a little clean up.

2023-07-21 21:16 UTC, evakill commented on src/stores/Howto/howto.store.tsx
> +      const total_downloads =
this logic is a bit different than what we had previously, which was: if there are files and `total_downloads` is not truthy, set it to 0. else do not set `total_downloads`.

i think this can be accomplished by instead defining this in the `howTo`: 
`...(files ? { total_downloads: values['total_downloads'] ?? 0 } : {}),`

does that make sense to you as well?

2023-07-21 21:16 UTC, evakill commented on src/stores/Howto/howto.store.tsx
> -      const previousSlugs: string[] = []
it looks like we've lost this bit of logic in the new version

2023-07-22 18:27 UTC, benfurber commented on src/models/howto.models.tsx
> +export interface IHowtoFormInput extends IModerable, ISharedFeatures {
I think this is the right place for it as IHowtoFormInput is used not just for initial first saves of content but also for resaves of IHowto.

2023-07-22 18:36 UTC, benfurber commented on src/models/howto.models.tsx
> +  previousSlugs: string[]
`ISharedFeatures` has it as optional. `previousSlugs` is set always set in `uploadHowTo` so can be required in IHowto.

2023-07-22 18:38 UTC, benfurber commented on src/stores/Howto/howto.store.tsx
> -    if (howToItem.previousSlugs === undefined) {
No. Relates to the other comment I just left. `previousSlugs` is set always set in `uploadHowTo`.

2023-07-22 18:45 UTC, benfurber commented on src/stores/Howto/howto.store.tsx
> -      const previousSlugs: string[] = []
The setting of the slugs? It's now on line 513 and I think(?) the new line fixes a bug that was there before - i.e. it was deleting all old slugs if the item was resaved.

2023-07-22 19:06 UTC, benfurber commented on src/stores/Howto/howto.store.tsx
> +      const total_downloads =
Apologies for not spotting I'd changed the logic. Could a test have caught that?

How do you feel about my approach which I think keeps the readability high?

2023-07-23 09:56 UTC, AlfonsoGhislieri commented
Would also be good to wait to merge this in until #2654 is incorporated as this has touched on the form validation!

2023-07-30 18:40 UTC, evakill commented on src/stores/Howto/howto.store.tsx
> -      const previousSlugs: string[] = []
but do we push a new slug into the array if the title or slug is defined on the update?

2023-07-30 18:44 UTC, evakill approved these changes
wooo! changes and rebase lgtm. thanks @benfurber, i know this functionality will be appreciated by our users 💪

2023-07-30 23:54 UTC, merged