chore: upgrade cypress@12.17.2
ONEARMY/community-platform pull request #2669
Opened 2023-07-25 15:12 UTC by benfurber

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Developer experience (improves developer workflows for contributing to the project)

## Description

Locally I'm finding no problem with the firefox tests, running on ci to see if there's issues.

## Git Issues

Closes #1522

2023-07-25 19:29 UTC, thisislawatts requested changes
**praise:** Thanks for picking this item up @benfurber. One small fix and then it looks ready to merge.

2023-07-25 19:29 UTC, thisislawatts commented on package.json
> +    "cypress": "12.17.2",
**issue (blocking):** It seems like there may have been a small oversight here. I've noticed that the `cypress` package has been added to the root application. We should avoid introducing this dependency in the root package.json file. Would you mind looking into this?

2023-07-26 07:25 UTC, benfurber commented on package.json
> +    "cypress": "12.17.2",
Yes! Sloppy of me, apologies.

2023-07-31 16:19 UTC, benfurber commented
@iSCJT - I forgot to ask earlier. Did you mean to add to this branch?

2023-08-10 15:40 UTC, benfurber commented
@evakill Rebased your change in.

2023-08-11 14:40 UTC, evakill approved these changes

2023-08-14 13:10 UTC, merged