add guidance to howto form
ONEARMY/community-platform pull request #2714
Opened 2023-08-14 14:40 UTC by benfurber

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #2683 

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-09-02 11:44 UTC, thisislawatts commented on src/pages/Howto/Content/Common/HowtoCategoryGuidance.test.tsx
> +    await screen.findByText('moulds category have some requirements', {
**question:** Could we load the `findByText` from the labels file? This would remove the hard coded text and make the tests less brittle to copy changes.

2023-09-02 14:51 UTC, benfurber commented on src/pages/Howto/Content/Common/HowtoCategoryGuidance.test.tsx
> +    await screen.findByText('moulds category have some requirements', {
I like the approach. Seeing as this label is formatted into html it makes this specific test still brittle but maybe less brittle?

2023-09-02 14:53 UTC, benfurber commented
@thisislawatts Suggested test change made with a comment. Also realising because of the order of work I did this month that this branch is pulling in code that's for #2720 - apologies.

2023-09-02 16:15 UTC, thisislawatts commented
> @thisislawatts Suggested test change made with a comment. Also realising because of the order of work I did this month that this branch is pulling in code that's for #2720 - apologies.

Gotcha, I think let's focus on merging #2720 as that is a subset of this PR and you and @evakill are working through review atm. I will label this one as blocked for the time being and we can come back to it after #2720 has been merged.

2023-09-24 06:38 UTC, thisislawatts commented
@benfurber, now that #2720 is merged do you think you can rebase this PR and we can move it forwards?

2023-09-25 12:55 UTC, benfurber commented
@thisislawatts Absolutely. Ready to finish this off. Added a clarifying question on #2683.

2023-09-26 16:54 UTC, thisislawatts commented on src/pages/Howto/labels.ts
> +      '<li>Step 5 > Tips & tricks</li>' +
**question:** Why have we marked this up as an unordered list with `ul` but then added a `Step n` to each one. Would an ordered list `ol` better align with the semantics of the content?

2023-09-26 16:55 UTC, thisislawatts commented on src/pages/Howto/labels.ts
> +      '<li>Step 5 > Tips & tricks</li>' +
**issue(blocking):** We are missing a Step 4 from this list.

2023-09-26 16:56 UTC, thisislawatts requested changes

2023-09-26 16:56 UTC, thisislawatts commented on src/pages/Howto/labels.ts
> +      '<li>Step 5 > Tips & tricks</li>' +
issue(blocking): We are missing a Step 4 from this list.

2023-09-27 11:05 UTC, benfurber commented
@thisismattia and @sigolenej - As I copied the copy exactly from [the guide](https://community.preciousplastic.com/academy/create/howto), @thisislawatts has a couple of questions for you.

1. As the steps are numbered and start 'step 1', etc. Would it be better to use a list with numbers rather than bullet points.
2. Products and guides 'miss' step 4 which I assumed is because you're trying to stay 'from step 5 onwards', but maybe that is a typo?

2023-09-27 13:50 UTC, thisismattia commented
Hey @benfurber nice one!

1. Yep ordered list sounds good
2. Defo a typo :)

2023-09-27 15:14 UTC, benfurber commented
Fixed. Updated screenshot:
<img width="550" alt="Screenshot 2023-09-27 at 16 12 43" src="https://github.com/ONEARMY/community-platform/assets/16688508/dac3ce91-a501-4692-b4a8-0aab535af5e7">

2023-09-27 17:27 UTC, thisislawatts approved these changes

2023-09-27 17:34 UTC, thisislawatts commented
Thanks @benfurber, looks great. Lets get this merged. I am curious does this also resolve Issue #2684?

2023-09-27 17:36 UTC, merged