feat: Adds stats to header of How-to and Research
ONEARMY/community-platform pull request #2737
Opened 2023-09-03 23:10 UTC by CheRayLiu

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-09-12 17:23 UTC, davehakkens commented
Hey @CheRayLiu are you able to add the tests? And could you let us know when its out of draft and ready for review. Would be great to see this merged!

2023-09-12 18:51 UTC, CheRayLiu commented
Hey @davehakkens it's ready for review! However, I haven't had time to add the tests. Will try to get to it by the end of the week.

2023-09-12 18:52 UTC, davehakkens commented
nice! @thisislawatts 👆

2023-09-13 18:05 UTC, CheRayLiu commented
Just added tests!

2023-09-14 20:58 UTC, thisislawatts requested changes

2023-09-14 20:58 UTC, thisislawatts commented on packages/components/src/Icon/Icon.tsx
> +      sx={{ color: props.color ?? 'inherit', opacity: props.opacity }}
**question(blocking):** As props.opacity is optional should we provide a fallback or default value for `opacity`?

2023-09-14 20:58 UTC, thisislawatts commented on packages/components/src/HowToStatistics/HowToStatistics.tsx
> +export const HowToStatistics = (props: IProps) => (
**issue(blocking):** Generally speaking we should aim for our components to be reusable across multiple places in the Platform. It looks like the 2 new components you have introduced here share very similar traits. So in theory you could refactor them to be a single component. 

Please take a look at a sketch I have added in https://github.com/ONEARMY/community-platform/pull/2737/commits/9b7110226b74d5d33a203fa1071bb2adf5dbdfe0 which introduces a generic `ContentStatistic` component. This does push the plural label formatting out to the controllers. What do you think of this approach?

2023-09-14 20:58 UTC, thisislawatts commented on packages/cypress/src/integration/research/read.spec.ts
> +      })
**praise:** Great to add these e2e checks around beta features, thank you!

2023-09-15 17:12 UTC, CheRayLiu commented on packages/components/src/Icon/Icon.tsx
> +      sx={{ color: props.color ?? 'inherit', opacity: props.opacity }}
Good call! I'll update it to default to '1' as that's the [default value of opacity](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity)

2023-09-15 17:25 UTC, CheRayLiu commented on packages/components/src/HowToStatistics/HowToStatistics.tsx
> +export const HowToStatistics = (props: IProps) => (
Yeah, I like that approach better to use `ContentStatistic`, thanks for the suggestion! 

I can create a reusable util method to handle the plural label logic there

2023-09-15 19:17 UTC, CheRayLiu commented on packages/components/src/HowToStatistics/HowToStatistics.tsx
> +export const HowToStatistics = (props: IProps) => (
Updated!

2023-09-27 18:06 UTC, davehakkens commented
Is this one be ready to merge @CheRayLiu @thisislawatts ?
Would help to build https://github.com/ONEARMY/community-platform/pull/2802

2023-09-27 18:29 UTC, CheRayLiu commented
Yep ready for merge from my perspective! Just waiting for additional reviews or approval

2023-09-30 19:04 UTC, thisislawatts commented
This is looking great @CheRayLiu, would you be able to resolve the merge conflicts? ThenI think we are in a place to merge this change ✨

2023-09-30 19:36 UTC, thisislawatts approved these changes

2023-10-04 17:33 UTC, CheRayLiu commented
Hey all, I fixed the merge conflicts and I think it's ready for merge!

However, it is failing due to an old commit message failing lint and I cannot find the commit to amend it in the commit log even using the sha shown on GitHub UI. Would it possible to override this lint commit rule?

2023-10-09 13:21 UTC, AlfonsoGhislieri commented
Hi @CheRayLiu, the issue is with [3e5603b](https://github.com/ONEARMY/community-platform/pull/2737/commits/3e5603bb0e46036d65ab7c0d00a3900f6450009e):

`✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
`
You could rebase interactively to change the commit and force push, as is explained in the github documenation:
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

2023-10-09 17:35 UTC, CheRayLiu commented
Hey @AlfonsoGhislieri Yep I am aware of the issue and I've tried to do that previously already for a few hours looking various ways. I cannot find the specific commit (3e5603bb0e46036d65ab7c0d00a3900f6450009e) to amend to changes. 

I will try again

2023-10-09 18:29 UTC, CheRayLiu commented
Hey @AlfonsoGhislieri Yes I am aware of the issue and I've tried to rebase interactively. I think the issue is that since it's the first commit of the branch, it doesn't show up when I do `git rebase -i ...` so I cannot reword the git message. 

I'll keep trying to search for a way resolve this.

2023-10-09 20:04 UTC, thisislawatts commented
Sorry for the extra hassle here @CheRayLiu, it is frustrating when git gets in the way like this.

2023-10-14 13:55 UTC, thisislawatts commented
Thank you so much @CheRayLiu for all the time and effort 💚, working with the changes you introduced here I created https://github.com/ONEARMY/community-platform/pull/2911. I've got you as a co-author for the changes.

2023-10-14 13:55 UTC, closed without merging

2023-10-15 18:15 UTC, CheRayLiu commented
No problem, apologies for not being able to push it through the finish line. Appreciate the help here! 🙏