fix: fixed issue #2682
ONEARMY/community-platform pull request #2749
Opened 2023-09-05 21:24 UTC by goratt12

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Added thumbnails to research list

## Git Issues

Closes #2682

## Screenshots/Videos

![image](https://github.com/ONEARMY/community-platform/assets/23094928/5ba4274a-5bd9-43d0-8c78-4bec33a8667e)

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-09-06 08:43 UTC, AlfonsoGhislieri commented
Thanks for this @goratt12, this makes me think we need to have a think about how to actually move forward in regards to generating and serving thumbnails. The current option that is proposed in this PR I think poses some issues for the resources that are needed and the sacalability moving forwards. To avoid having to pay off this debt down the line, I think we  should re-think the implementation.

Discussion on the topic in: 
https://discord.com/channels/586676777334865928/1148720148509900862

The two options that stand out to me:

- Storing the thumbnail in the DB (adding it to the items on upload and edit to avoid them going stale) --> this does require us to migrate all old howtos
- Using a cdn to service these images --> I wonder if we do have enough traffic/images to really need this approach, might be overengineering at this point?

I think this is definitely an area that could use some discussion before going ahead with implementing thumbnails, @ONEARMY/maintainers.

2023-09-10 19:15 UTC, davehakkens commented
Putting this here for visibility. Its an issue that had been opened up before https://github.com/ONEARMY/community-platform/issues/2548

No strong opinion on CDN vs resizing. But agree good moment to tackle the image-size issue side wide!

2023-09-13 00:13 UTC, davehakkens commented
hi @goratt12 meanwhile we figure out the discussion on the images. Would you be up for making it mobile ready? A bit bumpy atm
<img width="378" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/610fca1d-3892-4b17-b51e-813a77646d7a">

2023-09-14 08:22 UTC, goratt12 commented
Yeah sure, I’ll have a look at it @davehakkens

2023-09-14 15:09 UTC, goratt12 commented
Now the thumbnail will be hidden on mobile.

2023-09-14 19:12 UTC, thisislawatts commented on src/assets/images/default-research-thumbnail.jpg
@goratt12 As this image is only being used for a block that is ~100x100px I've downscaled the image to be 200x200px. This reduces the image size from 1.31mb to 11.7 kb

2023-09-14 19:18 UTC, thisislawatts commented on src/pages/Research/Content/ResearchListItem.tsx
> +    const latestImage = researchItem?.updates
**issue(blocking):** Please note that we should only load images from Updates which are publicly available. It is possible for an author to mark an update as either draft or deleted. In this case the author would not expect the image to be visible to the public.

Here's the logic [available elsewhere](https://github.com/ONEARMY/community-platform/blob/cd6ef960b50f64e59d2c3b50935c0a7e43b45e4d/src/pages/Research/Content/ResearchArticle.tsx#L254C1-L256C2):
```ts
const isUpdateVisible = (update: IResearch.UpdateDB) => {
  return update.status !== 'draft' && !update._deleted
}
```

It is being used in the same file to [filter updates for display](https://github.com/ONEARMY/community-platform/blob/cd6ef960b50f64e59d2c3b50935c0a7e43b45e4d/src/pages/Research/Content/ResearchArticle.tsx#L193C1-L195C40). It is probably worth introducing a shared helper for fetching these updates, perhaps something like `getPublicUpdates(researchItem.updates)`

2023-09-14 19:19 UTC, thisislawatts requested changes

2023-09-14 19:19 UTC, thisislawatts commented on src/pages/Research/Content/ResearchListItem.tsx
> +    const latestImage = researchItem?.updates
**issue(blocking):** Please note that we should only load images from Updates which are publicly available. It is possible for an author to mark an update as either draft or deleted. In this case the author would not expect the image to be visible to the public.

Here's the logic [available elsewhere](https://github.com/ONEARMY/community-platform/blob/cd6ef960b50f64e59d2c3b50935c0a7e43b45e4d/src/pages/Research/Content/ResearchArticle.tsx#L254C1-L256C2):
```ts
const isUpdateVisible = (update: IResearch.UpdateDB) => {
  return update.status !== 'draft' && !update._deleted
}
```

It is being used in the same file to [filter updates for display](https://github.com/ONEARMY/community-platform/blob/cd6ef960b50f64e59d2c3b50935c0a7e43b45e4d/src/pages/Research/Content/ResearchArticle.tsx#L193C1-L195C40). It is probably worth introducing a shared helper for fetching these updates, perhaps something like `getPublicUpdates(researchItem.updates)`

2023-09-16 19:18 UTC, goratt12 commented on src/pages/Research/Content/ResearchListItem.tsx
> +    const latestImage = researchItem?.updates
I created a shared function in the `src\utils\helpers.ts` file named `getPublicUpdates`.
linked both the thumbnail code and the `ResearchArticle.tsx` code

2023-09-17 10:22 UTC, thisislawatts approved these changes

2023-09-17 10:22 UTC, merged