feat: pin user howtos that require moderation/draft
ONEARMY/community-platform pull request #2752
Opened 2023-09-06 13:04 UTC by AlfonsoGhislieri

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Pins a users howtos to the top of the howto list if they are a draft/rejected/awaiting-moderation

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-09-06 13:08 UTC, AlfonsoGhislieri commented on src/stores/Howto/howto.store.tsx
> +    )
I was forced to pass the `validHowtos` to the `filterSorterDecorator.getSortedItems` function rather than modifying the `filterSorterDecorator` allItems directly like for [research items](https://github.com/ONEARMY/community-platform/blob/8022687ab9b4609d60e09d34e31a5c3e0b355586/src/stores/Research/research.store.tsx#L120)

I'm not sure why but when I try the same implementation for the howtoStore it just clears the `filterSorterDecorator.Items `array ...

2023-09-07 12:10 UTC, evakill requested changes
updating the active sorter "unpins" the moderation/draft PRs from the top because it uses the `sort` function rather than the `getSortedItems` function. not sure if this is expected behavior? but the research does not do that - items stay pinned despite the sort

2023-09-07 12:10 UTC, evakill commented on src/stores/Howto/howto.store.tsx
> +    this.filterSorterDecorator.allItems = validHowtos
why are we resetting `allItems` to `validHowtos`? if we want only the valid items sorted by `getSortedItems` i would suggest updating `getSortedItems` optionally accept a `listItems` argument as we do in the other methods

2023-09-07 12:35 UTC, AlfonsoGhislieri commented on src/stores/Howto/howto.store.tsx
> +    this.filterSorterDecorator.allItems = validHowtos
So this was my original thinking as well... I replicated the implementation that was originally also present in the research store.

The reason we are resetting it is because the `getSortedItems` function uses [allItems](https://github.com/ONEARMY/community-platform/blob/1e8155d4573417986fc6c63681fcf9c8c989ba8a/src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts#L136) from it's own class, I had originally implemented it like you suggested but changed it back to avoid making more changes.

Happy to go back and do this though!

2023-09-07 17:42 UTC, AlfonsoGhislieri commented
So the latest commit makes sure that everything works, I do think that there could be some re-thinking about how it's all implemented. I'll have a look at refactoring and improving this in a future PR. Let me know what you think @evakill and if you think we should pass the valid items to `filterSorterDecorator` or leave it like it is now (just like with the research store, but I'll have a look at improving this as well in a next PR)

2023-09-08 20:05 UTC, evakill requested changes
the more i play with this the weirder things get 😅 
some observations:
- changing the sorter doesn't always trigger a resort? not sure why
- sometimes things get unpinned still
- maybe we should have a "backup" unique sort key that's the id or something. that means that every time you change a sorter, you'll get the same result. without this, the sorter will not move things with the same value, so orders are not consistent (lmk if this makes sense it's hard to explain lol)


https://github.com/ONEARMY/community-platform/assets/37253846/2efa9ea4-60bd-429d-b7c9-74973525f319

2023-09-09 11:02 UTC, AlfonsoGhislieri commented
Hmmm well this is quite interesting...

>changing the sorter doesn't always trigger a resort? not sure why

This doesn't seem to be the case at all locally... So I wonder why on the preview it's happening.. Will have a look into this, maybe something with caching hmm

>sometimes things get unpinned still

This is by design, it's because when you are sorting by other filters eg: category or the direct search that don't match then it will disregard any post that doesn't match those parameters. Regardless of it being your own howto that is in awaiting-moderation, rejected  or draft. I thought this was the desired design as it may then just be very confusing if they are always showing even when doing a detailed search (it's the same for researches). Or do we really always want all of them pinned regardless of whether or not they are even in the right category for example? 

>maybe we should have a "backup" unique sort key that's the id or something. that means that every time you change a sorter, you'll get the same result. without this, the sorter will not move things with the same value, so orders are not consistent (lmk if this makes sense it's hard to explain lol)

Here you lost me a little @evakill! Not exactly sure what you mean here

2023-09-09 11:11 UTC, AlfonsoGhislieri commented on src/stores/Howto/howto.store.tsx
> +    this.filterSorterDecorator.allItems = validHowtos
Sure, I think this is probably the better approach as well, will be more in line with the other functions as well. We can pass the `validItems` to the `getSortedItems` directly.

2023-09-09 13:32 UTC, AlfonsoGhislieri commented on src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
> +      ItemSortingOption[sorter as keyof typeof ItemSortingOption]
Good catch, too much time away fro TS.. Removed in 6c0172e

2023-09-09 13:37 UTC, AlfonsoGhislieri commented on src/stores/Howto/howto.store.tsx
> +    this.filterSorterDecorator.allItems = validHowtos
Passing validItems to the `sort` function which then passes them along to `getSortedItems` 6c0172e. 

I think a case could be made to merge `sort` and `getSortedItems` into one function.. `getSortedItems` is never used outside of `sort`, not sure we really need these to be separate functions? But this should probably be one for a refactor PR..

2023-09-09 21:10 UTC, AlfonsoGhislieri commented
Some of the weird behaviour that you observed @evakill was due to the shuffling of the items in the lists when items had equal values, the fix in #2761 should address that. And I think this is in line with the reasoning you were suggesting here?

> maybe we should have a "backup" unique sort key that's the id or something. that means that every time you change a sorter, you'll get the same result. without this, the sorter will not move things with the same value, so orders are not consistent (lmk if this makes sense it's hard to explain lol)

2023-09-10 15:52 UTC, AlfonsoGhislieri commented on src/stores/Research/research.store.tsx
>      this.activeSorter = sorter
this is no longer needed since `this.activeSorter` being observable triggers the computed get `filteredResearches` value

2023-09-10 15:53 UTC, AlfonsoGhislieri commented on src/stores/Howto/howto.store.tsx
>      this.activeSorter = sorter
this is no longer needed since `this.activeSorter `being observable triggers the computed get `filteredHowtosvalue` to be re-run

2023-09-13 20:19 UTC, evakill commented
cool! this looks like an overall improvement, thanks for the updates and comments @AlfonsoGhislieri. i'm ready to stamp the code, but still getting something weird on the preview where only 8 howtos show up and i'm not able to add a new one. is that happening for you? might just need a rebase, not sure

2023-09-13 21:17 UTC, AlfonsoGhislieri commented
@evakill yeah I think it must have been an issue with the preview, now that I rebased it looks to be working like it should (all still good locally as well)

2023-09-13 21:28 UTC, evakill approved these changes
woooo same! 🚢 🚢 🚢

2023-09-13 21:38 UTC, merged