Feat: remove howto footer, add comment focus
ONEARMY/community-platform pull request #2779
Opened 2023-09-13 15:36 UTC by AlfonsoGhislieri

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Removes footer for howto's as suggested by @davehakkens  in #2774, also adds focus to the comments form when pressing leave a comment button for a better use experience

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-09-13 21:13 UTC, davehakkens commented
Looks good to me! 👍

2023-09-14 19:46 UTC, thisislawatts requested changes

2023-09-14 19:46 UTC, thisislawatts commented on src/pages/Howto/Content/Howto/Howto.tsx
> -import WhiteBubble0 from 'src/assets/images/white-bubble_0.svg'
**issue(blocking):** It looks like these images are not being used anywhere else. Can we remove them please 🙏🏻

2023-09-15 12:35 UTC, AlfonsoGhislieri commented on src/pages/Howto/Content/Howto/Howto.tsx
> -import WhiteBubble0 from 'src/assets/images/white-bubble_0.svg'
The images are being use by the [`MoreContainer` component](https://github.com/ONEARMY/community-platform/blob/master/packages/components/src/MoreContainer/MoreContainer.tsx) that is used inside the HowtoList.

2023-09-22 18:20 UTC, thisislawatts commented on src/pages/Howto/Content/Howto/Howto.tsx
> -import WhiteBubble0 from 'src/assets/images/white-bubble_0.svg'
Apologies for the delay. These images are duplicated and also exist within the `packages/components` directory, so we can remove them from the root of project.

2023-09-25 08:07 UTC, AlfonsoGhislieri commented on src/pages/Howto/Content/Howto/Howto.tsx
> -import WhiteBubble0 from 'src/assets/images/white-bubble_0.svg'
Ahh good catch @thisislawatts of course... Removed them in [4b553cb](https://github.com/ONEARMY/community-platform/pull/2779/commits/4b553cbd4b59b4fad465e74a699a122b10b89823)

2023-09-30 18:57 UTC, thisislawatts approved these changes

2023-09-30 18:57 UTC, merged