fix: prevent signup if username contains invalid characters
ONEARMY/community-platform pull request #2780
Opened 2023-09-13 18:59 UTC by jgable

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

- Add a new `noSpecialCharacters` validator along with a `getSpecialCharacters` helper.
- Refactored the SignUp form to use the new validator via `composeValidators`.

## Git Issues

Closes #2408 

## Screenshots/Videos

<img width="744" alt="Screenshot 2023-09-13 at 11 51 01 AM" src="https://github.com/ONEARMY/community-platform/assets/164497/56c96484-ac06-4ea1-ad0f-7b6e2ce32aba">

I also tested the signup flow worked when using a display name without special characters and ran the SignUp Cypress tests locally.

2023-09-13 21:26 UTC, AlfonsoGhislieri commented on src/utils/validators.test.ts
> +    expect(result).toBeDefined()
**Nitpick**: we don't need this assertion, we are already checking that the result will contain a string  after

2023-09-13 21:34 UTC, AlfonsoGhislieri commented on src/utils/validators.ts
> +    : undefined
**Issue**: not so sure about the error message here, it's a little confusing with the semi colon followed by a special characters in question..

Maybe we can use something simpler and easier for the user to understand at just a glance, eg: "Only letters and numbers are allowed." Taking this from [Microsoft 365](https://learn.microsoft.com/en-us/office/troubleshoot/office-suite-issues/username-contains-special-character)

2023-09-13 21:35 UTC, AlfonsoGhislieri requested changes
Thanks for this @jgable just a couple things I would change!

2023-09-13 21:37 UTC, AlfonsoGhislieri commented on src/utils/validators.ts
> +        .join(', ')}`
```suggestion
    ? "Only letters and numbers are allowed."
```

Issue: not so sure about the error message here, it's a little confusing with the semi colon followed by a special characters in question..

Maybe we can use something simpler and easier for the user to understand at just a glance, eg: "Only letters and numbers are allowed." Taking this from Microsoft 365

2023-09-14 21:21 UTC, AlfonsoGhislieri commented
Thanks for the changes here @jgable, just linting test failing since prettier wasn’t run on one of the files (validator test file)

2023-09-15 12:41 UTC, AlfonsoGhislieri commented
Thanks for the changes @jgable, we are failing the lint test in the `src/utils/validators.test.ts` file because prettier wasn't run on the file. Could we fix that please? :-)

https://prettier.io/

2023-09-30 19:56 UTC, thisislawatts approved these changes
Thanks @jgable for the time and effort on this PR ✨ Appreciate you for helping to build the community platform.

2023-09-30 19:56 UTC, merged

2023-09-30 19:56 UTC, thisislawatts commented
@all-contributors add @jgable for code