feat: adds question module
ONEARMY/community-platform pull request #2788
Opened 2023-09-15 07:22 UTC by thisislawatts

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-10-06 03:50 UTC, felipelmota approved these changes

2023-10-09 13:08 UTC, AlfonsoGhislieri requested changes

2023-10-09 13:08 UTC, AlfonsoGhislieri commented on src/pages/Question/question.routes.test.tsx
> +  formatResearchCommentList = jest.fn()
**Issue**: many of these mocked functions seem to be for the Research store and not the question store.

2023-10-09 13:08 UTC, AlfonsoGhislieri commented on src/stores/Question/question.store.tsx
> +export const useQuestionStore = () => useContext(QuestionStoreContext)
**Suggestion**: would be good to add tests for the question store

2023-10-17 19:10 UTC, thisislawatts commented on src/models/question.models.tsx
> +
Perhaps but that seems like a refactor that would benefit a broader chunk of the codebase and is not tightly coupled to the change we are making here.

2023-10-17 19:11 UTC, thisislawatts commented on src/models/question.models.tsx
> +}
Resolved in e8a6c4faa5739b507aa7a8916e4cb085cfb078fb

2023-10-17 19:38 UTC, thisislawatts commented on src/stores/Question/question.store.tsx
> +export const useQuestionStore = () => useContext(QuestionStoreContext)
Fixed in: 34899bae33b263c722981da56d9c17f4808df28f

2023-10-18 08:15 UTC, AlfonsoGhislieri approved these changes
Thanks for the changes and adding the tests and the scaffolding for store testing @thisislawatts

2023-10-18 08:15 UTC, merged