feat: add profile contact form
ONEARMY/community-platform pull request #2947
Opened 2023-10-24 11:35 UTC by benfurber

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #2607

## Screenshots/Videos

<img width="1078" alt="Screenshot 2023-10-24 at 12 28 54" src="https://github.com/ONEARMY/community-platform/assets/16688508/7d3f441e-4371-4519-b756-a03d58e557bf">
<img width="923" alt="Screenshot 2023-10-24 at 12 31 06" src="https://github.com/ONEARMY/community-platform/assets/16688508/477a398b-56a7-41b3-a718-e9efe0404403">

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-10-24 17:06 UTC, thisislawatts commented on src/modules/index.ts
> +  MESSAGE = 'message',
**Question:** Is this a standalone module or is it fundamental to interactions between Users so instead we should consider it a standard capability of Users rather than an optional extra?

WDYT @davehakkens

2023-10-24 17:10 UTC, davehakkens commented on src/modules/index.ts
> +  MESSAGE = 'message',
Would indeed see this as a standard feature of the platform for all group profiles.

2023-10-26 10:54 UTC, davehakkens commented
Logo/image doesnt seem to load in the email..
<img width="597" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/4413310f-d835-422c-bf77-cef8f5abe5ea">

2023-10-27 14:19 UTC, benfurber commented
> Logo/image doesnt seem to load in the email.. <img alt="afbeelding" width="597" src="https://user-images.githubusercontent.com/13672737/278306347-4413310f-d835-422c-bf77-cef8f5abe5ea.png">

Sorry @davehakkens I forgot to say, this is just because it's taken from the dev environment - it calls the same notification template as every other notification, so if that's working fine on prod for all the others, it'll be working fine for this.

2023-10-28 04:57 UTC, thisislawatts requested changes

2023-10-28 04:57 UTC, thisislawatts commented on functions/src/emailNotifications/createSubmissionEmails.ts
> +
**issue(blocking):** We need to include some additional checks here before writing to the emails collection.
1. The `toUserEmail` is associated with an actual User within the platform. Otherwise anyone with direct write access to the `messages` collection will be able to send emails.
2. The User record that is being referenced by the `toUserEmail` has the expected value in `isContactableByPublic`
3. The User who created the Message has not exceeded the upper limit on number of messages sent. This control could be bypassed if a User directly manipulated the Messages store.

2023-10-28 04:57 UTC, thisislawatts commented on src/modules/index.ts
> +  MESSAGE = 'message',
Sounds good to me, so lets remove the module wiring @benfurber

2023-10-28 04:57 UTC, thisislawatts commented on src/pages/User/contact/UserContactForm.tsx
> +} from './'
**question:** My preference here would be using direct imports from the file than loading rather than via an index file. What value does that provide?

2023-10-30 13:41 UTC, benfurber commented on functions/src/emailNotifications/createSubmissionEmails.ts
> +
[How's this](https://github.com/ONEARMY/community-platform/pull/2947/files#diff-c44dbba562fdb839e6e8a3bbf2d810e55e362a5a4d3d456cbac8bf4328926ddcR43) @thisislawatts?

2023-10-30 18:19 UTC, thisislawatts commented on functions/src/emailNotifications/utils.ts
> +    const error = new Error(`'${email}' attempted to send a message but isn't a user`)
**issue:** Can we avoid including dynamic attributes in the Error name? Static error messages are easier to search for in codebases and logs. If we are looking through logs trying to diagnose an issue, having a consistent error message helps. 

A consistent error message also allows us to add some alerting if we wanted to. For example if there are X instances of this error in Y minutes we want to raise an alert as it suggests a sustained attack.

2023-10-30 18:23 UTC, thisislawatts commented on functions/src/emailNotifications/utils.ts
> +    return false
**suggestion:** As we have this method wrapped in `withErrorAlerting`, I believe all we need to do is throw an error and let the error handler log it. 

```suggestion
    throw new Error(`User has exceeded email message count`)
```

2023-11-06 20:16 UTC, thisislawatts commented on src/stores/Message/message.store.tsx
> +      logger.error(`${error} by ${values.email}`)
**suggestion(blocking)** Can we avoid using dynamic variables in the logger and instead pass them through as a separate argument?

Although I am wondering about whether we should log this email address as it represents PII which will mean if we get a GDPR request we would need to purge our logs 😬

2023-11-06 20:16 UTC, thisislawatts approved these changes

2023-11-13 05:50 UTC, thisislawatts approved these changes

2023-11-13 05:53 UTC, thisislawatts commented
@benfurber before merging can you rebase/squash the history so that these commits are merged into a single releasable change. This will ensure a single meaningful message when generating the release notes. 
https://github.com/ONEARMY/community-platform/releases

2023-11-15 10:52 UTC, merged