feat: add display of impact data
ONEARMY/community-platform pull request #3004
Opened 2023-11-17 14:04 UTC by benfurber

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

This adds the large majority of the display for the impact data on workshop profiles.  

Missing: 
* As the tab layout changes haven't been implemented, the backgrounds are inverted in this.
* As no settings exist yet, the display of the tab is hidden unless impact data has been manually added to the database.
* As no settings exist yet, link to add impact data isn't present.
* TEMPORARILY: The links to the 2022 and 2021 impact reports - can I have these please.

## Git Issues

A large part of #3001.

## Screenshots/Videos

<img width="1049" alt="Screenshot 2023-11-17 at 13 54 31" src="https://github.com/ONEARMY/community-platform/assets/16688508/91af346c-af0f-46c3-899c-fca77ab9f40c">
<img width="1049" alt="Screenshot 2023-11-17 at 13 57 30" src="https://github.com/ONEARMY/community-platform/assets/16688508/bdc63214-f88b-4033-a276-badc35e40a3d">

2023-11-17 15:55 UTC, thisismattia commented
Thanks @benfurber nice and simple 🤙
DMing you the csv with impact data on discord. 

We have data about:
- 2019
- 2022
- 2023 (coming soon)

The design was just for the sake of seeing how it would look a few years down the line.

2023-11-17 20:05 UTC, thisislawatts requested changes

2023-11-17 20:05 UTC, thisislawatts commented on src/utils/helpers.ts
> +}
**suggestion:**  Consider using Intl.NumberFormat, this is a more versatile and internationalization-friendly approach. Intl.NumberFormat is a constructor for objects that enable language-sensitive number formatting.

```ts
export const numberWithCommas = (number: number) => {
  return new Intl.NumberFormat().format(number);
}
```

Further information: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat#basic_usage

2023-11-17 20:11 UTC, thisislawatts commented
Thanks @benfurber, I've added a few small comments but otherwise this is looking really good :)

2023-11-17 20:13 UTC, thisislawatts commented on src/pages/User/content/SpaceProfile.tsx
> +          <Tabs defaultValue={2}>
**question:** Do we want to automatically select this tab or is this a leftover from testing?

2023-11-17 20:14 UTC, thisislawatts commented on src/pages/User/content/SpaceProfile.tsx
> +            {impact && (
**question:** Can we add the AuthWrapper beta-tester for this as well? That will give the moderators a chance to verify the data before it is visible for all users.

2023-11-24 20:47 UTC, benfurber commented
@thisislawatts All your comments easily dealt with now, so no need for another full review, just need you to approve so I can merge.

2023-11-27 18:30 UTC, thisislawatts approved these changes

2023-11-27 18:30 UTC, merged