feat: Discussion model and store for persisting data
ONEARMY/community-platform pull request #3092
Opened 2023-12-22 07:33 UTC by thisislawatts

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-12-22 15:49 UTC, benfurber requested changes
The store is very easy to read, thank you. And I'm totally with use adding proper return values to everything. 

Is adding Discussion to the `IStores` list on `src/stores/index` missing?

2023-12-22 15:49 UTC, benfurber commented on src/stores/Discussions/discussions.store.tsx
> +  public formatComments(
Should a formating function be in the store? Feels like a helper function?

2023-12-22 15:49 UTC, benfurber commented on src/models/index.ts
> +  showReplies: boolean
Is this a presentational type? If it is, considering your point on discord yet now, should it be in a model type?

But maybe I'm wrong, I'm not sure from this PR I can see what this field is for.

2023-12-22 15:49 UTC, benfurber commented on src/stores/Discussions/discussions.store.tsx
> +            this.userStore.activeUser?.userName,
Do we have user ids? I thought userName was the primary key anyway?

2023-12-22 15:49 UTC, benfurber commented on src/stores/Discussions/discussions.store.tsx
> +      }
There's a lot going on in this map return, could some of it be pulled into variables above to aid readability?

2023-12-22 15:49 UTC, benfurber commented on src/stores/Discussions/discussions.store.tsx
> +      const comment = text.slice(0, MAX_COMMENT_LENGTH).trim()
I don't think this is right behaviour. If a comment is longer that what should be stored, it should error and give the user the chance to correct rather than persisting something different to what the user intended.

2023-12-22 15:49 UTC, benfurber commented on src/stores/Discussions/discussions.store.tsx
> +          _created: new Date().toISOString(),
Minor thought. OK, it's only on one line, but could the date creation be a helper? Then we can use that helper across all the stores ensuring consistency

2023-12-22 15:49 UTC, benfurber commented on src/stores/Discussions/discussions.store.tsx
> +        }
Should this before newComment?

2023-12-22 15:49 UTC, benfurber commented on src/stores/Discussions/discussions.store.tsx
> +      const comment = text.slice(0, MAX_COMMENT_LENGTH).trim()
Same comment as above.

2023-12-22 15:49 UTC, benfurber commented on src/stores/Discussions/discussions.store.tsx
> +import { changeUserReferenceToPlainText } from '../common/mentions'
Probably for the test file too but certainly for this one, maybe you please forgive my request for import ordering pedantry - it helps be understand the shape of a files connections. Ideally the package imports, gap, local imports, gap, types. A compromise I think is at least the type imports seperated from the rest.

2023-12-22 16:14 UTC, benfurber commented on src/stores/Discussions/discussions.store.tsx
> +  public async fetchDiscussion(sourceId: string): Promise<IDiscussion | null> {
sourceId or _id?

2023-12-22 16:16 UTC, benfurber commented on src/models/discussion.models.tsx
> +  sourceType: string
Shouldn't sourceType be stricter? e.g.:
````type SourceType = 'howto' | 'research' | 'comment'```

2023-12-22 16:24 UTC, thisislawatts commented on src/models/discussion.models.tsx
> +  sourceType: string
Good idea, fixed in https://github.com/ONEARMY/community-platform/pull/3092/commits/b2a8693f96c1efb7b3f6df81e87cd8dfc9076bf4

2023-12-22 16:28 UTC, thisislawatts commented on src/stores/Discussions/discussions.store.tsx
> +import { changeUserReferenceToPlainText } from '../common/mentions'
Happy to adopt a standard here but please lets make that something that can be enforced (and ideally fixed) using automated tools. Otherwise the burden sits on human reviewers to keep this consistent. I think dropping the format method a3275d59277062df24a5ab6b13d15fa5bab920aa, fixed this for the store file though.

2023-12-22 16:30 UTC, thisislawatts commented on src/stores/Discussions/discussions.store.tsx
> +          _created: new Date().toISOString(),
That is valid feedback but I would prefer to see this abstraction deferred until there are more call sites which make it a necessary. Until then I believe it is more readable to keep this inlined.

2023-12-22 16:31 UTC, thisislawatts commented on src/stores/Discussions/discussions.store.tsx
> +      const comment = text.slice(0, MAX_COMMENT_LENGTH).trim()
I believe that is something which would already be caught when interacting with the form components. This is a defensive mechanism in case someone has slipped (or hacked) past the UI protection.

2023-12-22 16:34 UTC, thisislawatts commented on src/stores/Discussions/discussions.store.tsx
> +      const comment = text.slice(0, MAX_COMMENT_LENGTH).trim()
At the moment this behaviour also exists in the howto and research stores. If we want to change it we should aim for the modules to be consistent.

2023-12-22 16:35 UTC, thisislawatts commented on src/stores/Discussions/discussions.store.tsx
> +  public formatComments(
A very valid point, I thought about it but it had a test so I gave it a cheeky pass. Removed in a3275d59277062df24a5ab6b13d15fa5bab920aa

2023-12-22 16:36 UTC, thisislawatts commented on src/stores/Discussions/discussions.store.tsx
> +      }
Fixed in a3275d59277062df24a5ab6b13d15fa5bab920aa

2023-12-22 16:37 UTC, thisislawatts commented on src/stores/Discussions/discussions.store.tsx
> +        }
Fixed in: 3c5a6e8179f0f4a0f8446cd435ecee039ee86315

2023-12-22 16:38 UTC, thisislawatts commented on src/models/index.ts
> +  showReplies: boolean
Good catch 🦅 👀, fixed in 4cdffbbfe3bd4a2e05d461ccbf7a7764aed02465

2023-12-22 16:40 UTC, thisislawatts commented on src/stores/Discussions/discussions.store.tsx
> +  public async fetchDiscussion(sourceId: string): Promise<IDiscussion | null> {
My preference would to use camelcase for variable names rather than have to many leading underscores floating about.

2023-12-22 16:43 UTC, thisislawatts commented on src/stores/Discussions/discussions.store.tsx
> +            this.userStore.activeUser?.userName,
No longer relevant as the enclosing method has been removed.

2023-12-22 16:53 UTC, thisislawatts commented
> Is adding Discussion to the IStores list on src/stores/index missing?
Good spot, I missed this as I have not integrated this store anywhere.

2023-12-22 17:32 UTC, benfurber requested changes
Still requesting changes as I think what fetchDiscussion should be doing is wrong.

2023-12-22 17:32 UTC, benfurber commented on src/stores/Discussions/discussions.store.tsx
> +  public async fetchDiscussion(sourceId: string): Promise<IDiscussion | null> {
Sorry my question wasn't clear. With the name of `fetchDiscussion` I assume this method is for fetching an individual dicussion by the unique identified, isn't `_id` the unique identifier?

2023-12-22 17:32 UTC, benfurber commented on src/models/discussion.models.tsx
> +}
(Thought I could have had on the last review) What's the thinking of extended IComment rather than adding `parentCommentId` to IComment?

2023-12-22 17:32 UTC, benfurber commented on src/stores/Discussions/discussion.store.test.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
Having all these exclusions inline makes the readability more difficult. Can you not exclude once at the top of the file?

2023-12-22 23:45 UTC, thisislawatts commented on src/stores/Discussions/discussions.store.tsx
> +  public async fetchDiscussion(sourceId: string): Promise<IDiscussion | null> {
Ah sorry, I misunderstood. The intention is for a Discussion document to contain a reference to the source content item (question, how-to or research). I have renamed the method to better reflect this relationship: fd41225c087be066ab930ac75a6ea249ccf5247b

2023-12-22 23:57 UTC, thisislawatts commented on src/models/discussion.models.tsx
> +}
I thought that adding this to the parent IComment type would run the risk of "leaking" the concept of parentCommentId to code interacting with the existing Comment data objects and it is really only something we want to exist within a Discussion data object. Eventually when all of the content is migrated across to use the new comment format we should be able to merge these interfaces and drop one of them.

2023-12-23 12:07 UTC, thisislawatts commented
@benfurber, I have made some changes to the fetchDiscussion method. Could you take another look. 

I appreciate the readability remark on the code comments around the test setup. We have this in a few different places so maybe we can look at this in a separate PR. Do you think it should block the other additions being made here?

2023-12-23 12:11 UTC, benfurber approved these changes
Lovely. I think we're all good now.

2023-12-23 15:27 UTC, merged

2023-12-29 13:06 UTC, mariojsnunes commented on src/stores/Discussions/discussions.store.tsx
> +    discussion: IDiscussion,
should be enough to pass the discussionId

2023-12-29 13:34 UTC, mariojsnunes commented on src/stores/Discussions/discussions.store.tsx
> +    commentId?: string,
this should be called parentCommentId to avoid confusion