feat(research): select and validate research collaborators usernames
ONEARMY/community-platform pull request #3127
Opened 2023-12-30 19:26 UTC by goratt12

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

- Changed the research collaborators input from Text to Select,
- Automatically fetch relevant users from DB based on user input.
- Validate a username exist in the users collection before assigning it as collaborator.

## Git Issues

Closes #2409 

## Screenshots/Videos

![image](https://github.com/ONEARMY/community-platform/assets/23094928/a67f418a-55e1-451f-8e2a-6c762412f9b8)

![image](https://github.com/ONEARMY/community-platform/assets/23094928/2dbb626f-d51c-4423-9752-f32304be39d1)

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2023-12-30 22:03 UTC, davehakkens commented
that works really nice!

2023-12-31 17:17 UTC, davehakkens commented
Did notice some usernames are double. I think this is due to a bug we had at some point duplicating accounts. 
This might be on live as well (didnt test). In that case we should probably clean them up first to avoid confusement. 

<img width="786" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/6db65be0-a94c-475c-a99f-28b70193ce34">

2023-12-31 18:56 UTC, goratt12 commented
> Did notice some usernames are double. I think this is due to a bug we had at some point duplicating accounts. This might be on live as well (didnt test). In that case we should probably clean them up first to avoid confusement.
> 
> <img alt="afbeelding" width="786" src="https://private-user-images.githubusercontent.com/13672737/293516747-6db65be0-a94c-475c-a99f-28b70193ce34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNDgwNDMsIm5iZiI6MTcwNDA0Nzc0MywicGF0aCI6Ii8xMzY3MjczNy8yOTM1MTY3NDctNmRiNjViZTAtYTk0Yy00NzVjLWE5OWYtMjhiNzAxOTNjZTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE4MzU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YzA2MDJhYWU1NjQzMDg1MThjMTJhYzBkNzFjMTgzMDc4MjcwMWM3YzQxMmI3OGYyMjE2YjY2NDdjN2ExMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wkPFK1VOiOAc1s7_KgNDa2yZ4wN9FwkmIvL5N3ej5WE">

Thanks for noticing that 💪

2024-01-03 15:02 UTC, benfurber requested changes
Nice, thanks @goratt12. Some bits a pieces in the review. 

The other thing I think it needs is a cypress test.

2024-01-03 15:02 UTC, benfurber commented on src/pages/common/UserNameSelect/UserNameSelect.tsx
> +          await userStore.getUsersStartingWith(inputVal, 20)
Could you please set this 20 as a const at the top of the file please. I'm thinking `USER_RESULTS_LIMIT` or similar.

2024-01-03 15:02 UTC, benfurber commented on src/stores/User/user.store.ts
> +  }
Is this a change pulled in from somewhere else? I don't see it used elsewhere in the PR.

2024-01-03 18:28 UTC, goratt12 commented on src/pages/common/UserNameSelect/UserNameSelect.tsx
> +  input: any
Done :)

2024-01-03 18:28 UTC, goratt12 commented on src/pages/common/UserNameSelect/UserNameSelect.tsx
> +  ({ input, defaultOptions, placeholder, isForm }: IProps) => {
Done :)

2024-01-03 18:28 UTC, goratt12 commented on src/pages/common/UserNameSelect/UserNameSelect.tsx
> +    const loadOptions = async (inputVal: string) => {
I'm not sure I understand what is a tested util, can you please explain?

2024-01-03 18:29 UTC, goratt12 commented on src/pages/common/UserNameSelect/UserNameSelect.tsx
> +        value={
Done :)

2024-01-03 18:29 UTC, goratt12 commented on src/stores/User/user.store.ts
> +  }
I'm not sure why its included in my commit, I only wrote the `getUsersStartingWith` function

2024-01-03 18:29 UTC, goratt12 commented on src/stores/User/user.store.ts
> +
I'm not sure why its included in my commit, I only wrote the `getUsersStartingWith` function

2024-01-03 18:29 UTC, goratt12 commented on src/pages/common/UserNameSelect/UserNameSelect.tsx
> +        )
You are correct, I moved it

2024-01-03 18:29 UTC, goratt12 commented on src/pages/common/UserNameSelect/UserNameSelect.tsx
> +          await userStore.getUsersStartingWith(inputVal, 20)
Done :)

2024-01-03 18:29 UTC, goratt12 commented on src/stores/User/user.store.ts
> +  }
I'm not sure why its included in my commit, I only wrote the `getUsersStartingWith` function

2024-01-05 16:00 UTC, benfurber commented on src/pages/common/UserNameSelect/UserNameSelect.tsx
> +    const loadOptions = async (inputVal: string) => {
I mean you could put most of this logic into a utility file (which can have some simple unit tests) and import it in so that your useEffect would end up looking something like:
```
  useEffect(() => {
    const fetchOptions = () => {
        try {
            const options = await loadUserNameOptions(inputValue)
            setOptions(options)
        } catch (error) {
           logger.error('Failed to fetch userName options', { error })
        }
    }
    fetchOptions()
  }, [inputValue])

2024-01-05 16:01 UTC, benfurber commented
Hey @goratt12, I think you're still working on this as some of the changes you say are done haven't been pushed up yet? :)

2024-01-06 07:17 UTC, goratt12 commented
> Hey @goratt12, I think you're still working on this as some of the changes you say are done haven't been pushed up yet? :)

Hey :) I pushed all the changes from my local repo, what Change Requests did I resolve and missed?

2024-01-10 21:20 UTC, davehakkens commented
@iSCJT this PR could also be a nice one to merge before research goes live. 
Would probably avoid some issues when adding collaborators

2024-01-10 23:55 UTC, iSCJT commented on src/pages/common/UserNameSelect/UserNameSelect.tsx
> +        value={
@goratt12 I think this is one of the ones @benfurber meant.

2024-01-10 23:57 UTC, iSCJT commented on src/stores/User/user.store.ts
> +  }
There's a merge conflict on this file now so I'll sort this and the others like this when we merge.

2024-01-10 23:57 UTC, iSCJT commented on src/stores/User/user.store.ts
> +
There's a merge conflict on this file now so I'll sort this and the others like this when we merge.

2024-01-10 23:57 UTC, iSCJT commented on src/stores/User/user.store.ts
> +  }
There's a merge conflict on this file now so I'll sort this and the others like this when we merge.

2024-01-11 00:04 UTC, iSCJT commented
> @iSCJT this PR could also be a nice one to merge before research goes live. Would probably avoid some issues when adding collaborators

Ok, I'll keep my eye on it.  I think it's in a state we can merge it and pick up the other changes @benfurber wanted in a subsequent pr if @goratt12 isn't able to do them in the next couple of days.

I'll add it to my list to look into the duplicate users again 😢  The method we're using here to give a unique list will work fine as we're just saving the username and not the id.

2024-01-11 19:54 UTC, goratt12 commented on src/pages/common/UserNameSelect/UserNameSelect.tsx
> +    const loadOptions = async (inputVal: string) => {
I just pushed a commit that moved this logic to a separate file as you suggested.
I didn't know what the recommended location is for this type of files so currently its next to `UserNameSelect.tsx`
If there is better location I will move it :)

2024-01-22 20:31 UTC, iSCJT approved these changes
Getting this merged.  Thanks @goratt12

2024-01-22 20:33 UTC, merged