feat: add header (search, filter, sort) to question's page
ONEARMY/community-platform pull request #3151
Opened 2024-01-04 19:43 UTC by Shamauk

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

# Description
- Updated SortFilterHeader to take the type question and render category filter, sort dropdown and search box. 
- Updated FilterSorterDecorator to include as ItemSortingOption:  LeastComments and LatestComments. 
- Updated question.store to be able to search, sort and filter.
- Added to QuestionListing the SortFilterHeader. 
- Created new file src/stores/utils.ts with a function that checks if a store has author functionality (if not then SortFilterHeader does not render Filter by author dropdown)

# Git issues
closes #2969, #2968, #2967

2024-01-06 13:58 UTC, AlfonsoGhislieri requested changes
Thanks for this @Shamauk, some issues that have to be addressed, let me know if anything doesn't make sense!

2024-01-06 13:58 UTC, AlfonsoGhislieri commented on src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
> +    return this.sortByComments(listItems).reverse()
**Issue**: This new feature doesn't seem to be relevant to the linked issues which are adding the already existing filter options to the new questions module. So lets keep the focus narrowed.

Also @davehakkens  can also maybe jump in here as to whether or not we want to also in general add a filter for Least and Latest comments? As this should be tackled as a separate issue.

2024-01-06 13:58 UTC, AlfonsoGhislieri commented on src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
> +    return [...listItems].sort((a, b) => {
Same as above here, let's narrow the scope this PR.

2024-01-06 13:58 UTC, AlfonsoGhislieri commented on src/pages/common/SortFilterHeader/SortFilterHeader.tsx
**Question**: I appreciate the addition of a guard clause here, but shouldn't the questions also have an author/creator realistically? I have been out of the loop in regards to the new module, but I would assume we want to allow sorting of questions by author/creator. @thisislawatts?

2024-01-06 13:58 UTC, AlfonsoGhislieri commented on src/stores/utils.ts
> +  )
**Praise/Issue**: thanks for adding this, not sure if it will be needed if the questions store is updated to also have the same functionality as the howto and research store. But an extra guard clause is always nice to prevent errors! :)

However, it would also be good practice when adding a function like this one to make it more extensible and maintainable without requiring constant updates for new store types (if we were to ever add/modify them). So something like creating an interface and performing the validation check could be a more flexible approach.

2024-01-06 13:58 UTC, AlfonsoGhislieri commented on src/stores/Question/question.store.tsx
> +          this.isFetching = false
Issue: The handling of the readiness of a component should be handled by the component itself ideally rather than separating away into the store, will also make things less readable and harder to maintain.

2024-01-06 13:58 UTC, AlfonsoGhislieri commented on src/pages/Question/QuestionListing.tsx
> -  }, [])
I would keep the management of readiness of a component inside the actual component.

2024-01-06 15:12 UTC, Shamauk commented on src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
> +    return this.sortByComments(listItems).reverse()
Took the inspiration from here:

https://github.com/ONEARMY/community-platform/issues/2968#issuecomment-1829520087

2024-01-06 15:26 UTC, AlfonsoGhislieri commented on src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
> +    return this.sortByComments(listItems).reverse()
Lovely, then if you're still interested in adding those could you please make a seperate PR and add some tests as well to make sure they are all in order :-)

2024-01-06 15:30 UTC, Shamauk commented on src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
> +    return this.sortByComments(listItems).reverse()
Yes, I'll do it.

2024-01-06 16:30 UTC, Shamauk commented on src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
> +    return this.sortByComments(listItems).reverse()
Just a question:

From _sortByComments_ we have:
`const totalCommentsA = a.comments?.length || calculateTotalComments(a)`

It will get the length either from the comments property or if not there it will calculateTotalComments which is a bit misleading since it counts the number of comments under the updates property. 

I just want to ask if it is safe to assume this – that comments are _either_ under comments or updates->comments.
Just want to know for future proofness and for my testing.

2024-01-06 18:13 UTC, thisislawatts commented on src/stores/utils.ts
> +  )
@Shamauk a small ask. We already have a few overloaded `utils.ts` files floating around. Instead please see the src/stores/common directory for an example of how we share functionality between the stores at the moment.

2024-01-06 22:40 UTC, Shamauk commented on src/pages/Question/QuestionListing.tsx
> -  }, [])
Thanks again for all the responses, this is for this reply and the previous: I essentially followed the same methodology as Research which you can see in `ResearchList.tsx` and `research.store.tsx`. Not sure if I am missing something from Question that would make it differ?

2024-01-08 15:12 UTC, AlfonsoGhislieri commented on src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
> +    return this.sortByComments(listItems).reverse()
That is correct! That is because for some items the comments are for the different updates rather than directly across the entire item

2024-01-08 15:23 UTC, AlfonsoGhislieri commented on src/pages/Question/QuestionListing.tsx
> -  }, [])
Yeah I just had a look at it does seem to be a bit of discrepancy as the research store is using this but the other stores like Howto's are not. I would personally prefer to keep it simple and in the component, but this approach does has the added benefit of not making unnecessary fetches every time the page is loaded.

So disregard my last comment :-)

2024-01-16 09:22 UTC, AlfonsoGhislieri approved these changes
Thanks for the changes! Just have to resolve the conflicted files :-)

2024-01-17 17:54 UTC, merged

2024-01-17 17:55 UTC, thisislawatts commented
@all-contributors add @Shamauk for code.