feat: question filters
ONEARMY/community-platform pull request #3349
Opened 2024-03-14 14:30 UTC by mariojsnunes

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Followup on https://github.com/ONEARMY/community-platform/pull/3121, #3222

Queries firebase directly for fetching questions, with pagination.
It's possible to filter, sort, and load more items.

This is the new approach, ready for server-side rendering, which doesn't use mobx/fuse.js.
Items are always requested from the database on each search/filter.
Fetches only 10 (configurable) items at a time, instead of the whole collection.

Using the new, modular API from firestore. https://firebase.google.com/docs/firestore/query-data/queries#or_queries
(required for or queries)

Deprecated Random filter as they are not possible with firestore queries.
Search no longer supports fuzziness, but I don't think it's that useful or a blocker.

## Git Issues

Closes https://github.com/ONEARMY/community-platform/issues/2968
Solves https://github.com/ONEARMY/community-platform/issues/3307 for Questions Module

2024-03-15 10:04 UTC, benfurber requested changes
That service is so nice to read @mariojsnunes. Love all this. And the questions load so much faster!

2024-03-15 10:04 UTC, benfurber commented on src/stores/Question/question.store.tsx
> +      keywords: Array.from(keywords),
The tests should be updated to cover this.

2024-03-15 10:04 UTC, benfurber commented on src/utils/searchHelper.ts
> +import { stopwords } from './stopwords'
Would love a little test or two for this util please. Perfect low hanging fruit to keep the coverage OK.

2024-03-15 10:04 UTC, benfurber commented on src/utils/stopwords.ts
> +export const stopwords = new Set([
I assume this list of words came from somewhere? Worth referencing in a comment in the file?

2024-03-17 08:50 UTC, mariojsnunes commented on src/pages/Question/QuestionListing.tsx
> +    skipFrom?: QueryDocumentSnapshot<DocumentData, DocumentData>,
Fair point, ideally firestore would support passing the item id, but I could only make it work passing the document snapshot. Maybe we could store it in memory at the service, but that could lead to other issues. I think this is the best option for now.

2024-03-21 08:36 UTC, mariojsnunes commented on src/stores/Question/question.store.tsx
> +      keywords: Array.from(keywords),
Can we do this on another PR? For SSR, this store will have to be removed. I could work on that next.

2024-03-21 08:36 UTC, mariojsnunes commented on src/pages/Question/question.service.ts
> +import {
done!

2024-03-21 08:36 UTC, mariojsnunes commented on src/utils/searchHelper.ts
> +import { stopwords } from './stopwords'
done!

2024-03-21 08:39 UTC, mariojsnunes commented
I've added ts-jest package to make it easier to run tests locally

2024-03-25 09:44 UTC, benfurber approved these changes

2024-03-25 09:44 UTC, benfurber commented on src/pages/Question/labels.ts
> +  list: 'Ask your questions and help others out',
This undoes some copy changes I made based on user feedback.

2024-03-25 09:44 UTC, benfurber commented on src/pages/Question/labels.ts
> +  list: 'Ask your questions and help others out',
If there's only little things like this that need changing, I hope you don't mind me going to the branch myself so I can get this all merged in asap.

2024-03-25 10:07 UTC, mariojsnunes commented on src/pages/Question/labels.ts
> +  list: 'Ask your questions and help others out',
not at all, please go ahead

2024-03-25 13:13 UTC, merged