refactor: replace tag components across how-to and research
ONEARMY/community-platform pull request #3367
Opened 2024-03-16 16:36 UTC by simontree

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description
Refactoring of components using tagList as described in the issues ticket.

## Git Issues

Closes #3357

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2024-03-18 10:07 UTC, benfurber requested changes
Thanks for this @simontree. I think this needs to go further. The idea is that no tagList needs to be set to any content type. `<content>.tags` should be fine to give to TagList without any faff.

2024-03-18 10:07 UTC, benfurber commented on src/pages/Howto/Content/Howto/Howto.tsx
> +   tagList: <TagList tags={activeHowto.tags as ISelectedTags}/>
Can't all this be removed because of the changes made in `HowtoDescription.tsx`?

2024-03-18 10:07 UTC, benfurber commented on src/pages/Howto/Content/HowtoList/HowtoList.tsx
> +    tagList: <TagList tags={howto.tags as ISelectedTags}/>
Is this needed at all anymore?

2024-03-18 10:07 UTC, benfurber commented on src/pages/Research/Content/ResearchDescription.tsx
> +import { Link, useNavigate } from "react-router-dom";
I don't think this has been linted right?

2024-03-18 10:07 UTC, benfurber commented on src/pages/Research/Content/ResearchArticle.tsx
> +    tagList: <TagList tags={item.tags as ISelectedTags}/>
This shouldn't be needed.

2024-03-18 10:07 UTC, benfurber commented on src/pages/Research/Content/ResearchList.tsx
> +      tagList: <TagList tags={research.tags as ISelectedTags}/>
Is this needed?

2024-03-20 19:49 UTC, simontree commented
> Thanks for this @simontree. I think this needs to go further. The idea is that no tagList needs to be set to any content type. `<content>.tags` should be fine to give to TagList without any faff.

Hey @benfurber - sorry, I was working on some other things. Also, I am new to open source issues. Is there any time you suggest until this ticket should be solved ideally? Also I would be interested in joining the monthly dev call if thats okay? If yes, what would be the next time you guys are meeting up?

All the best!

2024-03-22 14:06 UTC, simontree commented on src/pages/Howto/Content/Howto/Howto.tsx
> +   tagList: <TagList tags={activeHowto.tags as ISelectedTags}/>
@benfurber Yes you are right, removed it and tagList is still visible.

2024-03-22 14:12 UTC, simontree commented on src/pages/Howto/Content/HowtoList/HowtoList.tsx
> +    tagList: <TagList tags={howto.tags as ISelectedTags}/>
I can delete that, too @benfurber. Where actually should this tagList be visible? According to src/pages/howto/howto.tsx - it should be within howtopage itself (s. screenshot), right?

![2024-03-22_15-11](https://github.com/ONEARMY/community-platform/assets/59532700/154c38dd-d840-4459-9b6f-3a20c7d1adea)

2024-03-22 14:20 UTC, simontree commented on src/pages/Research/Content/ResearchDescription.tsx
> +import { Link, useNavigate } from "react-router-dom";
done :)

2024-03-22 14:20 UTC, simontree commented on src/pages/Research/Content/ResearchArticle.tsx
> +    tagList: <TagList tags={item.tags as ISelectedTags}/>
ok removed it

2024-03-22 14:20 UTC, simontree commented on src/pages/Research/Content/ResearchList.tsx
> +      tagList: <TagList tags={research.tags as ISelectedTags}/>
also removed it

2024-03-27 09:46 UTC, benfurber commented on src/pages/Howto/Content/HowtoList/HowtoList.tsx
> +    tagList: <TagList tags={howto.tags as ISelectedTags}/>
Not sure I understand what you mean?

2024-03-28 10:35 UTC, closed without merging

2024-03-28 10:41 UTC, simontree commented on src/pages/Howto/Content/HowtoList/HowtoList.tsx
> +    tagList: <TagList tags={howto.tags as ISelectedTags}/>
Ok nvm - I thought the tags should be visible on how-to-list page (my screenshot above) but its only passed down within the component.

2024-03-28 10:42 UTC, simontree commented on src/pages/Research/Content/ResearchDescription.tsx
> +import { Link, useNavigate } from "react-router-dom";
Sorry, linting didn't work via yarn lint hence I did it manually for this file. I am trying to check on why "yarn lint" didnt work

2024-03-28 11:58 UTC, benfurber commented on src/pages/Research/Content/ResearchDescription.tsx
> +import { Link, useNavigate } from "react-router-dom";
@simontree 'yarn format' is the command to run.

2024-03-28 13:16 UTC, benfurber commented
Hey @simontree. Did you mean to close the PR?

2024-03-28 15:22 UTC, simontree commented
> Hey @simontree. Did you mean to close the PR?

sorry - this happened by accident after testing to get git worktree working on my end - will create a new PR