docs: outline steps for rollback
ONEARMY/community-platform pull request #3465
Opened 2024-04-21 13:00 UTC by thisislawatts

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2024-04-29 09:16 UTC, benfurber requested changes
Awesome, thank you @thisislawatts! A couple of typos and a linting and good to go.

2024-04-29 09:16 UTC, benfurber commented on packages/documentation/docs/Maintainers/Rollback.md
> +Usk the CircleCI to perform the rollback deployment so that we go through the same steps as a normal deployment.
Typo: 'Use' instead of 'Usk'.

2024-04-29 09:16 UTC, benfurber commented on packages/documentation/docs/Maintainers/Rollback.md
> +Sure, here are the steps to rollback a release in a clearer and more structured format:
Typo? 'So' instead of 'Sure'?

2024-05-03 12:10 UTC, thisislawatts commented
Thanks for catching those typos @benfurber ✨

2024-05-07 14:20 UTC, merged