feat: deep link into impact section in settings page
ONEARMY/community-platform pull request #3471
Opened 2024-04-22 16:07 UTC by paposeco

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

It is now possible to link to the Impact section on the Settings page, for a given year. By adding ?section=impact."wantedyear" to the /settings url, the Impact section is expanded and the user is taken to the provided year. If impact data is missing from a user's profile, by clicking on the "Edit data" from the profile, the user will also be taken straight to the right place on the settings page. 

(for example: /settings?section=impact.2022 will take you to the 2022 Impact section on the settings page)

## Git Issues

Closes # 3055

2024-04-22 16:52 UTC, mariojsnunes requested changes

2024-04-22 16:52 UTC, mariojsnunes commented on src/pages/User/impact/ImpactMissing.tsx
> -        <a href="/settings">
I think we should use the # as it's the standard for this kind of behavior:
```<a href={`/settings#impact_${year}`}>```
and at [ImpactYear.section.tsx](https://github.com/ONEARMY/community-platform/pull/3471/files#diff-f70ea2e69bb16c980f0f06f3a55704a9e5e6c48d281dc633ad6bdec42394d907), the `<Heading>` would have ```id="{`/settings#impact_${year}`}"```

2024-04-22 16:52 UTC, mariojsnunes commented on src/pages/UserSettings/content/formSections/Impact/ImpactYear.section.tsx
>        <a id="impact"></a>
I know this line was here before, but it doesn't make much sense to me... can be removed if you confirm it's not needed

2024-04-22 16:52 UTC, mariojsnunes commented on src/pages/UserSettings/content/formSections/Impact/ImpactYear.section.tsx
> +export const ImpactYearSection = observer(({ year, target }: Props) => {
I think we can simplify this PR a lot if we move all the logic to this component.
`const { hash } = useLocation();`
```
useEffect(() => {
// logic to check if hash is valid
// scroll to ImpactYearSection
}, [hash])
```
This way we avoid passing 3 layers of props

2024-05-06 10:05 UTC, paposeco commented on src/pages/UserSettings/content/formSections/Impact/ImpactYear.section.tsx
> +export const ImpactYearSection = observer(({ year, target }: Props) => {
Thanks for the feedback and I'm sorry for the delay in getting back to you. I've made the changes you suggested, but haven't submitted them yet. Should I just make a new commit to this branch? (I'm a newbie in case you couldn't tell).

2024-05-09 12:37 UTC, benfurber commented
Awesome! Thanks @paposeco!

2024-05-09 12:37 UTC, merged