3477 e2e flaky tests
ONEARMY/community-platform pull request #3489
Opened 2024-04-30 16:06 UTC by tuliobluz

PR Checklist

- [ x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

To solve some flaky tests regarding the issue https://github.com/ONEARMY/community-platform/issues/3477, I made some small adjusts:

1. [Can contact profiles by default]
I add the **email** to the index to the schema.

2. [By Authenticated] and [Warning on leaving page]
I add the tag `data-cy` to the `lazy loading` to use it as a dynamic wait. Before clicking on the create button of How To, Question, and Research now we are waiting for the lazy loading not to exist.

I am still not sure If this will solve this flaky. We need to keep eye on it.

3. [by default should render all accepted pins]
It looks like it was fixed with previous PRs, I rebased it and could not reproduce it again. I will keep an eye on it.

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2024-05-01 08:09 UTC, benfurber requested changes
Nice one, thanks @tuliobluz.

2024-05-01 08:09 UTC, benfurber commented on src/stores/databaseV2/clients/DexieClient.ts
> +  messages: `${DEFAULT_SCHEMA},email`,
Thanks for working out the issue I created by not populating the database with an email. This isn't the way to do it though and is probably why the build is failing.

If you have a look at #3375 you'll see how to add some initital mock data for the cy tests.

2024-05-01 08:09 UTC, benfurber commented on packages/components/src/Loader/Loader.tsx
> +            data-cy="lazy-loading"
Really like this approach. Smart. I think `loader` is a better name though.

2024-05-01 15:59 UTC, tuliobluz commented on src/stores/databaseV2/clients/DexieClient.ts
> +  messages: `${DEFAULT_SCHEMA},email`,
Hello ben, 

I populated the user `settings_machine_new`, with the email `settings_machine_new@example.com` in `shared/mocks/data/users.ts`, is that what you mean, right? However, I am still facing the issue.

`> KeyPath email on object store u9kWQ_messages_rev20231022 is not indexed`

2024-05-02 08:20 UTC, benfurber commented on src/stores/databaseV2/clients/DexieClient.ts
> +  messages: `${DEFAULT_SCHEMA},email`,
Rather than changing the schema, you need to add starter data to the messages store. This is already setup for other document types (categories, howtos, mappins, etc.). #3375 adds discussions and questions into `shared/mocks/data` in the same way you need to add messages.

2024-05-08 13:47 UTC, benfurber commented
Nice one, thank you @tuliobluz!

2024-05-08 13:47 UTC, benfurber commented
@all-contributors please add @tuliobluz for code

2024-05-08 13:47 UTC, merged