feat: research draft list
ONEARMY/community-platform pull request #3522
Opened 2024-05-09 15:31 UTC by mariojsnunes

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

- Ensures only accepted research items appear on the list.
- Adds a new section to display the user's non-accepted research items.

## Git Issues

Closes #3503

## Screenshots/Videos

https://github.com/ONEARMY/community-platform/assets/8073622/ad6b5aa5-2a26-413a-87c8-4c7c1105e191

2024-05-09 15:42 UTC, benfurber requested changes
There's a lot of untested changes in application behaviour here.

In addition to the button component suggestion made in the comments, if everything going on in this header area was wrapped in a component, there could then be a nice set of unit tests to check:

1. Logged out, correct display
2. Logged in but not a research creator, correct display
3. Logged in with permissions.

Also easer then to share across with how-tos.

2024-05-09 15:42 UTC, benfurber commented on src/pages/Research/Content/ResearchList.tsx
> +    'idle' | 'fetching' | 'completed'
Define it as a type above?

2024-05-09 15:42 UTC, benfurber commented on src/pages/Research/Content/ResearchList.tsx
> +    'idle' | 'fetching' | 'completed'
I think some of this logic would be better in something like `DraftContentButton` to keep ResearchList clean.

2024-05-09 15:42 UTC, benfurber commented on src/pages/Research/Content/ResearchList.tsx
> +    'idle' | 'fetching' | 'completed'
Can also then have a nice little set of unit tests for it.

2024-05-09 16:29 UTC, mariojsnunes commented on src/pages/Research/Content/ResearchList.tsx
> +    'idle' | 'fetching' | 'completed'
done :)

2024-05-09 19:52 UTC, codisart commented on src/pages/Research/Content/ResearchList.tsx
> +  const [fetchingDrafts, setFetchingDrafts] = useState<FetchState>('idle')
suggestion: to go with the composition of the DraftButton, we could also do encapsulation of behavior and create a custom hook 

```typescript

const useDrafts = () => {
  const { userStore } = useCommonStores().stores

  const [draftCount, setDraftCount] = useState<number>(0)
  const [drafts, setDrafts] = useState<IResearch.Item[]>([])
  const [showDrafts, setShowDrafts] = useState<boolean>(false)
  const [fetchingDrafts, setFetchingDrafts] = useState<FetchState>('idle')

  useEffect(() => {
    const fetchDraftCount = async () => {
      if (userStore.user?._id) {
        const count = await researchService.getDraftCount(userStore.user!._id)

        setDraftCount(count)
      }
    }
    fetchDraftCount()
  }, [userStore.user?._id])

  const handleShowDrafts = async () => {
    setShowDrafts((showDrafts) => !showDrafts)

    if (fetchingDrafts !== 'idle') {
      return
    }

    setFetchingDrafts('fetching')

    const items = await researchService.getDrafts(userStore.user!._id)
    setDrafts(items)

    setFetchingDrafts('completed')
  }

  return {
    handleShowDrafts,
    isFetchingDrafts: fetchingDrafts === 'fetching',
    showDrafts,
    drafts,
    draftCount
  }
}
```
You can put this custom hook in a separate file and it seems that it could be not difficult to change to make the store or service to use as a param.

you can use it like this 
```typescript
const { handleShowDrafts, isFetchingDrafts, showDrafts, drafts, draftCount } = useDrafts()

{(isFetching || isFetchingDrafts) && <Loader />}

<DraftButton
              showDrafts={showDrafts}
              draftCount={draftCount}
              handleShowDrafts={handleShowDrafts}
            />
```

or 
```typescript
const draftsState = useDrafts()

{(isFetching || draftsState.isFetching) && <Loader />}

<DraftButton draftsState={draftsState} />
```

2024-05-10 04:20 UTC, mariojsnunes commented on src/pages/Research/Content/ResearchList.tsx
> +  const [fetchingDrafts, setFetchingDrafts] = useState<FetchState>('idle')
thank you! it is much better indeed.

2024-05-10 13:02 UTC, mariojsnunes commented
I've resolved the conflicts

2024-05-13 13:38 UTC, benfurber approved these changes
@mariojsnunes! I'm sorry! I've unfairly created a merge conflict for you because of #3528! Good otherwise!

2024-05-13 14:15 UTC, merged