Chore/fix up firebase emulator
ONEARMY/community-platform pull request #3598
Opened 2024-05-26 18:06 UTC by pizzaisdavid

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- chore

## Description
Make the emulator stuff work for the backend. :sweat_smile:

I recommend by reading the updated documentation https://github.com/pizzaisdavid/community-platform/blob/51ed0187aa155337a7d8130895739c08767d9f8e/packages/documentation/docs/Backend%20Development/firebase-emulator.md

2024-05-26 18:07 UTC, pizzaisdavid commented on functions/README.md
> +Some additional, newer information can also be found in [Firebase Emulators Docs](../packages/documentation/docs/Backend%20Development/firebase-emulator.md)
this is technically incorrect, but will be correct once this code is deployed.

(functional review on production.)

2024-05-27 08:50 UTC, mariojsnunes reviewed
great work!

is the `storage_export` folder suposed to be included on git?

2024-05-27 08:50 UTC, mariojsnunes commented on CONTRIBUTING.md
> +#### Option 1
maybe instead of Option 1/2:

1. Cloud based
2. Emulator based

or anything better you come up with :)

2024-05-27 08:50 UTC, mariojsnunes commented on functions/Dockerfile.emulator
> +# TODO: someone else can figure out a good way to install the Firebase CLI.
can you explain why the current way isn't "good"?

2024-05-27 12:03 UTC, pizzaisdavid commented
Something to note: for me, the e2e tests don't run. So actually, the functions e2e job may fail because I edited the firebase.json file.

Currently, the only way to check that is if a maintainer pushes the code or presses the merge button.

2024-05-27 15:00 UTC, pizzaisdavid commented
@mariojsnunes 
> is the `storage_export` folder suposed to be included on git?

Yep, on master you can also see a version of this is already committed similar in other seed data. Hidden in zips or compressed files. If you unzip `functions/data/seed/seed-default.zip` you'll see it there too.

Yep, everything in the `emulator` folder is just the data exported from the emulator with `emulators:export` https://firebase.google.com/docs/emulator-suite/install_and_configure#export_and_import_emulator_data

2024-05-27 15:27 UTC, pizzaisdavid commented
@mariojsnunes feedback addressed. I assume the CI e2e will fail again

2024-05-31 15:54 UTC, pizzaisdavid commented
Looks like I deleted a file that is used in the Cloud Functions tests

2024-06-05 14:29 UTC, benfurber commented on functions/Dockerfile.emulator
> +# Optionally, initial data can be setup by mounting `/app/seed`.
What's needed for this, can you provide the command?

2024-06-05 14:39 UTC, benfurber requested changes
@pizzaisdavid! Amazing! Thank you.

Ran it locally on my mac 14.4.1 and did the basics.

Followed the docs on `packages/documentation/docs/Backend Development/firebase-emulator.md` the command `yarn run backend:emulator:watch` isn't working for me but `docker run -v ./functions:/app/functions -p 4001-4008:4001-4008 -it emulator` on `functions/Dockerfile.emulator` worked fine. Log below.
```
benfurber@Benjamins-Laptop community-platform % yarn run backend:emulator:watch
[1] time="2024-06-05T15:30:13+01:00" level=warning msg="/Users/benfurber/projects/community-platform/docker-compose.yml: `version` is obsolete"
[1] #0 building with "desktop-linux" instance using docker driver
[1]
[1] #1 [emulator internal] load build definition from Dockerfile.emulator
[1] #1 transferring dockerfile: 3.19kB done
[1] #1 DONE 0.0s
[1]
[1] #2 [emulator internal] load metadata for docker.io/library/node:20.9.0-bullseye-slim
[1] #2 DONE 1.2s
[1]
[1] #3 [emulator internal] load .dockerignore
[1] #3 transferring context: 2B done
[1] #3 DONE 0.0s
[1]
[1] #4 [emulator  1/11] FROM docker.io/library/node:20.9.0-bullseye-slim@sha256:330fa0342b6ad2cbdab30ac44195660af5a1f298cc499d8cbdf7496b02ea17d8
[1] #4 DONE 0.0s
[1]
[1] #5 [emulator internal] load build context
[1] #5 transferring context: 155B done
[1] #5 DONE 0.0s
[1]
[1] #6 [emulator 10/11] RUN   echo "#!/bin/bash\n" >> ./export.sh &&   echo "firebase emulators:export --project demo-community-platform-emulated --force ./dump\n" >> ./export.sh &&   chmod +x ./export.sh
[1] #6 CACHED
[1]
[1] #7 [emulator  7/11] COPY ./firebase.storage.rules      ./firebase.storage.rules
[1] #7 CACHED
[1]
[1] #8 [emulator  6/11] COPY ./firebase.json               ./firebase.json
[1] #8 CACHED
[1]
[1] #9 [emulator  9/11] COPY ./firestore.rules             ./firestore.rules
[1] #9 CACHED
[1]
[1] #10 [emulator  3/11] RUN   apt-get update &&   apt-get -y install openjdk-11-jre-headless &&   apt-get -y install nano &&   apt-get clean
[1] #10 CACHED
[1]
[1] #11 [emulator  4/11] RUN npm install -g firebase-tools
[1] #11 CACHED
[1]
[1] #12 [emulator  5/11] RUN   firebase setup:emulators:ui &&   firebase setup:emulators:firestore &&   firebase setup:emulators:database &&   firebase setup:emulators:storage &&   firebase setup:emulators:pubsub
[1] #12 CACHED
[1]
[1] #13 [emulator  2/11] WORKDIR /app
[1] #13 CACHED
[1]
[1] #14 [emulator  8/11] COPY ./firestore.indexes.json      ./firestore.indexes.json
[1] #14 CACHED
[1]
[1] #15 [emulator 11/11] RUN mkdir ./seed
[1] #15 CACHED
[1]
[1] #16 [emulator] exporting to image
[1] #16 exporting layers done
[1] #16 writing image sha256:7342849822d024d537b4826b68bf2ea7661de4c2eb048d80ac19cf7f9ee1f355 done
[1] #16 naming to docker.io/library/community-platform-emulator done
[1] #16 DONE 0.0s
[1]  Container community-platform-emulator-1  Recreate
[1]  Container community-platform-emulator-1  Recreated
[1] Attaching to emulator-1
[1] emulator-1  | ⚠  emulators: You are not currently authenticated so some features may not work correctly. Please run firebase login to authenticate the CLI.
[1] emulator-1  | i  emulators: Starting emulators: auth, functions, firestore, database, hosting, pubsub, storage
[1] emulator-1  | i  emulators: Detected demo project ID "demo-community-platform-emulated", emulated services will use a demo configuration and attempts to access non-emulated services for this project will fail.
[1] emulator-1  | ⚠  functions: You are not signed in to the Firebase CLI. If you have authorized this machine using gcloud application-default credentials those may be discovered and used to access production services.
[1] emulator-1  | i  firestore: Importing data from /app/seed/firestore_export/firestore_export.overall_export_metadata
[1] emulator-1  | i  firestore: Firestore Emulator logging to firestore-debug.log
[1] emulator-1  | ✔  firestore: Firestore Emulator UI websocket is running on 9150.
[1] emulator-1  | ⚠  database: Did not find a Realtime Database rules file specified in a firebase.json config file. The emulator will default to allowing all reads and writes. Learn more about this option: https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration.
[1] emulator-1  | i  database: Database Emulator logging to database-debug.log
[1] emulator-1  | i  emulators: Shutting down emulators.
[1] emulator-1  | i  functions: Stopping Functions Emulator
[1] emulator-1  | i  database: Stopping Database Emulator
[1] emulator-1  | i  firestore: Stopping Firestore Emulator
[1] emulator-1  | i  eventarc: Stopping Eventarc Emulator
[1] emulator-1  | i  hub: Stopping emulator hub
[1] emulator-1  |
[1] emulator-1  | Error: An unexpected error has occurred.
emulator-1 exited with code 2
[1] docker-compose up --force-recreate --build emulator exited with code 0
--> Sending SIGTERM to other processes..
[0] yarn workspace functions watch exited with code 129```

2024-06-05 16:29 UTC, pizzaisdavid commented
The code, as is:

Works on my desktop ✅

```
david@david:~/Documents/community-platform$ docker-compose version
Docker Compose version v2.20.3
```

Doesn't work on my laptop ❌
```
david@joman:~/Documents/community-platform$ docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

2024-06-05 16:43 UTC, pizzaisdavid commented
The code now works on both for me, try it again @benfurber

2024-06-05 16:47 UTC, pizzaisdavid commented on functions/Dockerfile.emulator
> +# Optionally, initial data can be setup by mounting `/app/seed`.
I have added on to the file (`docker run -v ./functions/data/emulator:/seed -v ./functions:/app/functions -p 4001-4008:4001-4008 -it emulator`)

Note the path in the Docker container is now /seed instead of /app/seed

2024-06-06 08:40 UTC, benfurber commented
Docker Compose version 2.27.1
Still not working unfortunately.

Also I don't think the updated seed command worked as expected. It didn't error but going to the app or `http://127.0.0.1:4001/firestore` didn't show any created data.

2024-06-06 16:57 UTC, pizzaisdavid commented
Ben and I had a call, we narrowed it down the issue to being with sharing files from the host machine to the container.

Perhaps due to Mac permissions.

Maybe over the weekend I will try it on my partners Mac. I found some things here: https://stackoverflow.com/questions/55667800/mac-docker-volume-mount-using-osxfs-not-working

But I have at least added some more documentation to help figure developers figure out if it is a problem with our Docker files or their Docker setup.

2024-06-07 17:42 UTC, pizzaisdavid commented
The problem:

```
[debug] [2024-06-07T17:34:11.788Z] Error: ENOENT: no such file or directory, scandir '/app/functions/data/emulator/database_export'
    at Object.readdirSync (node:fs:1513:3)
    at Object.startAll (/usr/local/lib/node_modules/firebase-tools/lib/emulator/controller.js:473:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/local/lib/node_modules/firebase-tools/lib/commands/emulators-start.js:33:43
```

The export is an empty folder, which didn't automatically get checked into Git. Booo!

2024-06-07 22:59 UTC, pizzaisdavid commented
Should be fixed now.

2024-06-12 13:08 UTC, benfurber approved these changes
Awesome. Working for me now @pizzaisdavid.

Will merge in soon. I don't think this has much overlap with the vite migration stuff Mario has been working on but we're just confirming our approach to getting that work through to prod first.

2024-06-12 17:58 UTC, pizzaisdavid commented
rebased (whoop)

2024-06-13 14:10 UTC, merged