feat: display date as time has passed
ONEARMY/community-platform pull request #3840
Opened 2024-09-03 21:11 UTC by onim-at

## PR Checklist

- [X] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix (fixes an issue)
- [X] Feature (adds functionality)
- [ ] Code style update
- [ ] Refactoring (no functional changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?
Dates are shown as timestamp
## What is the new behavior?
Dates are shown as "time has passed"

### To-Do

- [X]   Create component in the library to cover this
- [ ]     At least one example in the end-to-end tests of the 'just now' render of the component displayed.
- [ ]  Fix ResearchArticle.test.tsx

List everywhere it should go:
- [X]         Comments and nested comments across all modules where there are comments
- [X]         Research module listing
- [X]         Single research and research updates
- [X]         Questions module listing
- [X]         Single question
- [X]         Single How-To 

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Git Issues

Closes #3653

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2024-09-04 07:13 UTC, benfurber commented
Nice one so far @onim-at - looks like exactly the right direction. 🥳

2024-09-05 19:06 UTC, onim-at commented
Hello @benfurber! I've added a check on the date in the question cypress test, is this what you intended? 
Also I don't know where to ask so I'll try here, is it possible to join the discord developer chat?

2024-09-06 08:17 UTC, benfurber commented
@onim-at Nice one, thank you. I'll have a look today. [You shoule be able to join discord with this link](https://discord.gg/gJ7Yyk4)

2024-09-06 11:55 UTC, benfurber requested changes
Just the one thing that's an absolute must change with the console log but there's a couple of bits I'd appreciate.

If you have a look at `DiscussionTitle` you'll see a style of stories/tests I think would be good. 

The stories file has a separate function for each display expected (roughly) and then a test checks that each function has the expected output. So in this instance roughly somthing like:

stories:
```
export const TwoMonthsAGo: StoryFn<typeof DisplayDate> = () => {
  const twoMonthsAGo = subMonths(new Date(), 2)
  return (
      <DisplayDate date={twoMonthsAGo}></DisplayDate>
)}
```

test: 
```
describe('DisplayDate', () => {
...
  it('renders correctly when two months ago', () => {
    const { getByText } = render(
      <TwoMonthsAGo {...(TwoMonthsAGo.args as IProps)} />,
    )

    expect(getByText("2 months ago")).toBeInTheDocument()
  })
```

Then it's a quick test of our implementation of the package (not the package itself) and more importantly, prevents a regression.

2024-09-06 11:55 UTC, benfurber commented on packages/components/src/DisplayDate/DisplayDate.tsx
> +  console.log(date)
The linter should have caught this. Please drop the console log.

2024-09-06 15:09 UTC, merged

2024-09-09 14:00 UTC, dalibormrska commented
Looks absolutely awesome! I'm really happy to see it implemented! Great job @onim-at and @benfurber!  🎉