Update map setting display
ONEARMY/community-platform pull request #3862
Opened 2024-09-25 07:30 UTC by LahuenGR

## PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix (fixes an issue)
- [ ] Feature (adds functionality)
- [ ] Code style update
- [ ] Refactoring (no functional changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?
Standard pin showing in the Map Settings and without relevant information
![2024-09-25 04_16_23-Window](https://github.com/user-attachments/assets/e54325da-f11e-4013-9c71-0e575280f12b)

## What is the new behavior?
1) Pin is now showing the profile type design and, when clicked, shows the popup with relevant information
2) Removed one-click option to move the pin and setted it to double-click, as it was not working well with the click-n-popup idea

_Describe the new behaviour_
_If useful, provide screenshot or capture to highlight main changes_

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Git Issues

Closes #3856

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2024-09-25 08:38 UTC, benfurber requested changes
Thanks @LahuenGR. I've added on quick style thing I could see but it's a little hard to review fully as you're pulling in unrelated commits from your other branch. Plus maybe some unrelated model changes?

Also. Have you looked into our cypress tests yet. Any ideas on how to test your change within the existing settings test(s)?

2024-09-25 08:38 UTC, benfurber commented on packages/components/src/MapWithPin/MapWithPin.stories.tsx
> +import React from 'react'
style preference:
```
import { useRef } from 'react'
```

2024-09-25 09:20 UTC, LahuenGR commented
@benfurber I'm not sure why it dragged the commit from the other branch 🤔 let me try to fix it

What model changes are you referring to?

As for the cypress tool... nope, never used it hahaha, i'm going to need some help with that <3

2024-09-25 10:07 UTC, benfurber commented
From QA.

1. Definitely need to increase the map height. If you change your profile type to something other than a member you'll see what I mean.
2. Add onblur to hide the pin when click/tapping the map. This is especially important for mobile.
3. Move the +/- controls to the bottom left, on mobile they nearly overlap with the search for address.
4. For pin onhover change the cursor to grab.
5. I don't think the explainer text is right because it is possible still to grab to move your pin. Let's go with: "To move your pin, grab it to move it or double click where you want it to go. Tap on your pin to see how it'll look on the map.

2024-09-25 13:45 UTC, LahuenGR commented
Did i understand correctly?

https://github.com/user-attachments/assets/c45fdf03-289c-401b-8d6e-f18120beb14f

2024-09-26 09:04 UTC, benfurber requested changes

2024-09-26 09:04 UTC, benfurber commented on src/pages/UserSettings/SettingsPageMapPin.tsx
> +          {mapPin ? yourPinTitle : addPinTitle}
Why this switch in logic? I think it's wrong and why the unit test is failing.

2024-09-26 09:08 UTC, benfurber commented on src/models/index.ts
> -
Always appreciate some tidy-up! But maybe better in a seperate PR as it's unrelated to the scope of this PR.

2024-09-26 09:08 UTC, benfurber commented on src/pages/UserSettings/SettingsPageMapPin.tsx
> +import React, { useEffect, useState } from 'react'
`import { useEffect, useRef, useState } from 'react'

2024-10-08 14:16 UTC, benfurber commented
Hey @LahuenGR I've sorted out the complex rebase that was needed on this branch after we merged in a big refactor.

I've run the branch locally and I think there's a couple more bits to finish. If you won't have time to do it, no worries, just let me know and I can finish it off.

<img width="850" alt="Screenshot 2024-10-08 at 15 03 37" src="https://github.com/user-attachments/assets/cdf6e9fa-7376-4d86-8546-cda5921f69c2">

1. Let's move those controls (+/- and location search) to the top.
2. For some reason the zoom out button doesn't work. Not sure if that relates to your branch or not but if you could take a look that would be awesome.

You're using `ondragstart` and `ondragend` for props with the map. On MapWithList, etc. we use the `onclick` prop to close a pin. Might be worth trying that?

2024-11-05 13:38 UTC, benfurber commented
Hey @LahuenGR, hope you're well. How are you getting on with this? :)

2024-11-20 10:04 UTC, merged

2024-11-20 10:04 UTC, benfurber commented
Thanks for your work on this @LahuenGR!