refactor: elevate download with donation to component level
ONEARMY/community-platform pull request #3869
Opened 2024-09-27 03:18 UTC by mchen10

## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix (fixes an issue)
- [ ] Feature (adds functionality)
- [ ] Code style update
- [x] Refactoring (no functional changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?

The donation modal only shows up in one place in the app that uses `DownloadWithDonationAsk`. 

## What is the new behavior?

We want to start showing the modal everywhere where files are downloaded, so I'm elevating `DownloadWithDonationAsk` to the component level. Immediately, this means that for research update downloads, we will show the donation modal.

https://github.com/user-attachments/assets/531c7827-5396-43d0-b341-847a70098153

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Git Issues

Closes #3858

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2024-09-27 03:24 UTC, mchen10 commented
I would love to get some advice on verifying that the component level test + Storybook are correct. 

For the component level test, I'm running `yarn test` from `src/components`, and I'm pretty sure the test is failing, but I can't actually find any logs or indication for why the failure is happening.

Storybook just isn't loading for me properly either; a combo of `TypeError: Failed to fetch dynamically imported module: http://localhost:6006/src/DownloadFileFromLink/DownloadFileFromLink.stories.tsx` and `Cannot find module '@babel/preset-react'`. The former is only happening for `DownloadFileFromLink`, which makes me suspect something is just wrong with the component/Storybook, but the latter error is happening across Storybook, which feels like something is wrong with my storybook setup.

2024-09-27 03:25 UTC, mchen10 commented on packages/components/src/DownloadFileFromLink/types.ts
> +export interface IUploadedFileMeta {
Let me know your thoughts on this! The type is important, but since components are hosted in a separate package, I couldn't access the type in the src/pages package.

2024-09-27 03:26 UTC, mchen10 commented on packages/components/src/DownloadFileFromLink/types.ts
> +export interface IUploadedFileMeta {
That type hasn't been updated in years, so it feels like there won't be too much maintenance burden between the two identical types

2024-09-27 19:06 UTC, jsonDoge commented on packages/components/src/DownloadFileFromLink/DownloadFileFromLink.tsx
> +                key={file ? file.name : `file-${index}`}
Very minor detail and correct me if I'm wrong, but `filteredFiles` already are "filtered", there shouldn't be a case, that `file` is falsy. Maybe worth replacing with:
```
key={file.name || `file-${index}`}
```
or this if name is optional
```
key={file?.name || `file-${index}`}
```
or even better if all files have names
```
key={file.name}
```

2024-09-27 19:33 UTC, jsonDoge commented on packages/components/src/DownloadFileFromLink/types.ts
> +export interface IUploadedFileMeta {
Adding thoughts, I'd say two options:
  - [Speed is the way] cheap and quick duplicate and leave a comment about other existing matches.
  - [Clean clean clean] there seems to be a shared folder which builds to oa-shared package, which in turn can be used everywhere. This would probably be a good place to put it as there already are some interfaces.
  
Note: the `IImageGalleryItem` looks almost exactly like this interfaces. Extra point to put to shared and creating something like a common interfaces like `FileMeta` and extending other ones.

*also I assume you were talking about the src/stores/storage.tsx - IUploadedFileMeta matching interface, if there are even more more points towards "Clean clean clean".

But would wait for some long time contributors to voice their thoughts too :)

2024-09-30 12:08 UTC, benfurber commented on packages/components/src/DownloadFileFromLink/types.ts
> +export interface IUploadedFileMeta {
We're generally on a "clean, clean, clean" path atm. Speed lead approaches can be valid but that on this project has created too many issues as contributors change so the areas with technical debt/issues is knowledge not passed on. And yes, typings to 'oa-shared' is the current direction. 

#3789 does a lot of type updates, which we're about to merge in and will likely cause a much of conflicts with this branch, apologies.

2024-09-30 12:28 UTC, benfurber requested changes
Awesome, thanks @mchen10!

2024-09-30 12:28 UTC, benfurber commented on src/pages/Howto/Content/Howto/HowtoDownloads/HowtoDownloads.tsx
> +        }}
theme is accessible in the component library, so I don't think this is necessary.

2024-09-30 12:28 UTC, benfurber commented on packages/components/src/DownloadFileFromLink/DownloadFileFromLink.tsx
I'm not sure the right component has been updated here. `DownloadFileFromLink` certainly isn't right as it includes files now as well as links. I was quite happy with the naming of `DownloadWithDonationAsk` - does what it says on the tin.

2024-09-30 12:28 UTC, benfurber commented on packages/components/src/DownloadFileFromLink/DownloadFileFromLink.tsx
> +import type { IThemeStoreDonationProps, IUploadedFileMeta } from './types'
IUploadedFileMeta can definitely be imported from shared.

2024-09-30 12:28 UTC, benfurber commented on packages/components/src/DownloadFileFromLink/DownloadFileFromLink.tsx
> +  files: (IUploadedFileMeta | File | null)[] | undefined
As one or the other will be provided. Both should be optional.

2024-10-11 08:24 UTC, benfurber commented
Hey @mchen10, how are you getting on?

2024-10-15 20:09 UTC, mchen10 commented
> Hey @mchen10, how are you getting on?

Hey sorry, been busy with other parts of life. Will rerequest for review by EOW!

2024-10-19 02:06 UTC, mchen10 commented on src/pages/Howto/Content/Howto/HowtoDownloads/HowtoDownloads.tsx
> +        }}
Hey! Updated to `import.meta.env` because that's the pattern I see here: https://github.com/ONEARMY/community-platform/blob/master/src/common/DownloadWithDonationAsk.tsx#L45, but honestly have never used Vite before so not sure if I'm missing something!

2024-10-19 02:06 UTC, mchen10 commented
> Hey @mchen10, how are you getting on?

Updated @benfurber ! PTAL, thanks

2024-10-19 02:07 UTC, mchen10 commented
> > Hey @mchen10, how are you getting on?
> 
> Updated @benfurber ! PTAL, thank you!

2024-10-19 02:18 UTC, mchen10 commented on src/pages/Howto/Content/Howto/HowtoDownloads/HowtoDownloads.tsx
> +        }}
It feels like I might have to play with `packages/components/tsconfig.json`?

2024-10-22 14:33 UTC, benfurber commented
Weird. Checkout how this branch locally but not getting the build errors. Rerunning CI.

2024-10-22 15:53 UTC, benfurber commented
Thanks for your work on this @mchen10. As there was some issues with the import env stuff I've changed the archectural design a little.

2024-10-22 16:03 UTC, merged