feat: profile views counter
ONEARMY/community-platform pull request #3890
Opened 2024-10-03 18:51 UTC by iSCJT

## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix (fixes an issue)
- [x] Feature (adds functionality)
- [ ] Code style update
- [ ] Refactoring (no functional changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?

Profile views were not logged / displayed.

## What is the new behavior?

When a profile is viewed for the first time in a 'session' then a view is logged against the user profile.  Uses the same logic as for the howto, research and question logging.  One thing to note is that the first time someone views a profile within the session their ow view won't count towards the displayed value.  This is consistent with the other document types.

<img width="948" alt="image" src="https://github.com/user-attachments/assets/5f8ad829-5791-48aa-80ae-6c94adfed8de">

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Git Issues

Closes #

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2024-10-03 19:26 UTC, davehakkens commented
Oe I like it!
I hope @benfurber or @mariojsnunes approves it 🫣
One remark: Could we add it in a beta-tester authwrapper first?

2024-10-03 22:06 UTC, mariojsnunes approved these changes
Looks good. We can merge this as a quick improvement.
But in the short term, these view counter increments will move serve-side.

2024-10-04 10:43 UTC, iSCJT commented
I've added the beta feature wrapper.

2024-10-07 13:08 UTC, benfurber commented
One risk from a product prospective. We're obvs only starting to count now. So seeing a low number of profile views for established users might be demoralising (plus give first time users a misunderstanding of a profile's reach and the depth of the community.

2024-10-07 13:17 UTC, benfurber requested changes
Feature test please! At least to prevent regression of losing the display.

2024-10-07 13:17 UTC, benfurber commented on src/assets/icons/eye.svg
There's an icon for this already.

2024-10-07 13:17 UTC, benfurber commented on src/pages/User/content/MemberProfile.tsx
> +  const total_views = user.total_views || 1
I think if for some reason a total can't be called from the DB, it would be better to show nothing?

2024-10-07 13:17 UTC, benfurber commented on src/pages/User/content/SpaceProfile.tsx
> +                      total_views={renderTotalViews()}
totalViews

2024-10-07 13:17 UTC, benfurber commented on packages/components/src/UserStatistics/UserStatistics.tsx
> +  total_views?: EmotionJSX.Element
Calling the element isn't the style of this component, all the rest are numbers. So I think the approach should be the same.

2024-10-07 13:17 UTC, benfurber commented on shared/mocks/data/users.ts
> +    total_views: 10,
totalViews

2024-10-07 18:41 UTC, iSCJT commented on packages/components/src/UserStatistics/UserStatistics.tsx
> +  total_views?: EmotionJSX.Element
It's like this because we're using the beta feature wrapper.  Think it's the simplest implementation that keeps the UserStatistics component purely as a display component.  Open to pointers on another way of doing it though?

2024-10-07 18:43 UTC, iSCJT commented on src/pages/User/content/MemberProfile.tsx
> +  const total_views = user.total_views || 1
The reason I defaulted to 1 is because the only reason we shouldn't return anything is if it's their first view (or I guess a db error but then I think the whole component doesn't render) but happy to turn off the default.

2024-10-07 18:46 UTC, iSCJT commented on shared/mocks/data/users.ts
> +    total_views: 10,
I've only used total_views to keep it consistent across all the document types so that we can use the same incrementing function and logic for all of them.  We could refactor everywhere?

2024-10-07 19:21 UTC, iSCJT commented on src/assets/icons/eye.svg
I did look for one but didn't think to search for 'view' 🤦

2024-10-07 19:23 UTC, iSCJT commented on src/pages/User/content/MemberProfile.tsx
> +              total_views={renderTotalViews()}
I used render to keep consistent with the space profile naming for other components but will change.

2024-10-08 12:25 UTC, benfurber commented on packages/components/src/UserStatistics/UserStatistics.tsx
> +  total_views?: EmotionJSX.Element
Oh got it, makes sense...

I guess something like adding another props to this component like `showViews` would work. Then the beta wrapper could call that prop but the public one doesn't.

2024-10-08 12:36 UTC, benfurber commented on shared/models/user.ts
> +  total_views?: number
I take your point about consistency, which is why I think it should be totalViews everywhere.

2024-10-08 12:36 UTC, benfurber commented on src/assets/icons/eye.svg
Missed removing this file now you're using the `Icon` component?

2024-10-08 14:37 UTC, iSCJT commented on shared/models/user.ts
> +  total_views?: number
Just been thinking about this and personally don't think it's worth the effort to update every how to, research, question doc to migrate to the new property name.  I think it would be better to pick this up as part of full db migration, there's a number of doc properties that need renaming.

2024-10-08 15:12 UTC, iSCJT commented on packages/components/src/UserStatistics/UserStatistics.tsx
> +  total_views?: EmotionJSX.Element
Just double checked to make sure... we can't use the auth wrapper for individual props.  Think the options are:

1. leave as is
2. not use the standard auth wrapper beta feature and write separate logic that checks whether the user is a beta user and then send the views prop as undefined if not.

2024-10-08 15:22 UTC, iSCJT commented
> One risk from a product prospective. We're obvs only starting to count now. So seeing a low number of profile views for established users might be demoralising (plus give first time users a misunderstanding of a profile's reach and the depth of the community.

This is a good point by the way, we could:

- accept the risk as is (possibly with some indication of when view logging started from)
- build things out more so we can display time bound views, e.g. 'views in last 30 days' although that requires some kind of indication of the time range / less simple screen design
- do without publicly displayed profile views but continue to log them

@davehakkens

2024-10-08 15:36 UTC, davehakkens commented
This is one of the reasons to add it now and start counting in the (beta) background.

We still have time to think about how to display this in a more impactful way

2024-10-09 12:04 UTC, benfurber commented on packages/components/src/UserStatistics/UserStatistics.tsx
> +  total_views?: EmotionJSX.Element
```
<AuthWrapper 
  roleRequired={UserRole.BETA_TESTER}
  fallback={<Component oneSetofProps />}
>
  <Component anotherSetofProps />
</AuthWrapper>

2024-10-16 08:03 UTC, merged