Feat/howto detail ssr
ONEARMY/community-platform pull request #3898
Opened 2024-10-07 22:31 UTC by mariojsnunes

## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Feature (adds functionality)
- [x] Refactoring (no functional changes)

## What is the current behavior?

Howto page is rendered client-side.

## What is the new behavior?

Howto page is rendered server-side.
More notable changes:
- 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Git Issues

Closes #

2024-10-22 14:23 UTC, benfurber requested changes
Nice. 

I think my only strong opinion is the 404/redirect thing.

2024-10-22 14:23 UTC, benfurber commented on src/routes/_.how-to.$slug._index.tsx
> +    return redirect(`/how-to?search=${searchSlug}&source=how-to-not-found`)
I think let's go with the 404. This redirect flow it's a good experience as we don't explain to the user what's happened. I mean that would be a good flow, but that's not this PR.

2024-10-22 18:12 UTC, mariojsnunes commented on packages/cypress/src/integration/profile.spec.ts
> +  // })
the test above already covers the scenario. Was failing because the user is a static one, so the views would keep increasing.

2024-10-22 18:15 UTC, mariojsnunes commented on src/pages/Howto/Content/Howto/Howto.tsx
> -      })
This is the old way. Now we use the remix meta function.
Check here:
https://github.com/ONEARMY/community-platform/pull/3898/files#diff-5af433d069534d5fd2b9cb850b4cc85d3d6936ef5036f23357c19df87b7f09f0

2024-10-22 18:18 UTC, mariojsnunes commented on src/routes/_.how-to.$slug._index.tsx
> +    return redirect(`/how-to?search=${searchSlug}&source=how-to-not-found`)
agreed

2024-10-23 10:58 UTC, benfurber approved these changes

2024-10-23 12:27 UTC, merged