added globe and location buttons to map
ONEARMY/community-platform pull request #3913
Opened 2024-10-22 21:52 UTC by motuz0001

## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix (fixes an issue)
- [x] Feature (adds functionality)
- [ ] Code style update
- [ ] Refactoring (no functional changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?
The map currently does not have a buttons for unzooming to global view and zooming to user's location.

## What is the new behavior?
- Added a globe button that allows users to unzoom to a world view of the map.
- Added a location button that zooms into the user's current geographic location.

![image](https://github.com/user-attachments/assets/637f605f-44d1-4542-95b3-9cbe79ec5e6f)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Git Issues

Closes [#3879](https://github.com/ONEARMY/community-platform/issues/3879)

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

2024-10-26 01:37 UTC, joperafe commented on src/pages/Maps/Content/MapView/MapWithList.tsx
> +      ;(window as any).mapInstance = mapRef.current
```suggestion
      (window as any).mapInstance = mapRef.current;
```

2024-11-05 13:36 UTC, motuz0001 commented
hey @joperafe , I'm not sure if you'll be the one reviewing this or if someone else will, but I think it's finally done. I fought with the tests for a while but eventually found a way to check the zoom. Let me know if any changes are needed or if something is wrong. Thanks!

2024-11-05 15:56 UTC, joperafe commented
> hey @joperafe , I'm not sure if you'll be the one reviewing this or if someone else will, but I think it's finally done. I fought with the tests for a while but eventually found a way to check the zoom. Let me know if any changes are needed or if something is wrong. Thanks!

Hi there! No no, not me. First timer
Just went through the PR back then and decided to say something :D

Thank you

2024-11-05 16:20 UTC, benfurber requested changes
Thank you so much for your contribution @motuz0001! 

One. Can you move the buttons to the top right please. You'll see why below!
<img width="920" alt="Screenshot 2024-11-05 at 16 08 23" src="https://github.com/user-attachments/assets/87e4b6e7-e475-4f0c-bc7a-f30b9e023a85">

Two. There's a lot of custom styles. I'm hoping that when you don't have to position absolute, most of them go away. I'd rather less custom styling that leave the buttons imperfect.

Three. The tooltips don't work for me on Firefox, do they for you?

Thank you for struggling with the feature test, I appreciate it.

2024-11-05 16:20 UTC, benfurber commented on src/pages/Maps/Content/MapView/MapWithList.tsx
> +              setZoom(1)
There's an existing `INITIAL_ZOOM` const on 1Maps.client` that can be used rather than 1.

2024-11-05 16:20 UTC, benfurber commented on src/pages/Maps/Content/MapView/MapWithList.tsx
> +            data-tip="Zoom in to your location"
I'd rather have...
```
const ZOOM_IN_TOOLTIP = "Zoom in to your location"

export const MapWithList = (props: IProps) => {
...
          <Button
            data-tip={ZOOM_IN_TOOLTIP}
```

Make sense?

2024-11-05 16:20 UTC, benfurber commented on src/pages/Maps/Content/MapView/MapWithList.tsx
> +            data-tip="Zoom out to world view"
Same point as above.

2024-11-05 16:54 UTC, benfurber commented
Oh and a complex rebase is needed!

2024-11-07 00:22 UTC, motuz0001 commented
hey @benfurber , I hope all is fixed now and rebase is okay

2024-11-07 13:40 UTC, merged

2024-11-07 13:40 UTC, benfurber commented
Awesome, thank you @motuz0001!

2024-11-07 13:45 UTC, benfurber commented
@all-contributors add @motuz0001 for code