feat: use supabase for question comments
ONEARMY/community-platform pull request #4006
Opened 2024-11-18 00:03 UTC by mariojsnunes

## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Feature (adds functionality)
- [x] Refactoring (no functional changes)

## What is the current behavior?
Current discussions use firebase

## What is the new behavior?
Question comments now use supabase.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## Git Issues

Closes #

2024-11-26 17:03 UTC, benfurber reviewed
Why do all these comment components need recreating?

2024-11-26 17:40 UTC, mariojsnunes commented on src/pages/Question/QuestionSortOptions.ts
> +// BaseOptions.set('LeastComments', 'Least Comments')
it can come back when questions are migrated too

2024-11-26 17:43 UTC, mariojsnunes commented on src/models/comment.model.ts
> +  firebase_auth_id: string
this represents the database schema. The postgres convention is snake_case.
For javascript things, we keep camelCase

2024-11-26 17:44 UTC, mariojsnunes commented on supabase/config.toml
> +[auth.external.apple]
nice find! this was generated automatically

2024-11-26 17:46 UTC, mariojsnunes commented on src/pages/common/CommentsV2/CommentItemV2.tsx
> +export const CommentItemV2 = observer(
yes, still required for the user store, not sure it will ever change, unless we move to another state-management library.

2024-11-26 17:51 UTC, mariojsnunes commented on src/pages/common/CommentsV2/CommentItemV2.tsx
it should if we follow our current practices.
here I prioritized making it work first, then seeing where it fits.
unsure about moving it because of the observer and, having a lot of nested props, like before, was hard to maintain.

2024-11-26 23:09 UTC, davehakkens commented
Is this a new approach to the order in which comments are displayed?
1. Comments: Display oldest on the top, newest on the bottom
2. Nested comments: Display newest on the top, oldest on the bottom

As currently they are aligned and all show oldest on top, newest on the bottom

2024-11-26 23:09 UTC, davehakkens commented
@dalibormrska Good to check out this preview as you are currently working on this

2024-11-27 06:28 UTC, dalibormrska commented
Nice one! The restructuring of the comments and the system with arrow is quite nice! I played around with devtools, but then still it will need some further structuring adjustments if we want to implement the logic that I'm designing for the comments.

<img width="344" alt="image" src="https://github.com/user-attachments/assets/c4d651a3-61ce-430f-8113-2f7496d799d3">

<img width="334" alt="image" src="https://github.com/user-attachments/assets/21516187-c518-4d71-a909-29d974a2c73b">

2024-11-28 11:46 UTC, davehakkens commented
What are the changes we should validate?

1. It seems to work ✅
2. UI Changes. Dalibor has a few more UI changes coming up, but I guess they are outside this PR anyway?

2024-11-28 13:17 UTC, benfurber requested changes

2024-11-28 13:17 UTC, benfurber commented on src/pages/Question/QuestionPage.tsx
> -            },
Sounds like a UI opinion not related to the scope of the PR.

2024-11-28 13:17 UTC, benfurber commented on src/pages/common/CommentsV2/CommentItemV2.tsx
I strongly disagree. Changing another agreed upon design pattern (and the opposite direct I try to go in) shouldn't be in the scope of this PR. It's coupling UI implementation to a DB change. Keeping the two seperate has to be an essential part of this project.

2024-11-29 00:27 UTC, mariojsnunes commented on src/pages/common/CommentsV2/CommentItemV2.tsx
for transparency, we had a chat about this and some conclusions were:
- it's impractical for large components like comment section to exist in a component library
- for smaller components, always consider having them on the component library
- if we are unsure, keep it simple, until we are more certain about which abstraction to go with

Did some extra analysis after the chat:
- `CreateCommentV2` and `CreateReply` were basically the same, so `CreateReply` was removed.
- `CommentItemV2` and `Reply` share a lot of code, but let's wait a bit until the new design bits have matured, in case they differ more.

2024-11-29 23:14 UTC, mariojsnunes commented on src/pages/Question/QuestionPage.tsx
> -            },
added it back

2024-11-30 17:20 UTC, merged